[OP#41504]refactor  OpenProjectAPIService::getOpenProjectAvatar so it uses  Ope…
nextcloud/integration_openproject pull request #102
Opened 2022-04-28 12:21 UTC by SwikritiT

OP#41504

2022-05-11 11:33 UTC, kiranparajuli589 reviewed
lgtm :+1:

2022-05-12 06:47 UTC, individual-it requested changes

2022-05-12 06:47 UTC, individual-it commented on lib/Service/OpenProjectAPIService.php
> +	// @phpstan-ignore-next-line
what do we want to ignore here?

2022-05-12 06:47 UTC, individual-it commented on lib/Service/OpenProjectAPIService.php
> +	public function rawRequest(string $accessToken, string $openprojectUrl,
can be private as its only used inside of this class

2022-05-23 05:40 UTC, individual-it approved these changes

2022-05-23 05:41 UTC, merged