add confirm dialog for admin config update action
nextcloud/integration_openproject pull request #110
Opened 2022-05-06 11:21 UTC by kiranparajuli589

- implement confirm dialog to update admin credentials
- delete user prefs. if updated admin config is not ok

2022-05-13 05:28 UTC, individual-it commented on lib/Controller/ConfigController.php
> +		// if the admin config is not ok, we clear every existing user information
we clear it in any case

2022-05-13 05:38 UTC, individual-it requested changes

2022-05-13 05:38 UTC, individual-it commented on lib/Controller/ConfigController.php
> +		// if the admin config is not ok, we clear every existing user information
we clear it in any case

2022-05-13 05:38 UTC, individual-it commented on src/components/AdminSettings.vue
> +					+ ' After saving, every connected users must need to re-connect to the Openproject instance.'
```suggestion
					+ ' After saving, every connected user will have to re-connect to the OpenProject instance.'
```

2022-05-13 05:38 UTC, individual-it commented on src/components/AdminSettings.vue
> +					'Are you sure you want to update the admin settings?'
```suggestion
					'Are you sure you want to update the Oauth settings for OpenProject?'
```

2022-05-13 05:38 UTC, individual-it commented on tests/jest/components/AdminSettings.spec.js
> +			it('should show the save button', async () => {
```suggestion
			it('should show the update button', async () => {
```

2022-05-13 05:38 UTC, individual-it commented on tests/jest/components/AdminSettings.spec.js
> +				expect(wrapper.find(selectors.updateConfigButton).exists()).toBeFalsy()
I think this should be true

2022-05-13 05:38 UTC, individual-it commented on tests/jest/components/AdminSettings.spec.js
> +		describe('when the admin config status is not ok beforehand', () => {
```suggestion
		describe('admin config is not complete', () => {
```

2022-05-13 05:38 UTC, individual-it commented on tests/jest/components/AdminSettings.spec.js
> +		describe('when the admin config status is ok beforehand', () => {
```suggestion
		describe('admin config is complete', () => {
```

2022-05-13 05:38 UTC, individual-it commented on tests/jest/components/AdminSettings.spec.js
> +				expect(wrapper.find(selectors.saveConfigButton).exists()).toBeFalsy()
shouldn't that be true?

2022-05-13 05:38 UTC, individual-it commented on tests/lib/Controller/ConfigControllerTest.php
> +		$manager = \OC::$server->getUserManager();
```suggestion
		$userManager = \OC::$server->getUserManager();
```

2022-05-13 06:01 UTC, individual-it commented on tests/lib/Controller/ConfigControllerTest.php
> +		$this->assertSame(1, $count, 'Expected to have only 1 user in the dB before this test');
why should we fail tests if there are more then one user before?

2022-05-16 06:25 UTC, kiranparajuli589 commented on tests/lib/Controller/ConfigControllerTest.php
> +		$this->assertSame(1, $count, 'Expected to have only 1 user in the dB before this test');
I've to mock the `deleteUserValue` fn for the number of fn calls and consecutive args to verify cleanup is done for every user. The consecutive args `withConsecutive` can't be fed calculated data, so I have to have only two to match with the CI. One will be an admin and another will be the test-created user.

2022-05-16 06:26 UTC, kiranparajuli589 commented on tests/jest/components/AdminSettings.spec.js
> +			it('should show the save button', async () => {
when the admin config is incomplete, it shows the save btn without the confirm dialog. isn't that how it should behave?

2022-05-16 06:27 UTC, kiranparajuli589 commented on tests/jest/components/AdminSettings.spec.js
> +				expect(wrapper.find(selectors.updateConfigButton).exists()).toBeFalsy()
if the admin config is incomplete, only the save btn is displayed

2022-05-16 06:28 UTC, kiranparajuli589 commented on tests/jest/components/AdminSettings.spec.js
> +				expect(wrapper.find(selectors.saveConfigButton).exists()).toBeFalsy()
if the admin config is complete, then only update btn is displayed which then triggers the confirm dialog. isn't this how it should be?

2022-05-16 06:29 UTC, kiranparajuli589 commented on tests/lib/Controller/ConfigControllerTest.php
> +		$this->assertSame(1, $count, 'Expected to have only 1 user in the dB before this test');
if we can provide the args like this then the check wouldn't have been required. can we do it like so?
```
->withConsecutive(listOfConsecutiveArgs)
```

2022-05-16 08:57 UTC, individual-it requested changes

2022-05-16 08:57 UTC, individual-it commented on src/components/AdminSettings.vue
> +				},
replace with suggestion of @wielinde in https://community.openproject.org/projects/nextcloud-integration/work_packages/42273/activity#activity-4

2022-05-16 09:40 UTC, individual-it approved these changes

2022-05-16 11:31 UTC, individual-it commented
this should also fix https://community.openproject.org/projects/nextcloud-integration/work_packages/42272 or?

2022-05-16 11:50 UTC, kiranparajuli589 commented
> this should also fix https://community.openproject.org/projects/nextcloud-integration/work_packages/42272 or?

yes it should

2022-05-16 11:50 UTC, merged