Redesign admin form
nextcloud/integration_openproject pull request #124
Opened 2022-06-01 11:38 UTC by kiranparajuli589

Signed-off-by: Kiran Parajuli <kiranparajuli589@gmail.com>

2022-06-08 07:25 UTC, kiranparajuli589 commented
Todo after this PR:
- use separate variables to remember the admin settings so that if we cancel the edit form, we can set them back to as it was before edit.

2022-06-08 10:45 UTC, individual-it commented on lib/Controller/ConfigController.php
> +//		}
Leave the current behavior for this PR, we can implement the desired behavior in a separate PR

2022-06-08 11:11 UTC, kiranparajuli589 commented on lib/Controller/ConfigController.php
> +//		}
reverted back to as it was. but still needs the readjustments.

2022-06-09 03:52 UTC, individual-it commented on src/components/admin/TextInput.vue
>  		},
why not set a default value here?

2022-06-10 07:13 UTC, kiranparajuli589 commented
A new work package is created [here](https://community.openproject.org/projects/nextcloud-integration/work_packages/42862) for these remaining todos. @individual-it @SwikritiT we can merge this one to move forward.

2022-06-10 10:26 UTC, SwikritiT reviewed
LGTM

2022-06-10 11:05 UTC, individual-it requested changes
great work!
just some minor comments


the second step does not need the `Copy Values` buttons
![image](https://user-images.githubusercontent.com/2425577/173050102-7b5bbbc4-8099-4c34-bba6-e56cc329a603.png)

2022-06-10 11:05 UTC, individual-it commented on src/components/AdminSettings.vue
> +			return this.state.oauth_instance_url + '/admin/settings/storages'
if the main OpenProject host has a trailing `/` this link will have two `//` that might give sometimes problems

2022-06-10 11:44 UTC, kiranparajuli589 commented on src/components/AdminSettings.vue
> +				title="OpenProject Server"
they are translated inside the component `FormHeading`

2022-06-10 11:45 UTC, kiranparajuli589 commented on src/components/AdminSettings.vue
> +				+ this.translate('as an Administrator and start the setup and copy the values here.')
used single translate

2022-06-10 11:45 UTC, kiranparajuli589 commented on src/components/AdminSettings.vue
> +			return this.state.oauth_instance_url + '/admin/settings/storages'
fixed

2022-06-13 03:33 UTC, individual-it commented on src/components/AdminSettings.vue
> +					text="Yes, I have copied these values"
need translation

2022-06-13 03:40 UTC, individual-it approved these changes
I think some snapshots in the tests need to be recreated, rest looks good to me

2022-06-13 04:26 UTC, merged