[OP#41900] Improve developers documentation
nextcloud/integration_openproject pull request #132
Opened 2022-06-07 08:58 UTC by SwikritiT

## Description
This PR updates the developer's documentation by removing all the unnecessary configurations and keeps the description up-to-date with the system's current functionality.
Also adds the following missing configurations: 
 - [x] storage module Feature Flag 
 - [x] APP_DIR env variable

## Related Workpackage
OP#41900: https://community.openproject.org/projects/nextcloud-integration/work_packages/41900/g

2022-06-09 03:50 UTC, individual-it commented on README.md
> +### Setting up storages
I believe this documentation should be all in OpenProject, here we only want to have documentation about how to start development of the nextcloud app

2022-06-20 08:44 UTC, phil-davis commented on README.md
> +a search provider for work packages, through which you can search, link, and unlink work packages to a particular file.
```suggestion
OpenProject integration provides a dashboard widget for displaying notifications of changes in active work packages,
and a search provider for work packages, through which you can search, link, and unlink work packages to a particular file.
```

2022-06-20 08:44 UTC, phil-davis commented on README.md
> +**Note:** If you've cloned integration app anywhere other that the default `./../../custom_apps`, provide its path in `APP_DIR` environment variable
```suggestion
**Note:** If you've cloned the integration app anywhere other than the default `./../../custom_apps`, provide its path in the `APP_DIR` environment variable
```

2022-06-20 08:44 UTC, phil-davis commented on README.md
> +> **Note:** Inorder to use the search bar for searching work packages you need to set-up file storages in openProject side for your particular nextcloud instance. To do so you can follow this [docume
```suggestion
> **Note:** In order to use the search bar for searching work packages you need to set-up file storages in the openProject side for your particular nextcloud instance. To do so you can follow this [documentation](https://google.com)
```

2022-06-20 08:50 UTC, kiranparajuli589 commented on README.md
> +> **Note:** Inorder to use the search bar for searching work packages you need to set-up file storages in openProject side for your particular nextcloud instance. To do so you can follow this [docume
```suggestion
> **Note:** In order to use the search bar for searching work packages you need to set up file storage on the OpenProject side for your particular Nextcloud instance. To do so you can follow this [documentation](https://google.com)
```

2022-06-20 08:50 UTC, kiranparajuli589 commented on README.md
> +After this, you should be able to access the nextcloud server at [http://localhost](http://localhost).
```suggestion
After this, you should be able to access the Nextcloud server at [http://localhost](http://localhost).
```

2022-06-20 09:03 UTC, SwikritiT commented on README.md
> +> **Note:** Inorder to use the search bar for searching work packages you need to set-up file storages in openProject side for your particular nextcloud instance. To do so you can follow this [docume
Yes for now there's no documentation for how to set it up from the OpenProject side, we will have to link it once there's a proper docs

2022-06-21 04:17 UTC, individual-it requested changes

2022-06-21 04:17 UTC, individual-it commented on README.md
> +a search provider for work packages, through which you can search, link, and unlink work packages to a particular file.
I would put the linking of WP first, because that became our most important feature
I think the search provider means the searching through the global search of NC
the dashboard does not check for changes in WP, but reads the OP notifications
also we can display the count of OP notifications in NC notification
```suggestion
OpenProject integration provides the possibility to link OpenProject work-packages to a file in NextCloud, a dashboard widget for displaying OpenProject notifications, a search provider to search for work packages through the unified search and can display the count of OpenProject notifications as NextCloud notification.
```

2022-06-21 04:17 UTC, individual-it commented on README.md
> +> **Note:** In order to use the search bar for searching work packages you need to set up file storages on the OpenProject side for your particular Nextcloud instance. To do so you can follow this [d
maybe that could go to the top, because it will be needed also if people want just to run the app and not develop it

2022-06-21 05:57 UTC, individual-it approved these changes
LGTM

2022-06-21 06:03 UTC, phil-davis approved these changes

2022-06-21 10:49 UTC, kiranparajuli589 approved these changes

2022-06-22 05:41 UTC, merged