Add readonly attributes for the Nextcloud OAuth values form input fields
nextcloud/integration_openproject pull request #140
Opened 2022-06-13 11:45 UTC by kiranparajuli589

## Description
[OP#42862] As the 3rd form (Nextcloud OAuth values form) is not involved in edit, the input fields are made `readonly`

### Related
Part of https://community.openproject.org/projects/nextcloud-integration/work_packages/42862

Signed-off-by: Kiran Parajuli <kiranparajuli589@gmail.com>

2022-06-13 12:22 UTC, SwikritiT requested changes
This is not working for me. 

https://user-images.githubusercontent.com/41103328/173352377-0cf30247-4d75-4a88-8e1a-02f509df11a6.mp4

2022-06-14 05:02 UTC, kiranparajuli589 commented
> This is not working for me.
> 
>  simplescreenrecorder-2022-06-13_17.57.20.mp4

Hmm, the PR is actually for setting the 3rd form inputs as readonly. But, the problem in your screen recording is something different. fixed here https://github.com/nextcloud/integration_openproject/pull/142

2022-06-15 02:40 UTC, individual-it approved these changes

2022-06-15 07:27 UTC, SwikritiT approved these changes
LGTM

2022-06-15 07:28 UTC, merged