Change redirect uri only when op url changes
nextcloud/integration_openproject pull request #143
Opened 2022-06-14 05:40 UTC by SwikritiT

Signed-off-by: Swikriti Tripathi <swikriti808@gmail.com>

2022-06-14 09:11 UTC, kiranparajuli589 reviewed
lgtm :+1: works good on my machine too.

2022-06-15 02:46 UTC, individual-it requested changes
just small comments about variable naming

2022-06-15 02:46 UTC, individual-it commented on lib/Controller/ConfigController.php
> +		$opUrl = $this->config->getAppValue(Application::APP_ID, 'oauth_instance_url', '');
```suggestion
		$oldOpenProjectOauthUrl = $this->config->getAppValue(Application::APP_ID, 'oauth_instance_url', '');
```

2022-06-15 02:46 UTC, individual-it commented on lib/Controller/ConfigController.php
> +			$this->oauthService->setClientRedirectUri($id, $values['oauth_instance_url']);
```suggestion
			$this->oauthService->setClientRedirectUri((int) $oauthClientInternalId, $values['oauth_instance_url']);
```

this would avoid the very generic variable name `$id`

2022-06-15 02:46 UTC, individual-it commented on lib/Service/OauthService.php
> +			$redirectUri = rtrim($opUrl, '/') .'/oauth_clients/'.$clientId.'/callback';
do we need extra unit tests to check this small part of the logic?

2022-06-15 07:17 UTC, SwikritiT commented on lib/Service/OauthService.php
> +			$redirectUri = rtrim($opUrl, '/') .'/oauth_clients/'.$clientId.'/callback';
currently, we don't have any tests for `OauthService` as there were some problems while trying to mock the `Client`. I have created a work package here https://community.openproject.org/projects/nextcloud-integration/work_packages/42896/activity for future

2022-06-15 08:01 UTC, individual-it approved these changes

2022-06-15 08:01 UTC, merged