[OP#42909] Use material icon
nextcloud/integration_openproject pull request #155
Opened 2022-06-22 12:06 UTC by SwikritiT

## Description
The icon classes used in the Nextcloud app will be dropped in the future. So, this PR makes use of vue material icon https://github.com/robcresswell/vue-material-design-icons

## Related Workpackage
OP#42909 https://community.openproject.org/work_packages/42909/activity

2022-06-27 03:59 UTC, kiranparajuli589 commented on src/components/tab/EmptyContent.vue
> +				<LinkOffIcon v-else :size="60" />
imo, we should be using `isAdminConfigOk` check here

2022-06-27 04:45 UTC, SwikritiT commented on src/components/tab/EmptyContent.vue
> +				<LinkOffIcon v-else :size="60" />
done in the latest commit!

2022-06-27 06:37 UTC, kiranparajuli589 commented on src/views/Dashboard.vue
> +					<CheckBoldIcon v-if="state === 'ok'" :size="70" />
```suggestion
					<CheckBoldIcon v-if="state === STATE.OK" :size="70" />
```
please use the state variables from the STATE obj

2022-06-27 10:53 UTC, eneiluj requested changes
I pushed a couple of commits to fix stuff in the `.complete` element of FormHeading:
* use the color-success variable 
* fix the icon alignment

In general, colors provided by Nextcloud global CSS are preferred for green/red/orange referring to success/error/warning.

Other than that, looks good to me. I fully reviewed the code but didn't try everything.

A few inline comments.

2022-06-27 10:53 UTC, eneiluj commented on src/components/PersonalSettings.vue
> +	padding-right: 8px;
```suggestion
	padding-right: 8px;
	color: var(--color-success);
```

2022-06-27 10:53 UTC, eneiluj commented on src/components/PersonalSettings.vue
> +					<CheckIcon class="openproject-connected-checkmark" :size="20" fill-color="#007500" />
You can set a green color with the "color" css attribute on material icons. There is a `--color-success` CSS variable provided by Nextcloud.

```suggestion
					<CheckIcon class="openproject-connected-checkmark" :size="20" />
```

2022-06-28 04:25 UTC, SwikritiT commented on src/views/Dashboard.vue
> +					<CheckBoldIcon v-if="state === 'ok'" :size="70" />
Done in latest push!

2022-06-28 04:25 UTC, SwikritiT commented on src/components/PersonalSettings.vue
> +					<CheckIcon class="openproject-connected-checkmark" :size="20" fill-color="#007500" />
Done in the latest commit. Thank you for the suggestion!

2022-06-28 07:57 UTC, merged