run tests with NC22
nextcloud/integration_openproject pull request #184
Opened 2022-07-26 09:07 UTC by individual-it

the app claims to have NC 22 as min version, so lets test it

2022-07-26 09:15 UTC, eneiluj requested changes

2022-07-26 09:15 UTC, eneiluj commented on .github/workflows/ci.yml
> +        nextcloudVersion: [ v22.2.9, v23.0.4, v24.0.0, master ]
```suggestion
        nextcloudVersion: [ stable22, stable23, stable24, master ]
```
It will save you some effort to adjust to latest minor releases.

2022-07-26 10:57 UTC, individual-it commented on .github/workflows/ci.yml
> +        nextcloudVersion: [ v22.2.9, v23.0.4, v24.0.0, master ]
thanks, adjusted

2022-07-27 09:13 UTC, kiranparajuli589 approved these changes

2022-07-28 04:01 UTC, merged