[#43670] add OpenProject to the files action menu in NC
nextcloud/integration_openproject pull request #202
Opened 2022-08-16 11:57 UTC by kiranparajuli589

https://community.openproject.org/work_packages/43670
Signed-off-by: Kiran Parajuli <kiranparajuli589@gmail.com>

2022-08-18 04:18 UTC, individual-it requested changes
works fine, just some small comments

2022-08-18 04:18 UTC, individual-it commented on lib/AppInfo/Application.php
> +		// TODO this creates some deprecation warnings!
a TODO in the code will not be worked on and will be forgotten.
Ether fix this now or create a work-package

2022-08-18 04:18 UTC, individual-it commented on src/fileActions.js
> +	}
```suggestion
	},
```
to make the linter happy

2022-08-18 06:16 UTC, kiranparajuli589 commented on lib/AppInfo/Application.php
> +		// TODO this creates some deprecation warnings!
sorry, the comment was not relevant. removed it.

2022-08-19 11:07 UTC, individual-it approved these changes

2022-08-19 11:07 UTC, merged