Updated app description
nextcloud/integration_openproject pull request #209
Opened 2022-08-19 12:57 UTC by psatyal

Updated the copy of the description to make it clearer, easier to read and more to-the-point

Signed-off-by: Parimal Satyal <88370597+psatyal@users.noreply.github.com> (OpenProject)

2022-08-22 04:17 UTC, individual-it requested changes

2022-08-22 04:17 UTC, individual-it commented on appinfo/info.xml
> +* Keep an eye on updates to linked work packages via the dashboard
This is not completely correct, the dashboard shows all OP notifications, not only updates of linked WP

2022-08-22 04:17 UTC, individual-it commented on appinfo/info.xml
> +For more information on how to set up and use the OpenProject application, please refer to [integration setup guide](https://www.openproject.org/docs/system-admin-guide/integrations/nextcloud/) for a
I'm not sure if the links will be rendered correctly in the app-store. @eneiluj do you know.
But maybe it's enough that the links are anyway shown in the resources area
![image](https://user-images.githubusercontent.com/2425577/185838573-bf008794-8180-404c-96b1-a68ee66a2c9a.png)

2022-08-22 09:38 UTC, psatyal commented on appinfo/info.xml
> +* Keep an eye on updates to linked work packages via the dashboard
Important distinction, thanks. Updated the text.

2022-08-22 09:41 UTC, psatyal reviewed
Made changes based on @individual-it's comments.

2022-08-22 09:54 UTC, individual-it approved these changes

2022-08-23 04:27 UTC, individual-it commented
CI fails because code-coverage does not work correctly when the PR comes from an other repo. But in this case that does not matter at all

2022-08-23 04:28 UTC, merged