[OP#43669] allow the administrator to define defaults for user settings
nextcloud/integration_openproject pull request #223
Opened 2022-08-25 05:46 UTC by kiranparajuli589

- Enhance html/css for the personal settings section
- Use component for the checkbox
- Use component for the checkbox
- Add raw html for the defaults
- backend started
- ui integration with the backend for the settings update

2022-08-30 06:41 UTC, individual-it commented on src/components/AdminSettings.vue
> +		init() {
why moving that code to an own function?

2022-08-30 07:05 UTC, kiranparajuli589 commented on src/components/AdminSettings.vue
> +		init() {
imo, it's better to call an fn from the hooks.

2022-09-22 07:00 UTC, SwikritiT commented
I have updated the description with the current implementation video

2022-09-22 09:03 UTC, eneiluj requested changes

2022-09-22 09:03 UTC, eneiluj commented on src/components/AdminSettings.vue
> +			this.state.default_enable_unified_search = null
We could set it back to false to keep it as a boolean.

2022-09-22 09:03 UTC, eneiluj commented on src/components/AdminSettings.vue
> -				console.debug(error)
As you want but I think it's good to have a console.error there.

2022-09-23 04:53 UTC, individual-it requested changes
this works nicely to show the correct settings in the admin and personal settings page
BUT: where we use the settings for real to trigger the actions only the usersettings are read, not the defaults
e.g https://github.com/nextcloud/integration_openproject/blob/caa0b817395c067dd1e53e53016ff6df3f3f779c/lib/Service/OpenProjectAPIService.php#L137
https://github.com/nextcloud/integration_openproject/blob/86987d0632d38fef9061e283d03f05598b14ab04/lib/Search/OpenProjectSearchProvider.php#L130
https://github.com/nextcloud/integration_openproject/blob/bccb09abd9326c1988f253862a28621a33810465/lib/AppInfo/Application.php#L86

2022-09-23 06:31 UTC, SwikritiT commented
> this works nicely to show the correct settings in the admin and personal settings page BUT: where we use the settings for real to trigger the actions only the usersettings are read, not the defaults e.g
> 
> https://github.com/nextcloud/integration_openproject/blob/caa0b817395c067dd1e53e53016ff6df3f3f779c/lib/Service/OpenProjectAPIService.php#L137
> 
> 
> https://github.com/nextcloud/integration_openproject/blob/86987d0632d38fef9061e283d03f05598b14ab04/lib/Search/OpenProjectSearchProvider.php#L130
> 
> 
> https://github.com/nextcloud/integration_openproject/blob/bccb09abd9326c1988f253862a28621a33810465/lib/AppInfo/Application.php#L86

Can you try again? It should work now.

2022-09-23 07:44 UTC, individual-it approved these changes
looks good, please adjust the tests

2022-09-23 08:57 UTC, SwikritiT commented
@eneiluj I've addressed your reviews can you take a look again?

2022-09-26 03:45 UTC, merged