Fix trashManager not found
nextcloud/integration_openproject pull request #228
Opened 2022-09-07 08:41 UTC by eneiluj

Only use the trash manager if the files_trashbin app is enabled for the user.
Catch any exception when getting the trashManager, just in case.

2022-09-07 09:04 UTC, eneiluj commented
The phpstan error can be ignored as it is the way to go :grin:.

2022-09-12 04:29 UTC, individual-it requested changes

2022-09-12 04:29 UTC, individual-it commented on lib/Controller/FilesController.php
> +				$trashManager = Server::get(\OCA\Files_Trashbin\Trash\ITrashManager::class);
this only works for NC 25, see https://github.com/nextcloud/server/commit/f945c0cbc6aef461fabf17cea42440ad9b6fea09#diff-e3c727c87edec3701539efc3b38c11374baf33362c0a4038f004f4b7ccbe71b7R39

That is why phpstan complains with older versions.

2022-09-13 10:30 UTC, eneiluj commented on lib/Controller/FilesController.php
> +				$trashManager = Server::get(\OCA\Files_Trashbin\Trash\ITrashManager::class);
Alright, fixed. Could you adjust the tests?

2022-09-13 11:41 UTC, individual-it commented
strangely the unit tests work fine when run separately but when ran all at once `getTrashNodeById`  throw strange exceptions  `"Backends provided no user object for testUser"`
need to investigate more

2022-09-14 08:33 UTC, individual-it commented
tests are fixed and some new ones added.
there are two cases
1. a file got deleted, then the trashbin app got disabled
    in that case the file actually is in the trashbin and has a mount, but cannot be accessed, the return code is 403
2. a file got deleted after the trashbin app got disabled
    in that case the file is really gone, the return code is 404

2022-09-14 08:35 UTC, individual-it reviewed
I think we can merge that
@eneiluj are you happy with my refactoring?
@wielinde should that be backported to 2.0 ?

2022-09-14 12:47 UTC, wielinde commented
@individual-it Yes, I think this PR is a typical for a patch level release

2022-09-15 09:40 UTC, eneiluj commented
@individual-it Yep, all good.

2022-09-15 09:41 UTC, individual-it approved these changes

2022-09-21 04:20 UTC, merged

2022-09-22 08:57 UTC, individual-it commented
backport in  #232