[OP-40679]Add search-bar to sidebar tab
nextcloud/integration_openproject pull request #23
Opened 2022-01-27 03:43 UTC by SwikritiT

2022-02-03 04:25 UTC, individual-it requested changes
please also add unit tests for the new code

2022-02-03 04:25 UTC, individual-it commented on lib/Controller/OpenProjectAPIController.php
> +			$this->openprojectUrl, $this->accessToken, $this->tokenType, $this->refreshToken, $this->clientID, $this->clientSecret, $this->userId, $searchQuery
too long line

2022-02-03 04:25 UTC, individual-it commented on lib/Controller/OpenProjectAPIController.php
> +	 * @throws PreConditionNotMetException
where can that exception come from?
maybe better to catch it and return an appropriate HTTP Error code, because the return of this function is given back to the browser

2022-02-03 04:25 UTC, individual-it commented on lib/Controller/OpenProjectAPIController.php
> +	 * @throws Exception
same here, I would suggest not to throw exceptions in functions that are called by a route

2022-02-03 04:25 UTC, individual-it commented on lib/Controller/OpenProjectAPIController.php
> +			$this->openprojectUrl, $this->accessToken, $this->tokenType, $this->refreshToken, $this->clientID, $this->clientSecret, $this->userId, $id
long line

2022-02-03 04:25 UTC, individual-it commented on lib/Controller/OpenProjectAPIController.php
> +			$this->openprojectUrl, $this->accessToken, $this->tokenType, $this->refreshToken, $this->clientID, $this->clientSecret, $this->userId, $id
long line

2022-02-03 04:25 UTC, individual-it commented on lib/Controller/OpenProjectAPIController.php
> +	 * @throws Exception
let's catch that too

2022-02-03 04:25 UTC, individual-it commented on lib/Service/OpenProjectAPIService.php
> +	{
formatting suggestion

```suggestion
	public function getOpenProjectWorkPackageStatus(
		string $url,
		string $accessToken,
		string $authType,
		string $refreshToken,
		string $clientID,
		string $clientSecret,
		string $userId,
		string $statusId
	): array
	{
```

also let's not use `$authType` in new functions, it will be deleted anyway soon. Where-ever you need to pass it give `oauth`

2022-02-03 04:25 UTC, individual-it commented on src/components/tab/SearchInput.vue
> +					console.debug('error')
why not setting the `state` here also to `error`?

2022-02-03 04:25 UTC, individual-it commented on src/components/tab/SearchInput.vue
> +			const url = generateUrl('/apps/integration_openproject/avatar?') + encodeURIComponent('userId') + '=' + userId + '&' + encodeURIComponent('userName') + '=' + userName
long line

2022-02-03 04:25 UTC, individual-it commented on tests/acceptance/features/searchBar.feature
> +    Then the work package "This is a work package" should be listed on the webUI
I think we can make two scenarios out of that

2022-02-03 04:25 UTC, individual-it commented on tests/acceptance/features/searchBar.feature
> +    And the work package "This is a work package" is displayed in the drop down menu on the webUI
ether that is a `Then` step or can be removed

2022-02-03 04:25 UTC, individual-it commented on tests/acceptance/features/searchBar.feature
> +  - can easily locate and navigate to connected information in OpenProject
The search-bar is not so much for viewing the linked workpackages but to link them

2022-02-03 04:28 UTC, kiranparajuli589 commented on lib/Controller/OpenProjectAPIController.php
> +
seems not necessary!

2022-02-03 04:28 UTC, kiranparajuli589 commented on src/components/tab/SearchInput.vue
> +				{{ "+ New work package in OpenProject" }}
add translations

2022-02-03 04:28 UTC, kiranparajuli589 commented on src/components/tab/SearchInput.vue
> +				this.searchResults.length = 0
```suggestion
				this.searchResults = []
```

2022-02-03 04:28 UTC, kiranparajuli589 commented on src/components/tab/SearchInput.vue
> +				if (response.status === 400) {
I think 401 should be for unauthorized.

2022-02-03 04:28 UTC, kiranparajuli589 commented on src/components/tab/SearchInput.vue
> +					? workPackages[i]._links.status.href.replace(/.*\//, '')
you can make a helper function for this:
```suggestion
					? this.replacesForMe(workPackages[i]._links.status.href)
```
and implement the function inside `methods` with a nice name

2022-02-09 14:25 UTC, individual-it commented
code coverage report seems not to work if PR comes from a fork

2022-02-10 06:10 UTC, kiranparajuli589 commented on src/components/tab/SearchInput.vue
> +				}
can we use a function to reduce some duplications? seem like this is reused after the server request.

2022-02-10 06:10 UTC, kiranparajuli589 commented on src/components/tab/SearchInput.vue
> +	font-size: 14px;
use `rem` rather `px`
https://stackoverflow.com/questions/11799236/should-i-use-px-or-rem-value-units-in-my-css

2022-02-10 06:10 UTC, kiranparajuli589 commented on tests/acceptance/features/searchBar.feature
> +   when the user links the work package "This is a work package" using the webUI
```suggestion
   When the user links the work package "This is a work package" using the webUI
```

2022-02-10 06:10 UTC, kiranparajuli589 commented on tests/jest/components/tab/SearchInput.spec.js
> +			let errorSelector = wrapper.find('.title')
```suggestion
			let errorSelector = wrapper.find(selectors.title)
```
use variables for the selectors. look for the other occurrences too.

2022-02-10 06:10 UTC, kiranparajuli589 commented on tests/jest/components/tab/SearchInput.spec.js
> +})
you can add more test for  `should not show search results for less than 3 chars input`

2022-02-10 06:16 UTC, kiranparajuli589 commented on tests/jest/components/tab/SearchInput.spec.js
> +			expect(wrapper).toMatchSnapshot()
```suggestion
			expect(searchList).toMatchSnapshot()
```

2022-02-17 06:38 UTC, closed without merging