feature/44747 revoke client tokens received from openproject
nextcloud/integration_openproject pull request #270
Opened 2022-11-09 09:24 UTC by kiranparajuli589

- Setup some fns
- Feature lagvag done

2022-11-10 07:34 UTC, individual-it requested changes

2022-11-10 07:34 UTC, individual-it commented on lib/Controller/ConfigController.php
> +		if ($opUrl && $opOAuthClientID && $opOAuthClientSecret && $accessToken) {
what is that expression is not true, then the code will silently do nothing. I think its better to throw an exception

2022-11-10 07:34 UTC, individual-it commented on lib/Service/OpenProjectAPIService.php
> +	public function revokeUserOAuthToken(
why not integrate that function directly in `revokeUserToken`?
I think the most other functions in this file are providing some REST API, but this one not

2022-11-10 07:34 UTC, individual-it commented on lib/Controller/ConfigController.php
> +			($oldClientSecret && $oldClientId && $values['client_id'] === null && $values['client_secret'] === null)
is that a bug in the current code? On reset we don't clean the user info?

2022-11-10 08:42 UTC, kiranparajuli589 commented on lib/Service/OpenProjectAPIService.php
> +	public function revokeUserOAuthToken(
This func. sends a `POST` request for the revoke action to the OP instance. So I had put it in the `OpenProjectAPIService` section. We do NC things in the `ConfigController`.  Should it be moved? I can also call _revoke_ directly from the `setAdminConfig` fn.

2022-11-10 08:53 UTC, kiranparajuli589 commented on lib/Controller/ConfigController.php
> +			($oldClientSecret && $oldClientId && $values['client_id'] === null && $values['client_secret'] === null)
maybe yes :)

2022-11-10 08:53 UTC, kiranparajuli589 commented on lib/Controller/ConfigController.php
> +		if ($opUrl && $opOAuthClientID && $opOAuthClientSecret && $accessToken) {
there can be case where user might not have the `accessToken` set. I've modified the code. Please review.

2022-11-15 09:24 UTC, individual-it commented on lib/Service/OpenProjectAPIService.php
> +	public function revokeUserOAuthToken(
I think I would put it into `revokeUserToken`

2022-11-22 11:11 UTC, individual-it requested changes

2022-11-22 11:11 UTC, individual-it commented on lib/Service/OpenProjectAPIService.php
> +			throw new OpenprojectErrorException($body);
```suggestion
			throw new OpenprojectErrorException('could not revoke token in OpenProject. response body: "' .$body . '"');
```
what will happen in the UI in that case? Will the user see some technical error?
Maybe better to have some nice error message to the user and a detailed log entry

2022-12-06 09:17 UTC, SwikritiT commented
@kiranparajuli589 Seems like the CI error is because of the passing variable by reference here https://github.com/nextcloud/integration_openproject/pull/270/commits/da3cc2af9fac34c318fbe67580990870139b8197 
If I pass them as value CI is green https://github.com/nextcloud/integration_openproject/actions/runs/3628009178, but the feature won't work as intended?

2022-12-07 05:39 UTC, individual-it requested changes

2022-12-07 05:39 UTC, individual-it commented on lib/Service/OpenProjectAPIService.php
> +		}
if the OP server cannot be reached the user does not see any error message and the log-file only shows an exception like 
```
  "reqId": "w1EeF0qP7dEfEnJSosrG",
  "level": 3,
  "time": "2022-12-07T05:22:14+00:00",
  "remoteAddr": "127.0.0.1",
  "user": "admin",
  "app": "index",
  "method": "PUT",
  "url": "/nextcloud-server/index.php/apps/integration_openproject/admin-config",
  "message": "cURL error 7: Failed to connect to host.docker.internal port 3000 after 0 ms: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://host.docker.internal:3000/oauth/revoke?token=sLlQ4LHmS_jC1IW8SS8M-1edpOB72m0-AvtPb9sPDJE",
  "userAgent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:107.0) Gecko/20100101 Firefox/107.0",
  "version": "24.0.7.1",
  "exception": {
    "Exception": "GuzzleHttp\\Exception\\ConnectException",
    "Message": "cURL error 7: Failed to connect to host.docker.internal port 3000 after 0 ms: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://host.docker.internal:3000/oauth/revoke?token=sLlQ4LHmS_jC1IW8SS8M-1edpOB72m0-AvtPb9sPDJE",
    "Code": 0,
    "Trace": [
      {
        "file": "/home/artur/www/nextcloud-server/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php",
        "line": 158,
        "function": "createRejection",
        "class": "GuzzleHttp\\Handler\\CurlFactory",
        "type": "::"
      },
      {
        "file": "/home/artur/www/nextcloud-server/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php",
```

I think it would be better to show a general message to the user like `OAuth Tokens in OpenProject could not be reset` and a good log message with more details like response code and body

2022-12-07 05:39 UTC, individual-it commented on lib/Controller/ConfigController.php
> +					throw new Exception('Missing required parameters.'
do we need to throw an exception here?
maybe better to show a message to the user and have a log entry

e.g. when the admin enters some wrong OP client id and secret at the first time setting up the app and then clicks on "Replace OpenProject OAuth values" only the message `Missing  required parameters.` is shown and the admin cannot replace the values

2022-12-07 08:54 UTC, kiranparajuli589 commented on lib/Controller/ConfigController.php
> +			($oldClientSecret && $oldClientId && $values['client_id'] === null && $values['client_secret'] === null)
for that case, revoke would not be possible. if we have the token present for the user, it will be cleared in the loop below. any more thing we should do here @individual-it ?

2022-12-07 09:06 UTC, kiranparajuli589 commented on lib/Service/OpenProjectAPIService.php
> +		}
should we clear the user info & admin config data, if the revoke fails?

2022-12-07 09:08 UTC, individual-it commented on lib/Service/OpenProjectAPIService.php
> +		}
I think yes

2022-12-07 09:09 UTC, individual-it commented on lib/Controller/ConfigController.php
> +			($oldClientSecret && $oldClientId && $values['client_id'] === null && $values['client_secret'] === null)
lets tell the user that revoking was not possible, but still reset

2022-12-07 09:31 UTC, kiranparajuli589 commented on lib/Service/OpenProjectAPIService.php
> +		}
upto now...the admin data is cleared at first, then in user for loop: revoke is done and then user data is cleaned up

2022-12-08 06:15 UTC, kiranparajuli589 commented
unit tests for UI and Pact tests for service API is yet to be added.

2022-12-08 06:33 UTC, individual-it requested changes

2022-12-08 06:40 UTC, kiranparajuli589 commented on lib/Controller/ConfigController.php
> +				$oldOpenProjectOauthUrl, $oldClientId, $oldClientSecret, &$oPOAuthTokenRevokeStatus
the value of `$oPOAuthTokenRevokeStatus` has to be changed inside the callback fn. which is only possible by using the reference. i am trying to see why this coverage is failing. suggestions?

2022-12-08 10:23 UTC, kiranparajuli589 commented on lib/Controller/ConfigController.php
> +				$oldOpenProjectOauthUrl, $oldClientId, $oldClientSecret, &$oPOAuthTokenRevokeStatus
done using the system variables

2022-12-08 10:23 UTC, kiranparajuli589 commented on lib/Controller/ConfigController.php
> +			'default_enable_notifications'
fixed

2022-12-09 08:08 UTC, individual-it requested changes
there are still problems:
1. with a full setup
2. try to change the OP client id & secret
=> the UI reloads and leaves the id & secrets empty :-1: 

1. reset everything
4. enter valid openproject URL
 => UI says the tokens have been revoked :-1: because there haven't been any tokens to revoke
 => the UI does not go to the next part :-1:

2022-12-09 10:52 UTC, SwikritiT commented
> there are still problems:
> 
> 1. with a full setup
> 2. try to change the OP client id & secret
>    => the UI reloads and leaves the id & secrets empty -1
> 3. reset everything
> 4. enter valid openproject URL
>    => UI says the tokens have been revoked -1 because there haven't been any tokens to revoke
>    => the UI does not go to the next part -1

I cannot reproduce this now, @kiranparajuli589 but some of the php tests are still failing

2022-12-09 11:15 UTC, kiranparajuli589 commented
@SwikritiT I've fixed the unit tests too. please give it a look again.

2022-12-09 11:33 UTC, SwikritiT commented
I'm having this problem now
I cannot connect through the dashboard of the normal user or rather I can connect but it still shows the connect button
![Screenshot from 2022-12-09 17-15-42](https://user-images.githubusercontent.com/41103328/206693471-1b8b3616-4a1d-404b-9aa4-a1a86979c63e.png)


![Screenshot from 2022-12-09 17-15-54](https://user-images.githubusercontent.com/41103328/206693504-9c6d9042-a618-453f-b6a7-1aaf048c2e44.png)

Not reproducible for admin user though

2022-12-12 06:06 UTC, kiranparajuli589 commented on lib/Controller/ConfigController.php
> +		if (
done

2022-12-12 06:35 UTC, kiranparajuli589 commented
@SwikritiT I have tried and it works fine with stable 24 and 25. Can u please check in with NC master branch.

2022-12-12 09:20 UTC, SwikritiT commented
looks good

2022-12-12 10:10 UTC, individual-it approved these changes

2022-12-12 10:10 UTC, merged