Endpoint for setting whole integration
nextcloud/integration_openproject pull request #280
Opened 2022-11-28 07:31 UTC by SagarGi

2022-11-29 04:22 UTC, kiranparajuli589 commented on lib/Controller/ConfigController.php
> +		}
else some error need to be thrown? user also should be shown some message about the failure.

2022-11-30 09:27 UTC, kiranparajuli589 commented on lib/Controller/ConfigController.php
> +		}
on the second thought,,,,server log may be useful but this is not yet used by the UI. ur call.

2022-12-07 08:40 UTC, SwikritiT reviewed
maybe we can add some PHP unit tests as well?

2022-12-07 09:31 UTC, SwikritiT commented
sending the request with following data 
```json
{
		"values":
			{
				"client_id":null,
				"client_secret":null,
				"default_enable_navigation":false,
				"default_enable_unified_search":false,
				"oauth_instance_url":null
			}
}
```
GIves me `500` maybe it should support `null` as well, while resetting we sent null value

2022-12-07 09:41 UTC, SwikritiT commented
In another case while sending `empty`, `client-id`, and `client_secret` it sends me `200`  and the UI looks like this
![Screenshot from 2022-12-07 15-22-55](https://user-images.githubusercontent.com/41103328/206143773-ade05346-91ce-4e5e-ae9f-694fd050f1fe.png)


Maybe a check for empty string?

2022-12-07 10:04 UTC, kiranparajuli589 commented on lib/Controller/ConfigController.php
> +					'response_status_code' => Http::STATUS_BAD_REQUEST
```suggestion
					'type' => 'error',
					'result' => $this->l->t('Invalid key'),
					'status_code' => Http::STATUS_BAD_REQUEST
```

2022-12-07 10:04 UTC, kiranparajuli589 commented on lib/Controller/ConfigController.php
> +	private function setUpOpenProjectAdminSetUp(array $values): array {
```suggestion
	private function setUpOpenProjectAdminConfig(array $values): array {
```

2022-12-08 06:46 UTC, individual-it requested changes

2022-12-08 06:46 UTC, individual-it commented on lib/Controller/ConfigController.php
> +					"status" => "Missing Open Project client info or Invalid Key"
```suggestion
					"status" => "Missing OpenProject client information or invalid key"
```

2022-12-08 06:46 UTC, individual-it commented on lib/Controller/ConfigController.php
> +			$values[$keyName] = (string)$values[$keyName];
```suggestion
			if ($keyName == "default_enable_navigation" || $keyName == "default_enable_unified_search") {
				$values[$keyName] = (bool)$values[$keyName];
			} else {
			        $values[$keyName] = (string)$values[$keyName];
		        }
```
otherwise it will be cast to bool and then to string

2022-12-08 06:46 UTC, individual-it commented on lib/Controller/ConfigController.php
> +	private function createAndGetClientInformationForNextCloud(): array {
```suggestion
	private function recreateOAuthClient(): array {
```

2022-12-08 06:46 UTC, individual-it commented on lib/Controller/ConfigController.php
> +	 * returns auto-generated OAuth client information for nextcloud
```suggestion
	 * recreates the OAuth client and returns its details
```

2022-12-08 06:46 UTC, individual-it commented on appinfo/routes.php
> +		['name' => 'config#setUpWholeIntegration', 'url' => '/setup-whole-integration', 'verb' => 'PUT'],
```suggestion
		['name' => 'config#setup', 'url' => '/setup', 'verb' => 'PUT'],
```

2022-12-09 11:19 UTC, kiranparajuli589 commented on lib/Controller/ConfigController.php
> +		}
this check can be reused with some separate fn.

2022-12-09 11:19 UTC, kiranparajuli589 commented on lib/Controller/ConfigController.php
> +			"message" => "Delete Successful"
```suggestion
			"message" => "Reset Successful"
```

2022-12-12 07:49 UTC, individual-it requested changes

2022-12-12 07:49 UTC, individual-it commented on lib/Service/OpenProjectAPIService.php
> +			if ($key == 'openproject_instance_url' && !OpenProjectAPIService::validateURL((string)$value)) {
always use `===` to check also the type
```suggestion
			if ($key === 'openproject_instance_url' && !OpenProjectAPIService::validateURL((string)$value)) {
```
why casting `$value` to string?
shouldn't `validateURL` return false if the parameter is not string?

2022-12-12 07:49 UTC, individual-it commented on lib/Service/OpenProjectAPIService.php
> +				if (!is_bool($value)) {
```suggestion
			if (($key === 'default_enable_navigation' || $key === 'default_enable_unified_search') && !is_bool($value)) {
```

2022-12-12 08:23 UTC, individual-it requested changes
sending invalid JSON results in error 500, see tests added in https://github.com/nextcloud/integration_openproject/pull/280/commits/428e05391fdd89cea91a266ce4ba86f2d2e49d0e

2022-12-12 09:02 UTC, SagarGi commented on lib/Service/OpenProjectAPIService.php
> +				if (!is_bool($value)) {
i do not want to run the code below after this condition so i have checked it with extra if since i am using `continue`.

2022-12-15 04:11 UTC, individual-it requested changes

2022-12-15 04:11 UTC, individual-it commented on README.md
> +We have a single API endpoint (/setup) available to set , update and delete the integration.
```suggestion
We have a single API endpoint (/setup) available to set up, update and delete the integration.
```

2022-12-15 04:11 UTC, individual-it commented on README.md
> +    - openproject_client_id
```suggestion
These data need to be provided:
    - openproject_instance_url
    - openproject_client_id
```

2022-12-15 04:11 UTC, individual-it commented on README.md
> +-d '{"values":{"openproject_instance_url":<openproject_instance_url>,"openproject_client_id":<openproject_client_id>,"openproject_client_secret":<openproject_client_secret>,"default_enable_navigation
I think default_enable_navigation and default_enable_unified_search need to be "true" or "false"

2022-12-15 04:11 UTC, individual-it commented on README.md
> +	- openproject_client_id
```suggestion
One or more of this items need to be send to the endpoint
    - openproject_instance_url
    - openproject_client_id
    - openproject_client_id
```

2022-12-15 04:11 UTC, individual-it commented on README.md
> +1. Set up the whole integration with [POST] request
```suggestion
1. Set up the whole integration with a [POST] request
```

2022-12-15 04:11 UTC, individual-it commented on README.md
> +2. Update the integration with [PUT] request
```suggestion
2. Update the integration with a [PUT] request
```

2022-12-15 04:11 UTC, individual-it commented on README.md
> +2. Resetting the whole integration with [DELETE] request
```suggestion
2. Resetting the whole integration with a [DELETE] request
```

2022-12-15 06:06 UTC, SwikritiT commented
One of the things I noticed is that if we don't send the `Content-type : application/json ` header the request returns with `500` maybe `412` would be the appropriate error code.

2022-12-15 11:25 UTC, individual-it requested changes

2022-12-15 11:25 UTC, individual-it commented on lib/Controller/ConfigController.php
> +	public function recreateOauthClientInformation(): array {
this is only used in the own class
```suggestion
	private function recreateOauthClientInformation(): array {
```

2022-12-15 11:25 UTC, individual-it commented on lib/Controller/ConfigController.php
> +	public function setUpIntegrationConfig(array $values): array {
only used in the own class
```suggestion
	private function setIntegrationConfig(array $values): array {
```

2022-12-15 11:25 UTC, individual-it commented on lib/Service/OpenProjectAPIService.php
> +	public static function validateIntegrationSetupInformation(array $values, ?string $keyType = null): bool {
actually the second parameter is a bool, it only can have two values
```suggestion
	public static function validateIntegrationSetupInformation(array $values, bool $allKeysMandatory = true): bool {
```

2022-12-19 06:24 UTC, SwikritiT commented
Tested manually. Works fine for me. No regression caught so far!

2022-12-19 09:48 UTC, individual-it approved these changes

2022-12-19 09:48 UTC, merged