Direct upload implementation
nextcloud/integration_openproject pull request #303
Opened 2022-12-22 09:32 UTC by SwikritiT

Signed-off-by: Swikriti Tripathi <swikriti808@gmail.com>

2022-12-30 10:57 UTC, SwikritiT commented
Opening this up for review. Meanwhile, I'll add more tests to satisfy the PHP coverage

2023-01-02 07:17 UTC, individual-it requested changes

2023-01-02 07:17 UTC, individual-it commented on tests/acceptance/features/api/directUpload.feature
> +#      | ?&$%?§ file.txt |
what is wrong with that file-name?

2023-01-02 07:17 UTC, individual-it commented on lib/Controller/DirectUploadController.php
> +					'error' => 'Invalid token. The token should be 64 characters long and in human readable format.'
not sure if we want to tell anyone who is guessing tokens what the format should be. Use the token that you generated, if you send anything else you will receive a `'Invalid token'` message.
That check could also be integrated into `getTokenInfo()` or you could throw an exception here `throw new NotFoundException('Invalid token.');` then there will be just one place where the DataResponse is generated

2023-01-02 07:17 UTC, individual-it commented on lib/Service/DatabaseService.php
> +			$expiration = (int) $row['expires_on'];
just to reduce brain work, the logical naming would be:
```suggestion
			$expiresOn = (int) $row['expires_on'];
```

2023-01-02 07:17 UTC, individual-it commented on tests/acceptance/features/bootstrap/DirectUploadContext.php
> +		}
why not sending it all to the `replaceInlineCodes` ? If there is nothing to replace it would come back as it is?

2023-01-02 07:17 UTC, individual-it commented on tests/acceptance/features/bootstrap/FeatureContext.php
> +//		}
I think we need that header for other tests

2023-01-02 07:17 UTC, individual-it commented on tests/lib/Controller/DirectUploadControllerTest.php
> +	/**
delete code that is commented out

2023-01-02 07:17 UTC, individual-it commented on tests/lib/Controller/DirectUploadControllerTest.php
> +//		);
delete if not needed

2023-01-03 07:03 UTC, SwikritiT commented on lib/Service/DirectUploadService.php
> +		if ($tokenInfo['user_id'] === null || !$this->userManager->userExists($tokenInfo['user_id'])) {
Tested this manually and the token from the disabled user works. I'll add a check so that it doesn't happen and add a test as well

2023-01-03 07:04 UTC, SwikritiT commented on lib/Controller/DirectUploadController.php
> +					'error' => 'Invalid token. The token should be 64 characters long and in human readable format.'
I didn't think it that way. I'll refactor it

2023-01-03 09:58 UTC, SwikritiT commented on tests/acceptance/features/bootstrap/DirectUploadContext.php
> +		}
Yes but we are replacing the string with the last created upload token https://github.com/nextcloud/integration_openproject/blob/ab9f8a4c83f0fac355c7849faa4219f9512e4882/tests/acceptance/features/bootstrap/DirectUploadContext.php#L122
and when testing for invalid token  (hard-coded -token-from-feature-file) this ^ function throws error

2023-01-03 10:05 UTC, SwikritiT commented on tests/acceptance/features/bootstrap/FeatureContext.php
> +//		}
If I enable this the test will never enter the next if statement 
https://github.com/nextcloud/integration_openproject/blob/ab9f8a4c83f0fac355c7849faa4219f9512e4882/tests/acceptance/features/bootstrap/FeatureContext.php#L738

Because by the time it reaches here ^ one of the conditions i.e `$headers===null` is already false because `$headers` is set by the above commented if block.

the headers are set in else block. Do we really need that if check?

2023-01-03 11:59 UTC, individual-it requested changes
some small nitty picky comments

2023-01-03 11:59 UTC, individual-it commented on tests/acceptance/features/api/directUpload.feature
> +  Scenario Outline: Send valid file-names to the direct-upload endpoint
I think we could just integrate this scenario into the one above

2023-01-03 11:59 UTC, individual-it commented on tests/acceptance/features/api/directUpload.feature
> +  Scenario: use the token of disable user
```suggestion
  Scenario: use a token created by a user that was disabled after creating the token
```

2023-01-03 11:59 UTC, individual-it commented on tests/acceptance/features/api/directUpload.feature
> +  Scenario: use the token of disable user
we should also check a deleted user

2023-01-03 11:59 UTC, individual-it commented on lib/Controller/DirectUploadController.php
> +				$folderNode->isCreatable() &&
all the changes in this function do not really affect the new functionality, should we revert them?

2023-01-03 11:59 UTC, individual-it commented on lib/Controller/DirectUploadController.php
> +		} catch (Exception | NotPermittedException |NoUserException $e) {
catching "Exception" will also catch all other possible exceptions

2023-01-03 11:59 UTC, individual-it commented on lib/Controller/DirectUploadController.php
> +				$folderNode->isCreatable()  // @phpstan-ignore-line
phpstan does not complain for me when deleting the `// @phpstan-ignore-line` comments

2023-01-03 11:59 UTC, individual-it commented on tests/acceptance/features/api/directUpload.feature
> +          "error": {"type": "string", "pattern": "^Conflict, file with name file.txt already exists.$"}
I wouldn't mention the file name, the user knows it

2023-01-03 11:59 UTC, individual-it commented on tests/acceptance/features/bootstrap/FeatureContext.php
> +//		}
you are right, let's delete that whole if check

2023-01-03 11:59 UTC, individual-it commented on tests/acceptance/features/bootstrap/DirectUploadContext.php
> +		}
Oh yes, `str_replace` calls `getLastCreatedDirectUploadToken()` even nothing is found. 
Let's move the check into `replaceInlineCodes()` and I can work on refactoring the `replaceInlineCodes()` to get the other codes like `%now+3500s%` and  `%ids[1]%` into it

2023-01-03 11:59 UTC, individual-it commented on lib/Service/DirectUploadService.php
> +			throw new NotFoundException('Invalid token.');
we should unify the error messages, some are starting with a capital letter, some not, some have a `.` at the end, some not

2023-01-04 04:49 UTC, SwikritiT commented on tests/acceptance/features/api/directUpload.feature
> +  Scenario: use the token of disable user
test added in new commit

2023-01-04 04:50 UTC, SwikritiT commented on lib/Controller/DirectUploadController.php
> +				$folderNode->isCreatable() &&
true. I've reverted them

2023-01-04 04:50 UTC, SwikritiT commented on lib/Controller/DirectUploadController.php
> +				$folderNode->isCreatable()  // @phpstan-ignore-line
the CI complains

2023-01-04 04:50 UTC, SwikritiT commented on tests/acceptance/features/api/directUpload.feature
> +          "error": {"type": "string", "pattern": "^Conflict, file with name file.txt already exists.$"}
removed

2023-01-04 04:51 UTC, SwikritiT commented on lib/Service/DirectUploadService.php
> +			throw new NotFoundException('Invalid token.');
true. I've made them similar

2023-01-04 09:20 UTC, individual-it approved these changes

2023-01-04 09:20 UTC, merged