[OP#45464] Feature/direct upload api overwrite
nextcloud/integration_openproject pull request #310
Opened 2023-01-05 10:18 UTC by SwikritiT

related work package [OP#45464] : https://community.openproject.org/projects/nextcloud-integration/work_packages/45464

## Description
**Direct upload with overwrite parameter**:
   The overwrite parameter can be either set to `true` or `false`.
      1. **overwrite set to false**: 
      If the parameter is set to `false` and a file with the name already exists, a new file will be uploaded with existing name having a number suffix.
```console
curl-X POST 'http://<nextcloud_host>/index.php/apps/integration_openproject/direct-upload/<token>' \
--form 'file=@"<path-of-file>"' --form 'overwrite="false"' -H'Content-Type: multipart/form-data' 
```
The response from the above curl request will be
```json
 {
  "file_name": "<file_name>(some-number)",
   "file_id": <file_id>
 }  
```
     
 2. **overwrite set to true**:
      If the parameter is set to `true` and a file with the name already exists, the existing file will be overwritten.
 ```console
 curl-X POST 'http://<nextcloud_host>/index.php/apps/integration_openproject/direct-upload/<token>' \
 --form 'file=@"<path-of-file>"' --form 'overwrite="true"' -H'Content-Type: multipart/form-data'
 ```

The response from the above curl request will be
```json
{
   "file_name": "<file_name>",
  "file_id": <file_id>
} 
```

2023-01-10 10:32 UTC, individual-it commented on lib/Controller/DirectUploadController.php
> +					$this->databaseService->deleteToken($token);
what should we do in the case of an error, still delete the token, or leave it as it is?

2023-01-10 10:35 UTC, individual-it commented on tests/acceptance/features/api/directUpload.feature
> +          "file_name": {"type": "string", "pattern": "^file \\(3\\)\\.txt$"},
I guess that is the choice `getNonExistingName()` does, so its the standard way for NC

2023-01-11 06:07 UTC, SwikritiT commented on lib/Controller/DirectUploadController.php
> +					$this->databaseService->deleteToken($token);
In the specification, the deletion of the token is only after the successful upload, I think we can leave it as it is for errors so that the token can be reused for the next request.

2023-01-11 10:30 UTC, individual-it requested changes

2023-01-11 10:30 UTC, individual-it commented on README.md
> +          curl-X POST 'http://<nextcloud_host>/index.php/apps/integration_openproject/direct-upload/<token>' \
there needs to be a space after `curl`, I've made a similar fix in [09a0e47](https://github.com/nextcloud/integration_openproject/commit/09a0e4749df929ed7a41450326ade49af6582ad2)
```suggestion
          curl -X POST 'http://<nextcloud_host>/index.php/apps/integration_openproject/direct-upload/<token>' \
```
same in the other curl examples

2023-01-11 10:30 UTC, individual-it commented on README.md
> +      If the parameter is set to `true` and a file with the name already exists, the existing file will be overwritten.
What happens if there is a folder with that name?

2023-01-11 10:30 UTC, individual-it commented on README.md
> +		 ```console
there seems to be a mixture of spaces and tabs for indenting in your change, I think its better to use spaces everywhere

2023-01-11 10:30 UTC, individual-it commented on lib/Controller/DirectUploadController.php
> +					$file->putContent(fopen($tmpPath, 'r'));
do we need to delete the `$tmpPath` afterwards?

2023-01-11 10:30 UTC, individual-it commented on lib/Controller/DirectUploadController.php
> +					$overwrite = $overwrite === 'true' || $overwrite === 'True' ;
what about running `$overwrite = strtolower($overwrite);` then we don't need to check all kind of possibilities

2023-01-12 03:56 UTC, SwikritiT commented on README.md
> +      If the parameter is set to `true` and a file with the name already exists, the existing file will be overwritten.
I don't know, I would expect the file to be uploaded. I'll try it and add tests as well.

2023-01-12 04:14 UTC, SwikritiT commented on README.md
> +      If the parameter is set to `true` and a file with the name already exists, the existing file will be overwritten.
The current code throws `500` when overwrite is set to `true`, and works fine when set to `false` or when not set. I'll fix the code so it doesn't send `500` in this case

2023-01-12 05:41 UTC, SwikritiT commented on lib/Controller/DirectUploadController.php
> +					$file->putContent(fopen($tmpPath, 'r'));
Maybe not according to this documentation https://www.php.net/manual/en/features.file-upload.post-method.php
> The file will be deleted from the temporary directory at the end of the request if it has not been moved away or renamed.

2023-01-16 06:19 UTC, SwikritiT commented on tests/acceptance/features/api/directUpload.feature
> +  Scenario: don't set override and send a file with existing folder name
```suggestion
  Scenario: don't set overwriteand send a file with an existing folder name
```

2023-01-16 09:15 UTC, phil-davis commented on README.md
> +   Send multipart form data POST request to `direct-upload` end-point to upload the file with `token` acquired from preparation endpoint. The API takes and optional parameter `overwrite`.
```suggestion
   Send a multipart form data POST request to the `direct-upload` end-point to upload the file with `token` acquired from the preparation endpoint. The API takes an optional parameter `overwrite`.
```

2023-01-16 09:15 UTC, phil-davis commented on README.md
> +      In case the `overwrite` parameter is not set at all a file will be only uploaded if no file exists with that name, otherwise a conflict error is thrown.
```suggestion
      If the `overwrite` parameter is not set, a file will only be uploaded if no file exists with that name, otherwise a conflict error is thrown.
```

2023-01-16 09:15 UTC, phil-davis commented on README.md
> +         If the parameter is set to `false` and a file with the name already exists, a new file will be uploaded with existing name having a number suffix.
```suggestion
         If the parameter is set to `false` and a file with the name already exists, a new file will be uploaded with the existing name and a number suffix.
```

2023-01-16 09:15 UTC, phil-davis commented on README.md
>  There's an end-point `direct-upload` available which can be used for direct-upload. There's two steps to direct upload first we need to get the `token` which is then used for direct upload.
```suggestion
There's an end-point `direct-upload` available which can be used for direct-upload. There's two steps to direct upload. first we need to get the `token`. Then use the token in the direct upload request.
```

2023-01-16 09:15 UTC, phil-davis commented on README.md
> +              "file_name": "<file_name>(some-number)",
What happens about "file extension". Do we get `file(42).doc` or `file.doc(42)`?

Maybe there could be a real example that shows this.

2023-01-16 10:53 UTC, individual-it requested changes

2023-01-16 10:53 UTC, individual-it commented on README.md
> +          Suppose we have a file with name `file.txt` in the server, and we send a request to direct-upload api with file `file.txt` and overwrite set to `true` then the response will be.
```suggestion
          Suppose we have a file with name `file.txt` in the server, and we send a request to direct-upload api with the file `file.txt` and overwrite is set to `false` then the response will be.
```

2023-01-16 10:53 UTC, individual-it commented on README.md
> +          > Note: The file id in this case is the id of the original file. Only the content is overwritten.
I think this line has to go to `**overwrite set to true**:`

2023-01-16 10:59 UTC, SwikritiT commented on README.md
> +          > Note: The file id in this case is the id of the original file. Only the content is overwritten.
yes sorry I didn't notice

2023-01-17 03:53 UTC, individual-it approved these changes

2023-01-17 04:56 UTC, phil-davis commented on README.md
> +   If the `overwrite` parameter is not set at all only the file with non-existing name is uploaded and a conflict error is thrown in case the file already exists.
We now have:
"If the `overwrite` parameter is not set, a file will only be uploaded if no file exists with that name, otherwise a conflict error is thrown."

That looks good to me.

2023-01-17 07:08 UTC, merged