[OP#45466]Remove expired direct upload tokens using background jobs
nextcloud/integration_openproject pull request #341
Opened 2023-01-25 08:26 UTC by SagarGi

### Description
This PR implements the background jobs to remove the expired direct upload tokens from the databases.

### Related Workpackage
https://community.openproject.org/projects/817/work_packages/45466/activity

2023-01-26 04:06 UTC, individual-it requested changes

2023-01-26 04:06 UTC, individual-it commented on lib/Service/DatabaseService.php
> +		$req = $query->executeQuery();
just make a single request and let the DB deal with it, that will be much more performant that doing multiple requests.
MySQL should work like this: `DELETE FROM oc_direct_upload WHERE  expires_on < UNIX_TIMESTAMP();`

2023-01-26 04:06 UTC, individual-it commented on lib/Service/DirectUploadService.php
> -
not needed

2023-01-26 04:06 UTC, individual-it commented on lib/Service/DatabaseService.php
> +	 * Get All token information from database
not true, be honest ;-)

2023-01-26 04:06 UTC, individual-it commented on lib/Service/DatabaseService.php
> +	public function deleteAllExpiredTokenFromDB(): void {
```suggestion
	public function deleteExpiredTokens(): void {
```
as this is a DB class, its clear that its deleting from the DB

2023-01-26 04:13 UTC, individual-it commented on lib/Service/DatabaseService.php
> +		$req = $query->executeQuery();
for pgsql it might be easier to generate the timestamp in PHP. But still just have a single delete request

2023-01-26 05:57 UTC, SagarGi commented on lib/Service/DatabaseService.php
> +		$req = $query->executeQuery();
@individual-it do we want to use `UNIX_TIMESTAMP();` function which is for mysql. why not using the date instead? does it not work for pgsql?

2023-01-27 07:59 UTC, individual-it commented
The app is not enabled in CI when we run the unit tests. I would suggest to merge #323, rebase and then adjust then adjust the CI steps

2023-01-27 08:19 UTC, individual-it approved these changes

2023-01-27 08:23 UTC, SagarGi commented
> The app is not enabled in CI when we run the unit tests. I would suggest to merge #323, rebase and then adjust then adjust the CI steps

sure !!

2023-01-30 06:42 UTC, SwikritiT approved these changes

2023-01-30 06:42 UTC, merged