only allow user to connect via OAuth
nextcloud/integration_openproject pull request #35
Opened 2022-02-03 04:08 UTC by individual-it

the user should not have any option to connect via api tokens to OpenProject. This PR is part of that
- the oAuth URL is constructed in PHP and handed over to vue
- oAuth button is a separate Vue component and used in files-details-tab, dashboard, personal settings
-  in personal settings page the user can only connect and disconnect from OpenProject (via oAuth)

in following PR more work needs to be done:
- delete back-end code that deals with api tokens
- show correct status of the connection in the file-details-tab (currently connect button is displayed even the connection is established)

2022-02-03 05:45 UTC, kiranparajuli589 commented on src/components/OAuthConnectButton.vue
> +				})
`finally` maybe?

2022-02-03 05:45 UTC, kiranparajuli589 commented on src/components/PersonalSettings.vue
>  			<div v-if="connected" class="openproject-grid-form">
```suggestion
			<div v-else class="openproject-grid-form">
```

2022-02-03 06:21 UTC, individual-it commented on src/components/OAuthConnectButton.vue
> +				})
completely deleted because nothing to be done in the second `then`

2022-02-03 06:21 UTC, individual-it commented on src/components/PersonalSettings.vue
>  			<div v-if="connected" class="openproject-grid-form">
I've moved the logic around and placed the `OAuthConnectButton` at the bottom with an `v-else`

2022-02-03 06:28 UTC, kiranparajuli589 approved these changes

2022-02-03 06:36 UTC, individual-it commented
I've not adjusted also the documentation

2022-02-03 12:14 UTC, eneiluj requested changes
Very nice.
A few minor inline comments.

2022-02-03 12:14 UTC, eneiluj commented on lib/Settings/Personal.php
> +use OCA\OpenProject\Service\OpenProjectAPIService;
Just nitpicking here :grin:
Let's keep the `OCA\OpenProject` imports grouped lower if you don't mind.

2022-02-03 12:14 UTC, eneiluj commented on lib/Settings/Personal.php
> +	private IURLGenerator $url;
Php 7.3 compat

2022-02-03 12:14 UTC, eneiluj commented on lib/Service/OpenProjectAPIService.php
> +	public static function getOpenProjectOauthURL(IConfig $config, IURLGenerator $urlGenerator): string {
`IURLGenerator` could be injected in the constructor of `OpenProjectAPIService` instead of passing it as a parameter to `getOpenProjectOauthURL`. This would avoid having to inject `IURLGenerator` in every class calling this method.

2022-02-04 06:46 UTC, individual-it commented on lib/Service/OpenProjectAPIService.php
> +	public static function getOpenProjectOauthURL(IConfig $config, IURLGenerator $urlGenerator): string {
yes, but then every class that calls the method would have to initiate the complete `OpenProjectAPIService` and by that need to get injected even more
e..g from `OpenProjectWidget` we would need the logger, usermanager, avatarmanager etc.
Or maybe we want to place that function somewhere else? A helper class?

2022-02-04 07:36 UTC, individual-it commented on lib/Dashboard/OpenProjectWidget.php
> +	private IConfig $config;
thx for the hint done in 9316b6b100dc90e4971f37583fa381dddd4159c2

2022-02-04 07:36 UTC, individual-it commented on lib/Listener/LoadSidebarScript.php
> +	private IConfig $config;
done in 9316b6b100dc90e4971f37583fa381dddd4159c2

2022-02-04 07:36 UTC, individual-it commented on lib/Settings/Personal.php
> +	private IURLGenerator $url;
done in 9316b6b100dc90e4971f37583fa381dddd4159c2

2022-02-04 07:37 UTC, individual-it commented on lib/Settings/Personal.php
> +use OCA\OpenProject\Service\OpenProjectAPIService;
those things are good to fix and keep in order, done in dd9f2cc0f7578b7e721e60df97725701ea68b41c
hope that code style analysis will help in future

2022-02-16 03:36 UTC, individual-it commented
@eneiluj could you re-review and give your opinion on my comment here https://github.com/nextcloud/integration_openproject/pull/35#discussion_r799203671 ?

2022-02-18 09:28 UTC, eneiluj submitted a review, later dismissed
:+1:
One last small change and we're good to go.

2022-02-18 09:28 UTC, eneiluj commented on lib/Service/OpenProjectAPIService.php
> +			'&redirect_uri=' . $redirectUri .
```suggestion
			'&redirect_uri=' . urlencode($redirectUri) .
```

2022-02-18 09:28 UTC, eneiluj commented on lib/Service/OpenProjectAPIService.php
> +	public static function getOpenProjectOauthURL(IConfig $config, IURLGenerator $urlGenerator): string {
Yes I agree. As long as `getOpenProjectOauthURL` is a static method, let's keep it that way.
If you feel like it belongs in a new class/file, feel free to move it :grin:.

2022-02-18 11:42 UTC, individual-it commented on lib/Service/OpenProjectAPIService.php
> +			'&redirect_uri=' . $redirectUri .
good point, I've adjusted that and also squashed all commits

2022-02-21 05:38 UTC, individual-it commented
I found an other issue that I've missed before. The url to openproject was still taken from the user settings

2022-02-21 10:47 UTC, merged