Implementation/create user openproject
nextcloud/integration_openproject pull request #358
Opened 2023-02-14 11:28 UTC by SwikritiT

2023-02-16 05:34 UTC, individual-it commented
The user still can be renamed and disabled, also the group can be disabled. We need to see if that also can be circumvented

2023-02-24 11:18 UTC, individual-it requested changes
looks good to me, but let's merge on Monday

2023-02-27 09:18 UTC, SagarGi reviewed
Looks Good to me. Checked it for integration script.

2023-02-28 05:48 UTC, individual-it approved these changes

2023-02-28 05:49 UTC, merged