[OP#46179 & OP#46178]Implement project folders and app password (UI and API)
nextcloud/integration_openproject pull request #375
Opened 2023-03-28 07:06 UTC by SagarGi

### Description
This PR implements:
- Group folders setup form (UI and API)
- App password form (UI and API)
- Adds UI unit tests
- Adds API tests
- Adjust `/setup` endpoint to setup whole integration

Related WorkPackage:
https://community.openproject.org/projects/nextcloud-integration/work_packages/46179/activity?query_id=3787
https://community.openproject.org/projects/nextcloud-integration/work_packages/46178/activity?query_id=3787

2023-05-02 09:46 UTC, SagarGi commented
@julien-nc  A strange error has been encountered when we switch from master to this branch. And also in the master branch as well. 
Steps to reproduce:
1. After setting up the integration switch to this branch
2. run build
3. then through UI try to set up the integration without group folder enabled.
4. the error is shown `group folder app is not enabled`
5. then enable the group folder app and retry again. 
6. then `__group folder locked error` is shown.

After the error is shown when we refresh then it crashes the whole App. Again upon refresh then we can set it up again.
It only appears single time. The next time we delete all the group folders related things and set it up again the error is not shown. It only appears again when we reset the whole nextcloud set up. And also appears in master branch with API endpoint `/setup` => POST.

2023-05-04 07:49 UTC, individual-it requested changes

2023-05-04 07:49 UTC, individual-it commented on lib/Controller/ConfigController.php
> +			"reset_app_password" => null
```suggestion
			'reset_app_password' => null
```

2023-05-04 10:59 UTC, individual-it requested changes

2023-05-04 10:59 UTC, individual-it commented on lib/Controller/ConfigController.php
> +			$app_password = $this->openprojectAPIService->createOrReplaceAppPasswordToken();
```suggestion
			$appPassword = $this->openprojectAPIService->createOrReplaceAppPasswordToken();
```

2023-05-04 10:59 UTC, individual-it commented on lib/Controller/ConfigController.php
> +		$app_password = null;
```suggestion
		$appPassword = null;
```

2023-05-04 10:59 UTC, individual-it commented on lib/Controller/ConfigController.php
> +		if(($runningFullReset && key_exists('reset_app_password', $values) && $values['reset_app_password'] === null) || ($values['managed_folder_state'] !== true && $values['reset_app_password'] === null)
too long line

2023-05-04 10:59 UTC, individual-it commented on lib/Service/OpenProjectAPIService.php
>  			// validating specific two key
that are more than two

2023-05-04 10:59 UTC, individual-it commented on lib/Service/OpenProjectAPIService.php
> +			$token_id = $this->tokenProvider->getTokenByUser(Application::OPEN_PROJECT_ENTITIES_NAME)[0]->getId();
```suggestion
			$tokenId = $this->tokenProvider->getTokenByUser(Application::OPEN_PROJECT_ENTITIES_NAME)[0]->getId();
```

2023-05-04 10:59 UTC, individual-it commented on lib/Service/OpenProjectAPIService.php
> +	public function hasAppPasswordAlready(): bool {
```suggestion
	public function hasAppPassword(): bool {
```

2023-05-04 10:59 UTC, individual-it commented on lib/Settings/Admin.php
> +		$groupFolderStatusInformation = $this->openProjectAPIService-> getGroupFolderSetupInformation();
```suggestion
		$groupFolderStatusInformation = $this->openProjectAPIService->getGroupFolderSetupInformation();
```

2023-05-04 11:00 UTC, individual-it commented
![image](https://user-images.githubusercontent.com/2425577/236185573-a0bb26d1-5ddd-4631-8134-c8377a411e24.png)
the text does not fit

2023-05-05 06:32 UTC, individual-it commented on src/components/AdminSettings.vue
> +					label="Application password*"
two `*` are shown on the screen
![image](https://user-images.githubusercontent.com/2425577/236390704-de0144ec-39b2-4676-9c26-777ef6357265.png)

2023-05-09 04:58 UTC, SwikritiT commented on lib/Controller/ConfigController.php
> +					$openProjectGroupFolderFileId = $this->openprojectAPIService->createGroupfolder();
this doesn't look right
```
composer cs:fix
```

2023-05-09 05:00 UTC, SwikritiT commented on lib/Controller/ConfigController.php
> +		// code for updating the app password token
```suggestion
		// this condition applies only when everything related to group folder along with app password is already setup
		// code for updating the app password token
```

2023-05-09 05:00 UTC, SwikritiT commented on lib/Controller/ConfigController.php
> +		// TODO
still a todo?

2023-05-09 05:02 UTC, SwikritiT commented on lib/Controller/ConfigController.php
> +	 * @NoCSRFRequired
reminder to remove this before merging

2023-05-09 05:03 UTC, SwikritiT commented on lib/Controller/OpenProjectAPIController.php
> +		// all the thing is ok then we return true and complete the integration
```suggestion
		// if everything is ok then we return true and complete the integration
```

2023-05-09 05:36 UTC, SwikritiT commented
The group folder error can also be reproduced as such
1. Fresh setup the NC
2. Switch to this branch
3. fill the op host, op oathu creds and NC oauth creds
4. Refresh the page
5. Enable the groupfolders app
6. Try to setup the groupfolder

2023-05-09 05:55 UTC, individual-it commented on lib/Service/OpenProjectAPIService.php
> +		$allAppKeys = $this->config->getAppKeys(Application::APP_ID);
why getting all keys, cannot we get just the single key?

2023-05-09 06:56 UTC, individual-it commented on lib/Service/OpenProjectAPIService.php
> +	public function isSetForFirstTime(): bool {
```suggestion
	public function firstTimeGroupFolderSetup(): bool {
```

2023-05-09 06:56 UTC, individual-it commented on lib/Service/OpenProjectAPIService.php
> +	 * check if app password for user OpenProject is already created
??

2023-05-09 07:17 UTC, individual-it requested changes

2023-05-09 07:17 UTC, individual-it commented on src/components/AdminSettings.vue
> +				:is-disabled="isManagedGroupFolderSetUpInDisableMode"
GroupFolder, ManagedProjectFolder, ManagedGroupFolder. Are those the same thing, or different? If that is all the same call it the same

2023-05-09 07:17 UTC, individual-it commented on src/components/AdminSettings.vue
> +				if (this.managedFolderState) {
```suggestion
				if (this.managedFolderState === true) {
```

2023-05-09 07:17 UTC, individual-it commented on src/components/AdminSettings.vue
> +			isGroupfolderSetupAutomaticallyReady: null,
```suggestion
			isProjectFolderSwitchEnabled: null,
```

2023-05-09 07:17 UTC, individual-it commented on src/components/AdminSettings.vue
> +		async checkForErrorOrSetUpOpenProjectGroupFolders() {
```suggestion
		async setUpProjectGroupFolders() {
```

2023-05-09 10:09 UTC, SwikritiT commented on src/components/AdminSettings.vue
> +								t('integration_openproject', 'Let OpenProject create folders per project automatically. It will ensure that every team member has always the correct access permission.')
This should be permissions according to figma
```suggestion
								t('integration_openproject', 'Let OpenProject create folders per project automatically. It will ensure that every team member has always the correct access permissions.')
```

2023-05-09 10:15 UTC, SwikritiT commented on src/components/AdminSettings.vue
> +					label="Application password*"
This still shows up for me as well so I'm unresolving

2023-05-09 10:17 UTC, SwikritiT commented on src/components/AdminSettings.vue
> +				return t('integration_openproject', 'Please install the group folder app, to be able to use automatic managed folders or deactivate the automatically managed folders.')
```suggestion
				return t('integration_openproject', 'Please install the group folder to be able to use automatic managed folders or deactivate the automatically managed folders.')
```

2023-05-09 10:27 UTC, SagarGi commented on src/components/AdminSettings.vue
> +					label="Application password*"
oh i thought it was in view mode but it is actually in edit mode. Fixing it right away.

2023-05-09 10:30 UTC, SwikritiT commented on src/components/AdminSettings.vue
> +				return t('integration_openproject', 'Please make sure to rename the group folder or completely delete the previous one or deactivate the automatically managed folders.')
why not refactor the backend error messages to send these messages, instead of switching here?

2023-05-09 10:38 UTC, SagarGi commented on src/components/AdminSettings.vue
> +				return t('integration_openproject', 'Please make sure to rename the group folder or completely delete the previous one or deactivate the automatically managed folders.')
just switching for the sub error message since different error has or might have different sub error description. The main error is displayed and used from backend.

2023-05-09 10:47 UTC, SwikritiT commented on src/components/admin/FormHeading.vue
> +		background: #555555;
let's add variable here as well instead of hardcoding the color

2023-05-10 03:47 UTC, SwikritiT commented on src/components/AdminSettings.vue
> +								t('integration_openproject', 'For automatically managing project folders, this app needs to setup a special group folder, assigned to a group and managed by a folder,each called "OpenProject"
```suggestion
								t('integration_openproject', 'For automatically managing project folders, this app needs to setup a special group folder, assigned to a group and managed by a user, each called "OpenProject".')
```

2023-05-10 03:48 UTC, SwikritiT commented on src/components/AdminSettings.vue
> +								t('integration_openproject', 'For automatically managing project folders, this app needs to setup a special group folder, assigned to a group and managed by a folder,each called "OpenProject"
This has been updated in Figma as well now
```suggestion
								t('integration_openproject', 'For automatically managing project folders, this app needs to setup a special group folder, assigned to a group and managed by a user, each called "OpenProject".')
```

2023-05-10 06:40 UTC, SagarGi commented on lib/Service/OpenProjectAPIService.php
> +		$allAppKeys = $this->config->getAppKeys(Application::APP_ID);
there is no specific function in the interface to get the single key but the other interface has function `hasKey($app, $key);`

2023-05-10 06:50 UTC, individual-it commented on lib/Service/OpenProjectAPIService.php
> +		$allAppKeys = $this->config->getAppKeys(Application::APP_ID);
you can use `getAppValue`, it returns `null` if the key does not exist

2023-05-10 08:45 UTC, SwikritiT commented
I'm getting this error now even though everything is setup correctly
![Screenshot from 2023-05-10 14-24-40](https://github.com/nextcloud/integration_openproject/assets/41103328/d831b27f-3ee4-48f1-9981-c5ca70058d71)

2023-05-10 09:09 UTC, SagarGi commented
> > I'm getting this error now even though everything is setup correctly ![Screenshot from 2023-05-10 14-24-40](https://user-images.githubusercontent.com/41103328/237331737-d831b27f-3ee4-48f1-9981-c5ca70058d71.png)
> 
> this happens only in sqlite

`$this->canOPUserManageACL()` this function gives false always even if the set up is completed. ugh..

2023-05-18 10:40 UTC, SwikritiT commented on lib/Service/OpenProjectAPIService.php
> +		);
```suggestion
		$generatedToken = $this->tokenProvider->generateToken(
			$token,
			$user->getUID(),
			$user->getUID(),
			null,
			Application::OPEN_PROJECT_ENTITIES_NAME
		);
```

2023-05-18 10:40 UTC, SwikritiT commented on lib/Service/OpenProjectAPIService.php
> +		$appName = Application::OPEN_PROJECT_ENTITIES_NAME;
```suggestion
```

2023-05-19 07:07 UTC, SwikritiT commented on lib/Service/OpenProjectAPIService.php
> +		);
I fixed this

2023-05-22 03:54 UTC, SwikritiT commented on .github/workflows/ci.yml
>          phpVersion: [ 7.4, 8.0, 8.1 ]
these changes will be reverted

2023-05-24 06:14 UTC, SwikritiT commented on lib/Controller/ConfigController.php
> +				throw new \Exception('User "' . Application::OPEN_PROJECT_ENTITIES_NAME . '" does not exists to create application password');
Should we throw the specific exception here and catch with and return it with `404`  here instead of the general exception  , I think this will return  `400` 
```
NotFoundException | NoUserException 
```

2023-05-24 06:20 UTC, SwikritiT commented on lib/Controller/OpenProjectAPIController.php
> +	 * @NoCSRFRequired
This should not be required?
```suggestion
```

2023-05-24 06:21 UTC, SwikritiT commented on lib/Controller/OpenProjectAPIController.php
> +		}
Maybe can be done like this since we're not reusing the variable anyway
```suggestion
		// if everything is ok then we return true and complete the integration
		if ($this->openprojectAPIService->isGroupFolderSetup()) {
			return new DataResponse(
				[
					'result' => true
				]
			);
		}
```

2023-05-24 06:24 UTC, SwikritiT commented on lib/Migration/Version2400Date20230504144300.php
> + * @copyright Copyright (c) 2022 Sagar Gurung <sagar@jankaritech.com>
```suggestion
 * @copyright Copyright (c) 2023 Sagar Gurung <sagar@jankaritech.com>
```

2023-05-24 06:31 UTC, SwikritiT commented on lib/Service/OpenProjectAPIService.php
> +				throw new \Exception('The group folder app is not installed');
I think we should throw some specified exception for the known case instead of throwing this generic exception. And `\Exception` should be caught and returned with `500` but with our current setup, it'll always return with`400` which might not always be true. But, we can do this refactoring in another PR, since I see other places where we do this as well, just mention this here as future refrence

2023-05-24 06:46 UTC, SwikritiT commented on src/components/AdminSettings.vue
> +								t('integration_openproject', 'The app will never delete files or folders, even if you deactivate this later')
We need a full-stop here
```suggestion
								t('integration_openproject', 'The app will never delete files or folders, even if you deactivate this later.')
```

2023-05-24 06:56 UTC, SwikritiT commented on src/components/AdminSettings.vue
> +					class="py-1"
Is this class used in styling? Do we need this?
```suggestion
					class="py-1"
```

2023-05-24 06:57 UTC, SwikritiT commented on src/components/AdminSettings.vue
> +			// this keep track of the state of group folder when user has done some setup (with or without)
```suggestion
			// this keeps track of the state of group folder when user has done some setup (with or without)
```

2023-05-24 06:58 UTC, SwikritiT commented on src/components/AdminSettings.vue
> +			// pointer from which form the request is coming
```suggestion
			// pointer for which form the request is coming
```

2023-05-24 06:58 UTC, SwikritiT commented on src/components/AdminSettings.vue
> +		isOPSUserAppPasswordFormComplete() {
```suggestion
		isOPUserAppPasswordFormComplete() {
```

2023-05-24 07:01 UTC, SwikritiT commented on src/components/AdminSettings.vue
> +			return (this.opUserAppPassword && this.formMode.groupFolderSetUp !== F_MODES.EDIT && this.isGroupFolderSetupCorrect === false)
Shouldn't this be true?
```suggestion
			return (this.opUserAppPassword && this.formMode.groupFolderSetUp !== F_MODES.EDIT && this.isGroupFolderSetupCorrect === true)
```

2023-05-24 07:08 UTC, SwikritiT commented on src/components/AdminSettings.vue
> +			return t('integration_openproject', 'This value will not be accessible again after you clicking save. Copy this password to OpenProject {htmlLink} as an Administrator.', { htmlLink }, null, { esca
Though in figma it's `clicking` I think grammatically this should be `click` I've commented in Figma as well for this
```suggestion
			return t('integration_openproject', 'This value will not be accessible again after you click save. Copy this password to OpenProject {htmlLink} as an Administrator.', { htmlLink }, null, { escape: false, sanitize: false })
```

2023-05-24 07:18 UTC, SwikritiT commented on src/components/AdminSettings.vue
> +				this.textLabelGroupFolderSetupButton = t('integration_openproject', 'Setup OpenProject user, group and folder')
I think we should store the texts used in buttons like  t('integration_openproject', 'Setup OpenProject user, group and folder') in a constant variable  with some appropriate and then use that variable everywhere needed, I see a lot of repetitions of the text
```suggestion
				this.textLabelGroupFolderSetupButton = textForSettingUpGroupFolders
```

2023-05-24 07:50 UTC, SwikritiT commented on src/components/AdminSettings.vue
> +								t('integration_openproject', 'We recommend using this functionality but is not mandatory. Please activate in case you want to use the automatic creation and management of project folders.')
I think `it` is also necessary here, I've commented in figma as well
```suggestion
								t('integration_openproject', 'We recommend using this functionality but it is not mandatory. Please activate in case you want to use the automatic creation and management of project folders.')
```

2023-05-24 09:08 UTC, SwikritiT commented on tests/acceptance/features/bootstrap/FeatureContext.php
> +	public function theUserSendsRequestTo(string $user, string $method, string $endpoint, string $appPassword)
```suggestion
	 */
	public function theUserSendsRequestTo(string $user, string $method, string $endpoint, string $appPassword): void
```

2023-05-24 09:08 UTC, SwikritiT commented on tests/acceptance/features/bootstrap/FeatureContext.php
> +	 * @throws Exception
```suggestion
	 *
	 * @param string $user
	 * @param string $method
	 * @param string $endpoint
	 * @param string $appPassword
	 * @return void
	 * @throws Exception
```

2023-05-24 09:21 UTC, SwikritiT commented on tests/jest/components/AdminSettings.spec.js
> +	describe('form mode and completed status without group folder, user app password setup', () => {
I think the app password comes with the group folder setup so maybe not needed to be mentioned. What do you think?
```suggestion
	describe('form mode and completed status without group folder setup', () => {
```

2023-05-24 09:28 UTC, SwikritiT commented on tests/jest/components/AdminSettings.spec.js
> +				it('on trigger switch should show button text label "Complete without group folder setup"', async () => {
is this appropriate for this case?
```suggestion
				it(' should show button text label "Complete without group folder setup" when the switch is "off"', async () => {
```

2023-05-24 09:33 UTC, SwikritiT commented on tests/jest/components/AdminSettings.spec.js
> +				describe.only('trigger on "Setup OpenProject user, group and folder" button', () => {
```suggestion
				describe('trigger on "Setup OpenProject user, group and folder" button', () => {
```

2023-05-24 09:45 UTC, SwikritiT commented on tests/jest/components/AdminSettings.spec.js
> +						it('should group folder state as "Active"', async () => {
```suggestion
						it('should set group folder state as "Active"', async () => {
```

2023-05-24 09:45 UTC, SwikritiT commented on tests/jest/components/AdminSettings.spec.js
> +						it('group folder setup form to edit mdoe', async () => {
```suggestion
						it('should set group folder setup form to edit mode, async () => {
```

2023-05-24 09:48 UTC, SwikritiT commented on tests/jest/components/AdminSettings.spec.js
> +			describe('If Already deactivated', function() {
```suggestion
			describe('default deactive state', function() {
```

2023-05-24 09:49 UTC, SwikritiT commented on tests/jest/components/AdminSettings.spec.js
> +				it('should show button label to "Setup OpenProject user, group and folder" when switch in "On"', async () => {
```suggestion
				it('should show button label to "Setup OpenProject user, group and folder" when switch is "On"', async () => {
```

2023-05-24 09:49 UTC, SwikritiT commented on tests/jest/components/AdminSettings.spec.js
> +			describe('upon complete setup (group folder and app password)', function() {
```suggestion
			describe('complete setup (group folder and app password)', function() {
```

2023-05-24 09:50 UTC, SwikritiT commented on tests/jest/components/AdminSettings.spec.js
> +				describe('edit mode again', function() {
```suggestion
				describe('edit mode', function() {
```

2023-05-24 09:53 UTC, SwikritiT commented on tests/jest/components/AdminSettings.spec.js
> +					it('on trigger "Keep on current change" should not create new user app password', async () => {
```suggestion
					it('on trigger "Keep on current change" should not create new user app password', async () => {
```
```suggestion
					it('should not create new user app password when the state is at "Keep on current change"', async () => {
```

2023-05-24 09:54 UTC, SwikritiT commented on tests/jest/components/AdminSettings.spec.js
> +					it('on switch "off" should show button label as "Complete without group folder setup"', async () => {
```suggestion
					it('should show button label as "Complete without group folder setup" when the switch "off"', async () => {
```

2023-05-24 09:55 UTC, SwikritiT commented on tests/jest/components/AdminSettings.spec.js
> +					it('resetting should set switch as "off" again (same as fresh set up)', async () => {
Should this be "on" ?
```suggestion
					it('should set switch as "on" after a full reset', async () => {
```

2023-05-24 09:57 UTC, SwikritiT commented on tests/jest/components/AdminSettings.spec.js
> +	describe('Reset User App password', () => {
```suggestion
	describe('user app password reset', () => {
```

2023-05-24 09:57 UTC, SwikritiT commented on tests/jest/components/AdminSettings.spec.js
> +	describe('Error after group folder is already setup', () => {
```suggestion
	describe('error after group folder is already setup', () => {
```

2023-05-24 09:59 UTC, SwikritiT commented on tests/jest/components/AdminSettings.spec.js
> +			it('should reset all settings on confirm when group folder, app password is not set', async () => {
```suggestion
			it('should reset all settings on confirm when group folder is not set up', async () => {
```

2023-05-24 10:09 UTC, SagarGi commented on tests/jest/components/AdminSettings.spec.js
> +	describe('form mode and completed status without group folder, user app password setup', () => {
yes can be removed but still can be checked different the state of it.

2023-05-25 04:07 UTC, SwikritiT commented on src/components/AdminSettings.vue
> +			return t('integration_openproject', 'This value will not be accessible again after you click save. Copy this password to OpenProject {htmlLink} as an Administrator.', { htmlLink }, null, { escape:
The wording has been changed a little bit in figma.
```suggestion
			return t('integration_openproject', 'This value is only visible now and then never again. Copy this password to OpenProject {htmlLink} as an Administrator.', { htmlLink }, null, { escape: false, sanitize: false })
```

2023-05-26 10:48 UTC, SwikritiT commented on lib/Controller/ConfigController.php
> +			$this->config->setAppValue(Application::APP_ID, 'fresh_group_folder_setup', "1");
Should we also change this to `project`?
```suggestion0
			$this->config->setAppValue(Application::APP_ID, 'fresh_project_folder_setup', "1");
```

2023-05-26 10:49 UTC, SwikritiT commented on lib/Controller/OpenProjectAPIController.php
> +	public function getGroupFolderSetupStatus(): DataResponse {
Here too?
```suggestion
	public function getProjectFolderSetupStatus(): DataResponse {
```

2023-05-26 10:50 UTC, SwikritiT commented on lib/Migration/Version2400Date20230504144300.php
> +			Application::APP_ID, 'fresh_group_folder_setup', "1"
```suggestion
			Application::APP_ID, 'fresh_project_folder_setup', "1"
```

2023-05-26 10:50 UTC, SwikritiT commented on lib/Service/OpenProjectAPIService.php
> +			'setup_group_folder',
Maybe this key as well?
```suggestion
			'setup_project_folder',
```

2023-05-26 10:52 UTC, SwikritiT commented on lib/Service/OpenProjectAPIService.php
> +				$this->isSystemReadyForGroupFolderSetUp();
```suggestion
				$this->isSystemReadyForProjectFolderSetUp();
```

2023-05-26 10:52 UTC, SwikritiT commented on lib/Service/OpenProjectAPIService.php
> +	public function getGroupFolderSetupInformation(): array {
```suggestion
	public function getProjectFolderSetupInformation(): array {
```

2023-05-26 10:53 UTC, SwikritiT commented on lib/Settings/Admin.php
> +			'group_folder_status' => $groupFolderStatusInformation,
Will it make sense here too?
```suggestion
			'project_folder_status' => $groupFolderStatusInformation,
```

2023-05-26 10:54 UTC, SwikritiT commented on src/components/AdminSettings.vue
> +		<div class="group-folder-setup">
```suggestion
		<div class="project-folder-setup">
```

2023-05-26 11:09 UTC, SwikritiT reviewed
Per our discussion today, I've commented on the lines where I think `groupFolders` should be replaced by `projectFolder`. Please look and them and determine if it makes sense for you too.

2023-05-26 11:09 UTC, SwikritiT commented on src/components/AdminSettings.vue
> +				:is-setup-complete-without-group-folders="isSetupCompleteWithoutGroupFolders"
```suggestion
				:is-setup-complete-without-project-folders="isSetupCompleteWithoutProjectFolders"
```

2023-05-26 11:09 UTC, SwikritiT commented on src/components/AdminSettings.vue
> +				:is-there-error-after-group-folder-and-app-password-setup="isThereErrorAfterGroupFolderAndAppPasswordSetup"
```suggestion
				:is-there-error-after-project-folder-setup="isThereErrorAfterProjectFolderSetup"
```

2023-05-26 11:09 UTC, SwikritiT commented on src/components/AdminSettings.vue
> +				:is-complete="isGroupFolderSetupCompleted"
```suggestion
				:is-complete="isProjectFolderSetupCompleted"
```

2023-05-26 11:09 UTC, SwikritiT commented on src/components/AdminSettings.vue
> +				:is-disabled="isGroupFolderSetUpInDisableMode" />
```suggestion
				:is-disabled="isProjectFolderSetUpInDisableMode" />
```

2023-05-26 11:09 UTC, SwikritiT commented on src/components/AdminSettings.vue
> +					<NcCheckboxRadioSwitch type="switch" :checked.sync="isProjectFolderSwitchEnabled" @update:checked="changeGroupFolderSetUpState">
```suggestion
				<div v-if="isProjectFolderSetupFormInEdit">
					<NcCheckboxRadioSwitch type="switch" :checked.sync="isProjectFolderSwitchEnabled" @update:checked="changeProjectFolderSetUpState">
```

2023-05-26 11:09 UTC, SwikritiT commented on src/components/AdminSettings.vue
> +						<p class="group-folder-description">
```suggestion
						<p class="project-folder-description">
```

2023-05-26 11:09 UTC, SwikritiT commented on src/components/AdminSettings.vue
> +								data-test-id="complete-without-group-folder-form-btn"
```suggestion
								data-test-id="complete-without-project-folder-form-btn"
```

2023-05-26 11:09 UTC, SwikritiT commented on src/components/AdminSettings.vue
> +								@click="completeIntegrationWithoutGroupFolderSetUp">
```suggestion
								@click="completeIntegrationWithoutProjectFolderSetUp">
```

2023-05-26 11:09 UTC, SwikritiT commented on src/components/AdminSettings.vue
> +									textLabelGroupFolderSetupButton
```suggestion
									textLabelProjectFolderSetupButton
```

2023-05-26 11:09 UTC, SwikritiT commented on src/components/AdminSettings.vue
> +						<p class="group-folder-description">
```suggestion
						<p class="project-folder-description">
```

2023-05-26 11:09 UTC, SwikritiT commented on src/components/AdminSettings.vue
> +						<p class="group-folder-description">
```suggestion
						<p class="project-folder-description">
```

2023-05-26 11:09 UTC, SwikritiT commented on src/components/AdminSettings.vue
> +						<GroupFolderError v-if="groupFolderSetupError !== null" :group-folder-set-up-error-message-description="groupFolderSetUpErrorMessageDescription(groupFolderSetupError)" :group-folder-set-up-erro
```suggestion
						</p>
						<ProjectFolderError v-if="ProjectFolderSetupError !== null" :project-folder-set-up-error-message-description="projectFolderSetUpErrorMessageDescription(projectFolderSetupError)" :project-folder-set-up-error="projectFolderSetupError" />
```

2023-05-26 11:09 UTC, SwikritiT commented on src/components/AdminSettings.vue
> +								type="primary"
```suggestion
							<NcButton v-else-if="projectFolderSetupError"
								type="primary"
```

2023-05-26 11:09 UTC, SwikritiT commented on src/components/AdminSettings.vue
> +								data-test-id="complete-with-projectfolders-form-btn"
```suggestion
								data-test-id="complete-with-project-folders-form-btn"
```

2023-05-26 11:09 UTC, SwikritiT commented on src/components/AdminSettings.vue
> +									<LoadingIcon v-if="loadingSetupGroupFolder" class="loading-spinner" :size="20" />
```suggestion
									<LoadingIcon v-if="loadingSetupProjectFolder" class="loading-spinner" :size="20" />
```

2023-05-26 11:09 UTC, SwikritiT commented on src/components/AdminSettings.vue
> +								@click="setUpProjectGroupFolders">
```suggestion
								@click="setUpProjectFolders">
```

2023-05-30 09:48 UTC, SagarGi commented on lib/Service/OpenProjectAPIService.php
> +				throw new \Exception('The group folder app is not installed');
Yes may be we can do it in separate PR.

2023-05-30 09:48 UTC, SagarGi commented on src/components/AdminSettings.vue
> +					class="py-1"
all the components have these. If of no use can be deleted from every component.

2023-05-31 10:04 UTC, individual-it approved these changes

2023-06-02 10:48 UTC, SwikritiT commented on src/components/AdminSettings.vue
> +				keepCurrentChange: t('integration_openproject', 'Keep current change'),
The wording has changed to, but this can be done in next PR just mentioning here as a reminder 
```suggestion
				keepCurrentChange: t('integration_openproject', 'Keep current setup'),
```

2023-06-02 10:51 UTC, SwikritiT commented on src/components/AdminSettings.vue
> +					class="py-1"
okay maybe we can check if this is needed and make changes in coming PR's

2023-06-06 03:27 UTC, SwikritiT commented on src/components/AdminSettings.vue
> +			case 'The group folder name "OpenProject" integration already exists' :
Recent changes in figma. Can be done in coming PR's. 
```suggestion
			case 'The group folder name "OpenProject" already exists' :
```

2023-06-06 03:29 UTC, SwikritiT commented on src/components/AdminSettings.vue
> +			case 'The group folder app is not installed' :
```suggestion
			case 'The "Group folder" app is not installed' :
```

2023-06-06 03:29 UTC, SwikritiT commented on src/components/AdminSettings.vue
> +				return t('integration_openproject', 'Please install the group folder to be able to use automatic managed folders or deactivate the automatically managed folders.')
```suggestion
				return t('integration_openproject', 'Please install the "Group folder" to be able to use automatic managed folders or deactivate the automatically managed folders.')
```

2023-06-06 10:27 UTC, SwikritiT commented on .github/workflows/ci.yml
> +        uses: shivammathur/setup-php@verbose
is this change needed?
```suggestion
        uses: shivammathur/setup-php@v2
```

2023-06-06 10:37 UTC, SagarGi commented on .github/workflows/ci.yml
> +        uses: shivammathur/setup-php@verbose
forgot to revert it thanks.

2023-06-06 10:38 UTC, SagarGi commented
I will be updating all the changes from the figma may be in next PR so i have skipped the changes for now. @SwikritiT

2023-06-06 10:38 UTC, SwikritiT approved these changes
Let's make another PR for other refactoring

2023-06-07 05:26 UTC, SwikritiT commented
I'll be merging this

2023-06-07 05:26 UTC, merged