Make files-info endpoint return path and permissions of the file
nextcloud/integration_openproject pull request #385
Opened 2023-04-03 09:51 UTC by SwikritiT

2023-04-03 11:16 UTC, Kharonus requested changes

2023-04-03 11:16 UTC, Kharonus commented on lib/Controller/FilesController.php
> +				'path' => $internalPath
taking code from 204, `$internalPath` is most of the time the path of the owner, not the requesting user. But the later one is the one, we need.

2023-04-04 03:40 UTC, SwikritiT commented on lib/Controller/FilesController.php
> +				'path' => $internalPath
true. I'll change it

2023-04-04 04:21 UTC, SwikritiT commented on lib/Controller/FilesController.php
> +				'path' => $internalPath
@Kharonus do you need it like `<user>/files/a/b/..` or `files/a/a/..` or does it not matter?

2023-04-04 08:41 UTC, Kharonus commented on lib/Controller/FilesController.php
> +				'path' => $internalPath
@SwikritiT Thanks for changing it. 

It should not matter, if the user is prefixed to the location path or not. We shift around values without the user, so we would have lesser postprocessing if the location is `files/a/b`. What is your opinion on that?

2023-04-04 10:50 UTC, SwikritiT commented on lib/Controller/FilesController.php
> +				'path' => $internalPath
Yes, makes sense. I've returned the one without the user.

2023-04-04 10:59 UTC, Kharonus approved these changes

2023-04-06 10:57 UTC, SwikritiT commented on lib/Controller/FilesController.php
> +			$fullpath = $file->getpath();
We cannot use `getInternalPath()` here like in https://github.com/nextcloud/integration_openproject/pull/385/commits/7fa31074f63c4844c7821f285f073dd3665d8d1c because `getInternalPath()` gets the path relative to the storage, and in case of a shared resource, the request from the share receiver will get an empty internal path as they don't own the file and the storage is that of the owner.

2023-04-06 11:25 UTC, SwikritiT commented
Seems like this file https://github.com/nextcloud/server/blob/stable25/lib/public/Files/DavUtil.php is only available from nc-25 😢 , need to find some alternative for support in NC 24 and 23

2023-04-11 08:41 UTC, individual-it requested changes
I think we need more tests where we share with different permissions

2023-04-11 08:41 UTC, individual-it commented on lib/Controller/FilesController.php
> +	// copy of https://github.com/nextcloud/server/blob/cd44ee2053f105f60c668906ed8460605cb1da81/lib/public/Files/DavUtil.php#L58
can we do `$file->getDavPermissions()` for the older versions? as in https://github.com/nextcloud/server/blame/e34f2c4799b271ac1b1c412af4bf2fa1f6279359/apps/dav/lib/BulkUpload/BulkUploadPlugin.php#L100

2023-04-11 08:41 UTC, individual-it commented on tests/acceptance/features/api/getFileinfoByFileIDAPI.feature
> +          "path": {"type": "string", "pattern":"^files/file.txt$"}
I think you are stripping away `files` in https://github.com/nextcloud/integration_openproject/pull/385/files#diff-776f8feca78c8322be8a9c5a0a5c6dcb93dfdd2776045ee36faa1a4c172d645fR234
```suggestion
          "path": {"type": "string", "pattern":"^file.txt$"}
```

2023-04-11 08:41 UTC, individual-it commented on tests/acceptance/features/api/getFileinfoByFileIDAPI.feature
> +          "path": {"type": "string", "pattern":"^files_trashbin\/files\/subfolder.d\\d{10}\/file.txt"}
what to do with that path? Strip away `files_trashbin/files` or leave both?

2023-04-11 09:59 UTC, SwikritiT commented on tests/acceptance/features/api/getFileinfoByFileIDAPI.feature
> +          "path": {"type": "string", "pattern":"^files/file.txt$"}
no the path is `<username>/files/a/b/c>` I'm stripping the `username` so it's `files/a/b/c`

2023-04-11 10:02 UTC, SwikritiT commented on tests/acceptance/features/api/getFileinfoByFileIDAPI.feature
> +          "path": {"type": "string", "pattern":"^files_trashbin\/files\/subfolder.d\\d{10}\/file.txt"}
the internal path starts with `files_trashbin/` so I don't think we need to strip that away.
We can if @Kharonus doesn't need that info.

2023-04-11 10:03 UTC, SwikritiT commented on lib/Controller/FilesController.php
> +	// copy of https://github.com/nextcloud/server/blob/cd44ee2053f105f60c668906ed8460605cb1da81/lib/public/Files/DavUtil.php#L58
I'll try it. Thanks!

2023-04-12 06:21 UTC, SwikritiT commented on lib/Controller/FilesController.php
> +	// copy of https://github.com/nextcloud/server/blob/cd44ee2053f105f60c668906ed8460605cb1da81/lib/public/Files/DavUtil.php#L58
I tried but it didn't work. that function needs the node to be an instance of Sabre Node but it our case it's not

2023-04-12 06:23 UTC, individual-it approved these changes

2023-04-12 09:27 UTC, merged