[OP#47630] Check if free space is a positive value
nextcloud/integration_openproject pull request #390
Opened 2023-04-13 06:05 UTC by SwikritiT

Currently we're checking quota like this

```php
$freeSpace = $folderNode->getFreeSpace();

// this is also true if we try to overwrite
// to overwrite a file we need enough free quota for the new data
// otherwise `putContent()` fails
if ($directUploadFile['size'] > $freeSpace) {
	throw new NotEnoughSpaceException('insufficient quota');
}
```
But since there's a possibility that the function getFreeSpace might return a negative

https://github.com/nextcloud/server/blob/b1abc57c07a61b5a0557395d86c3e31486a96c23/lib/public/Files/FileInfo.php#L52

https://github.com/nextcloud/server/blob/b1abc57c07a61b5a0557395d86c3e31486a96c23/lib/public/Files/FileInfo.php#L57

https://github.com/nextcloud/server/blob/b1abc57c07a61b5a0557395d86c3e31486a96c23/lib/public/Files/FileInfo.php#L62

So treat a negative return as an unlimited space

Related work package: https://community.openproject.org/projects/nextcloud-integration/work_packages/47630/activity?query_id=3504

2023-04-13 07:34 UTC, individual-it requested changes
looks good, can we add unit tests for that case?

2023-04-13 07:58 UTC, SwikritiT commented
> looks good, can we add unit tests for that case?

yes I can add it

2023-04-19 08:17 UTC, individual-it commented on lib/Controller/DirectUploadController.php
> +			], Http::STATUS_BAD_REQUEST);
In what case would that happen?
The response code does indicate that the client has done some mistake.

2023-04-19 08:36 UTC, SwikritiT commented on lib/Controller/DirectUploadController.php
> +			], Http::STATUS_BAD_REQUEST);
This will be thrown when if the put file contents operation fails https://github.com/nextcloud/server/blob/9db33055b208518601ff7b389188c032f8792e39/lib/private/Files/Node/File.php#L71
What would be an appropriate error code for this?

2023-04-20 06:50 UTC, SwikritiT commented on lib/Controller/DirectUploadController.php
> +			], Http::STATUS_BAD_REQUEST);
Removed it so that general exception will catch this as an internal server error.

2023-04-20 09:48 UTC, merged