Dev docker compose
nextcloud/integration_openproject pull request #42
Opened 2022-02-11 09:24 UTC by kiranparajuli589

WIP...

2022-02-14 10:28 UTC, individual-it requested changes

2022-02-14 10:28 UTC, individual-it commented on README.md
> +**Note:** If your host has running apache or nginx, you need to stop it before starting the `docker-compose`.
can't we use an alternative port inside of docker, so it would not affect any server on the host?

2022-02-14 10:28 UTC, individual-it commented on README.md
> +docker exec --user www-data integration_openproject_nc php occ config:system:set allow_local_remote_servers --value 1
can that be done automatically?

2022-02-14 10:28 UTC, individual-it commented on docker-compose.yml
> +      - "6379:6379"
can't we run NC without redis?

2022-02-15 03:34 UTC, individual-it requested changes

2022-02-15 03:34 UTC, individual-it commented on README.md
> +mkdir /dev/custom_apps
this is confusing because there is an actual `/dev` (for devices) folder on linux
```suggestion
mkdir ~/development/custom_apps
```

2022-02-15 03:34 UTC, individual-it commented on README.md
> +git clone https://github.com/nextcloud/integration_openproject.git
```suggestion
cd ~/development/custom_apps
git clone https://github.com/nextcloud/integration_openproject.git
```

2022-02-15 03:34 UTC, individual-it commented on README.md
> +sudo chown www-data custom_apps -R
if you do that, then the developer will not have write access to the app anymore
I would suggest to give it to the group `www-data` and give write access to the group
```suggestion
# provide group ownership of "custom_apps" to the user "www-data"
sudo chgrp www-data ~/development/custom_apps -R
sudo chmod g+w ~/development/custom_apps -r
```

2022-02-15 03:34 UTC, individual-it commented on README.md
> +cd /dev/custom_apps/integration_openproject
```suggestion
cd ~/development/custom_apps/integration_openproject
```

2022-02-15 04:21 UTC, kiranparajuli589 commented on README.md
> +**Note:** If your host has running apache or nginx, you need to stop it before starting the `docker-compose`.
when using the network mode as `host`, we cannot do port mapping

2022-02-15 04:21 UTC, kiranparajuli589 commented on README.md
> +docker exec --user www-data integration_openproject_nc php occ config:system:set allow_local_remote_servers --value 1
NC server should be in installed state, so we've to do it manually

2022-02-15 04:22 UTC, kiranparajuli589 commented on docker-compose.yml
> +      - "6379:6379"
I've tried to run NC without Redis, works fine.
removed this service

2022-02-15 05:55 UTC, individual-it approved these changes

2022-02-15 05:55 UTC, merged