[OP#48445]Update integration script according to project folder setup
nextcloud/integration_openproject pull request #425
Opened 2023-06-09 08:53 UTC by SagarGi

2023-06-13 09:53 UTC, SagarGi commented
This script for now when the `project folder is already setup` then it throws error when the user tries to set up it again. May be we can make it more user or admin friendly by adding checks for project folder setup. Need some Opinion regarding it.
CC @SwikritiT @individual-it

2023-06-22 06:12 UTC, SwikritiT commented on integration_setup.sh
> +								${NC_INTEGRATION_BASE_URL}/project-folder-status \
should we also add `-k` in all of the curl requests? I have open project setup in HTTPS and I cannot use this without `-k` option
```suggestion
	project_folder_setup_response=$(curl -k -s -X GET -u${NC_ADMIN_USERNAME}:${NC_ADMIN_PASSWORD} \
								${NC_INTEGRATION_BASE_URL}/project-folder-status \
```

2023-06-22 06:13 UTC, SwikritiT reviewed
@SagarGi the available env variable section should also be updated at the top to include `SET_PROJECT_FOLDER_SETUP` option

2023-06-23 03:56 UTC, SagarGi commented on lib/Controller/ConfigController.php
>  			}
I have updated this part. In case project folder is already setup then the set up is done with `PATCH`. It means that when the integration is reset and no  there is no oauthClient, the `PATCH` request creates the new oathClient informaton. Needs some opinion regarding this since PATCH request is related to update.

2023-06-23 06:28 UTC, individual-it requested changes

2023-06-23 06:28 UTC, individual-it commented on integration_setup.sh
> +# these two data are set as false when the integration is done without project folder setup
```suggestion
# these two data are set to "false" when the integration is done without project folder setup
```

2023-06-23 06:28 UTC, individual-it commented on integration_setup.sh
> +create_storage_response=$(curl -k -s -X POST -u${OP_ADMIN_USERNAME}:${OP_ADMIN_PASSWORD} \
`-k` should not be used here because it will make the requests insecure

2023-06-23 06:28 UTC, individual-it commented on integration_setup.sh
> +	# we can delete the storage created in openproject. since we have to delete it manually when we run the script for the next time
```suggestion
	# we can delete the storage created in openproject, otherwise it would need to be deleted manually when the script is ran the next time
```

2023-06-23 06:28 UTC, individual-it commented on integration_setup.sh
> +if [[ ${SET_PROJECT_FOLDER_SETUP} == true ]]
```suggestion
if [[ ${SETUP_PROJECT_FOLDER} == true ]]
```

2023-06-23 06:28 UTC, individual-it commented on integration_setup.sh
> +setup_method=POST
this is only used once, so why not calculate the value where ever its used

2023-06-26 04:21 UTC, SagarGi commented on integration_setup.sh
> +setup_method=POST
The value changes from post to patch when project folder setup is already set up and also the endpoint is the same.

2023-06-29 06:00 UTC, individual-it requested changes

2023-06-29 06:00 UTC, individual-it commented on integration_setup.sh
> +		log_info "Above response does not contain nextcloud_client_id or nextcloud_client_secret or openproject_user_app_password"
```suggestion
		log_info "Above response is missing one or more of nextcloud_client_id, nextcloud_client_secret, or openproject_user_app_password"
```

2023-06-29 06:00 UTC, individual-it commented on integration_setup.sh
> +		log_info "Above response does not contain nextcloud_client_id or nextcloud_client_secret"
```suggestion
		log_info "Above response is missing nextcloud_client_id or nextcloud_client_secret"
```

2023-06-29 06:00 UTC, individual-it commented on integration_setup.sh
> +nextcloud_information_response=$(curl -s -X${setup_method} -u${NC_ADMIN_USERNAME}:${NC_ADMIN_PASSWORD} "${NC_INTEGRATION_BASE_URL}/setup" \
```suggestion
if [ "$isProjectFolderAlreadySetup" == "true" ]; then
        setup_method=PATCH
else
        setup_method=POST
fi
nextcloud_information_response=$(curl -s -X${setup_method} -u${NC_ADMIN_USERNAME}:${NC_ADMIN_PASSWORD} "${NC_INTEGRATION_BASE_URL}/setup" \
```

2023-06-29 06:00 UTC, individual-it commented on lib/Controller/ConfigController.php
>  			}
I think that is OK

2023-06-29 06:00 UTC, individual-it commented on integration_setup.sh
> +setup_method=POST
maybe do it like that: https://github.com/nextcloud/integration_openproject/pull/425/files#r1246144808

2023-07-12 03:49 UTC, SwikritiT approved these changes
LGTM

2023-07-12 03:51 UTC, merged