[OP#48445]Update integration script to save user app password
nextcloud/integration_openproject pull request #442
Opened 2023-07-25 06:43 UTC by SagarGi

### Description
This PR updates the integration script to be able to save the user application password to open project.

### Related Work Package:

https://community.openproject.org/projects/nextcloud-integration/work_packages/48445/activity?query_id=3787

2023-07-25 07:09 UTC, phil-davis commented
"Now with this update in script, we can integration either with project folders or with project folders."

In the PR information "project folders" is repeated.

@SagarGi please edit it to say whatever you mean to say.

2023-07-25 07:15 UTC, phil-davis submitted a review, later dismissed

2023-07-25 07:15 UTC, phil-davis commented on integration_setup.sh
> +    if [[ ${app_password_respose_type} == "Error" ]] || [[ ${has_application_password} == null ]]; then
```suggestion
    if [[ ${app_password_response_type} == "Error" ]] || [[ ${has_application_password} == null ]]; then
```

2023-07-25 07:15 UTC, phil-davis commented on integration_setup.sh
> +	# save the application password to Open Project
```suggestion
    # save the application password to Open Project
```

The indent looks wrong here,

2023-07-25 07:15 UTC, phil-davis commented on integration_setup.sh
> +# whenever something goes wrong or error occurs during the setup of whole integration
```suggestion
# whenever something goes wrong or an error occurs during the setup of the whole integration
```

2023-07-25 07:17 UTC, SagarGi commented
> "Now with this update in script, we can integration either with project folders or with project folders."
> 
> In the PR information "project folders" is repeated.
> 
> @SagarGi please edit it to say whatever you mean to say.

Opps !! sorry its `with` or `without`. I missed `out` in the second one. Thnanks !!

2023-07-25 08:52 UTC, SwikritiT commented on integration_setup.sh
> +# we can delete the storage created in openproject, otherwise it would need to be deleted manually when the script is ran the next time
```suggestion
# if something goes wrong or an error occurs during the setup of the whole integration
# we can delete the storage created in OpenProject, otherwise it would need to be deleted manually when the script is run the next time
```

2023-07-25 08:53 UTC, SwikritiT commented on integration_setup.sh
> +# save the application password to Open Project
```suggestion
# save the application password to OpenProject
```

2023-07-25 08:53 UTC, SwikritiT commented on integration_setup.sh
> +    log_info "Saving 'OpenProject' user application password to Open Project...."
```suggestion
    log_info "Saving 'OpenProject' user application password to OpenProject...."
```

2023-07-25 09:52 UTC, SwikritiT approved these changes
LGTM

2023-07-25 10:42 UTC, SwikritiT requested changes
This also needs changing. I had a problem here

2023-07-25 10:42 UTC, SwikritiT commented on integration_setup.sh
>  if [ ${SETUP_PROJECT_FOLDER} == true ]; then
```suggestion
if [[ ${SETUP_PROJECT_FOLDER} == true ]]; then
```

2023-07-26 04:06 UTC, SagarGi commented on integration_setup.sh
>  if [ ${SETUP_PROJECT_FOLDER} == true ]; then
I have added it to all if conditions.

2023-07-26 04:06 UTC, SwikritiT approved these changes

2023-07-26 04:17 UTC, phil-davis approved these changes

2023-07-26 08:11 UTC, merged