support multiple files to a work-package
nextcloud/integration_openproject pull request #444
Opened 2023-07-26 10:37 UTC by SagarGi

2023-08-29 04:30 UTC, individual-it requested changes

2023-08-29 04:30 UTC, individual-it commented on lib/Service/OpenProjectAPIService.php
> +		$fileIfnos = $values['fileinfo'];
```suggestion
		$fileInfos = $values['fileinfo'];
```

2023-08-29 04:30 UTC, individual-it commented on src/components/tab/SearchInput.vue
> +				successMessage = 'Work package linked successfully for selected files!'
translation missing

2023-08-29 04:30 UTC, individual-it commented on src/components/tab/SearchInput.vue
> +				successMessage = 'Work package linked successfully!'
translation missing

2023-08-29 04:30 UTC, individual-it commented on src/components/tab/SearchInput.vue
> +		async processWorkPackages(workPackages, fileId = null) {
in which case would fileId be null?

2023-08-29 04:30 UTC, individual-it commented on src/components/tab/SearchInput.vue
> +							if (this.isSearchFrom === SEARCHFROM.PROJECT_TAB) {
IMO this check should be done in the function that calls `processWorkPackages`

2023-08-29 04:30 UTC, individual-it commented on src/components/tab/SearchInput.vue
> +								// for now multiple link of files to a workpackage, fileId is not sent for filtration process
so why then even call `getAdditionalMetaData` at all?

2023-08-29 04:30 UTC, individual-it commented on src/views/LinkMultipleFilesModal.vue
> +		async fetchWorkpackagesForMultipleFileLink(fileId) {
I thought we don't have to check if a file is already linked

2023-08-29 04:30 UTC, individual-it commented on webpack.js
> +	filesplugin: { import: path.join(__dirname, 'src', 'filesplugin.js'), filename: appId + '-filesplugin.js' },
```suggestion
	filesPlugin: { import: path.join(__dirname, 'src', 'filesPlugin.js'), filename: appId + '-filesPlugin.js' },
```

2023-08-29 04:30 UTC, individual-it commented on lib/Service/OpenProjectAPIService.php
> +		array $values,
this will be so confusing to know what "values" needed to be send here, same in `linkWorkPackageToFile`
we should 
- well document what `$values` expects
- maybe not expecting an array but an object, that will reduce the chances for errors
- check the content of the passed object/array (my guess is, that if we now don't supply the correct values in `$values` the whole function will fall over with `undefined index`)
- have tests, that check if something is wrong with the given parameters

2023-08-29 08:27 UTC, SagarGi commented on src/components/tab/SearchInput.vue
> +				successMessage = 'Work package linked successfully!'
will be translated in this function `showSuccess(
					t('integration_openproject', successMessage)
				)`

2023-08-29 08:57 UTC, SagarGi commented on src/components/tab/SearchInput.vue
> +		async processWorkPackages(workPackages, fileId = null) {
in case we search from the multiple link file modal or also from the link picker we do not need the filter the search result by id. in project tab it was done because of some inconsistency in the UI. But is different in this case.

2023-08-29 09:02 UTC, SagarGi commented on src/views/LinkMultipleFilesModal.vue
> +		async fetchWorkpackagesForMultipleFileLink(fileId) {
we check for only single file if the file is already linked to a work package now but not all.

2023-08-29 09:02 UTC, individual-it commented on src/components/tab/SearchInput.vue
> +				successMessage = 'Work package linked successfully!'
That does not work, because the translation tool does not run the code and so it has no idea about the content of `successMessage`. You have to use `t()` where ever the literal string is supplied

2023-08-29 09:18 UTC, SagarGi commented on src/components/tab/SearchInput.vue
> +				successMessage = 'Work package linked successfully!'
oh ok sure.

2023-08-30 11:02 UTC, SagarGi commented on lib/Service/OpenProjectAPIService.php
> +		array $values,
Added unit test with validation.

2023-08-30 11:04 UTC, SagarGi commented on src/views/LinkMultipleFilesModal.vue
> +		async fetchWorkpackagesForMultipleFileLink(fileId) {
For project tab fetch there are some extra checks that we do not require in the fetch from the link modal. So The function is a bit different. May be its better to have separate function for both.

2023-08-31 05:45 UTC, SwikritiT commented on lib/Controller/OpenProjectAPIController.php
>  			return new DataResponse($e->getMessage(), Http::STATUS_BAD_REQUEST);
Maybe we can do it like this since we're throwing the same status code?
```suggestion
		} catch (OpenprojectErrorException | InvalidArgumentException $e) {
			return new DataResponse($e->getMessage(), Http::STATUS_BAD_REQUEST);
```

2023-08-31 05:46 UTC, SwikritiT commented on lib/Controller/OpenProjectAPIController.php
>  		} catch (Exception $e) {
While you're at it can you refactor this to something like this? seems like we missed the `\`
```suggestion
		} catch (\Exception $e) {
```

2023-08-31 05:52 UTC, SwikritiT commented on lib/Service/OpenProjectAPIService.php
> +			}
can't we calculate them in a single `if` statement and should these be `&&` operations?
```suggestion
			if (!isset($fileInfo['id']) && !isset($fileInfo['name']) !is_int($fileInfo['id']) && $fileInfo['name'] === '' |&& !is_string($fileInfo['name'])) {
				throw new InvalidArgumentException('invalid data');
			}
```

2023-08-31 05:57 UTC, SwikritiT commented on src/components/tab/EmptyContent.vue
> +		isLinkMultipleModal: {
How about this?
```suggestion
		isMultipleWorkpackageLinking: {
```

2023-08-31 06:02 UTC, SwikritiT commented on src/components/tab/SearchInput.vue
> +				// we do not need to provide file id incase of searching through link multiple files to workpakcage and through linkpicker
```suggestion
				// we do not need to provide a file id incase of searching through link multiple files to work package and through smart picker
```

2023-08-31 06:21 UTC, SwikritiT reviewed
some suggestions

2023-08-31 06:21 UTC, SwikritiT commented on src/components/tab/SearchInput.vue
> +			// since we can link multiple files now we send file information required in array (whether its only one value or multiple)
```suggestion
			// since we can link multiple files now we send file information required in an array (whether it's only one value or multiple)
```

2023-08-31 06:21 UTC, SwikritiT commented on src/components/tab/SearchInput.vue
> +				successMessage = t('integration_openproject', 'Work package linked successfully!')
I see in Figma the toast message is something like this, maybe we didn't follow through the message the previous time. Can we change it, this seems more accurate than what we are displaying right now. 
```suggestion
				successMessage = t('integration_openproject', 'Link to work package created successfully!')
```

2023-08-31 06:21 UTC, SwikritiT commented on src/components/tab/SearchInput.vue
> +				successMessage = t('integration_openproject', 'Work package linked successfully for selected files!')
```suggestion
				successMessage = t('integration_openproject', 'Links to work package created successfully for selected files!')
```

2023-08-31 06:21 UTC, SwikritiT commented on src/filesPlugin.js
> +const modalId = 'exampleModal'
maybe something like this?
```suggestion
const modalId = 'multipleFileLinkModal'
```

2023-08-31 06:21 UTC, SwikritiT commented on src/utils.js
> +	LINK_MULTIPLE_MODAL: 'link-multiple-modal',
Maybe something like this? Right now it seems like we're linking multiple modals
```suggestion
	LINK_MULTIPLE_FILES_MODAL: 'link-multiple-files-modal',
```

2023-08-31 06:21 UTC, SwikritiT commented on src/utils.js
> +export const SEARCHFROM = {
How about something like this?
```suggestion
export const SEARCH_WORKPACKAGES_FROM = {
```

2023-08-31 06:21 UTC, SwikritiT commented on src/views/LinkMultipleFilesModal.vue
> +			isSearchFrom: SEARCHFROM.LINK_MULTIPLE_MODAL,
```suggestion
			isSearchWorkpackageFrom: SEARCHFROM.LINK_MULTIPLE_MODAL,
```

2023-08-31 06:45 UTC, SwikritiT commented
@SagarGi I made about a `100` files 

```bash
#!/usr/bin/env bash

for (( c=1; c<=110; c++ ))
do 
    folderName="test$c"
    echo ${folderName}
    # curl -X MKCOL -u admin:admin http://localhost/nextcloud/stable26/remote.php/dav/files/admin/${folderName}
    curl -X PUT -u admin:admin http://localhost/nextcloud/stable26/remote.php/webdav/${folderName}.txt -d "hello world"
done
```

And tried to link it to a work package, but it gives me `400` and none of the files are linked. This can be a bug from `openproject` side as well can we make sure that this is not a problem on our end?

2023-08-31 08:59 UTC, SagarGi commented
> @SagarGi I made about a `100` files
> 
> ```shell
> #!/usr/bin/env bash
> 
> for (( c=1; c<=110; c++ ))
> do 
>     folderName="test$c"
>     echo ${folderName}
>     # curl -X MKCOL -u admin:admin http://localhost/nextcloud/stable26/remote.php/dav/files/admin/${folderName}
>     curl -X PUT -u admin:admin http://localhost/nextcloud/stable26/remote.php/webdav/${folderName}.txt -d "hello world"
> done
> ```
> 
> And tried to link them all to a work package, but it gives me `400`, and none of the files are linked. This can be a bug from `openproject` side as well but can we make sure if it is a problem on our end?




![toMany](https://github.com/nextcloud/integration_openproject/assets/46086950/d2ddd206-762e-4a3d-9dd0-c44a3c480ffb)


Its the error from the openproject with message `To Many`. May be a clear information error might be necessary in this case. Can also be done in another PR

2023-08-31 09:29 UTC, SwikritiT commented
> > @SagarGi I made about a `100` files
> > ```shell
> > #!/usr/bin/env bash
> > 
> > for (( c=1; c<=110; c++ ))
> > do 
> >     folderName="test$c"
> >     echo ${folderName}
> >     # curl -X MKCOL -u admin:admin http://localhost/nextcloud/stable26/remote.php/dav/files/admin/${folderName}
> >     curl -X PUT -u admin:admin http://localhost/nextcloud/stable26/remote.php/webdav/${folderName}.txt -d "hello world"
> > done
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And tried to link them all to a work package, but it gives me `400`, and none of the files are linked. This can be a bug from `openproject` side as well but can we make sure if it is a problem on our end?
> 
> @SwikritiT ![toMany](https://user-images.githubusercontent.com/46086950/264593065-d2ddd206-762e-4a3d-9dd0-c44a3c480ffb.png)
> 
> Its the error from the openproject with message `To Many`. May be a clear information error might be necessary in this case. Can also be done in another PR

the limit seems to be 20 in a single request, we can show some error message if the limit is crossed maybe even from the front end but yes can be part of other PR

2023-09-01 04:21 UTC, SwikritiT commented on tests/jest/components/tab/SearchInput.spec.js
> -					{ headers: { 'Content-Type': 'application/x-www-form-urlencoded' } }
maybe we can check `Content-type: application/json` now?

2023-09-01 04:22 UTC, SwikritiT commented on tests/jest/components/tab/SearchInput.spec.js
> +				it('should show an error when linking failed', async () => {
```suggestion
				it('should show an error when linking fails', async () => {
```

2023-09-01 04:25 UTC, SwikritiT commented on tests/jest/components/tab/SearchInput.spec.js
> +			describe('click on a workpackage option', () => {
```suggestion
			describe('select a work package for linking', () => {
```

2023-09-01 04:27 UTC, SwikritiT commented on tests/jest/components/tab/SearchInput.spec.js
> +				describe('click on a workpackage option', () => {
```suggestion
				describe('select a work package for linking', () => {
```

2023-09-01 04:27 UTC, SwikritiT commented on tests/jest/components/tab/SearchInput.spec.js
> +						const err = new Error()
```suggestion
					it('should show an error when linking fails', async () => {
						const err = new Error()
```

2023-09-05 08:47 UTC, individual-it requested changes

2023-09-05 08:47 UTC, individual-it commented on src/components/tab/SearchInput.vue
> +		isSearchWorkpackageFrom: {
```suggestion
		searchSource: {
```

2023-09-05 09:08 UTC, individual-it commented
When there is no connection yet to OP the screen shows:
![grafik](https://github.com/nextcloud/integration_openproject/assets/2425577/0627c7c1-2b4b-4686-8dc2-b3932c8fda30)

In other places we show
![grafik](https://github.com/nextcloud/integration_openproject/assets/2425577/0d65ea54-3482-4529-9667-b537116dd284)

2023-09-08 09:14 UTC, SagarGi commented
@SwikritiT @individual-it The linking of files more than 20 in chunks can be done in another PR since this PR seems big itself. So this can be reviewed again.

2023-09-11 04:17 UTC, SwikritiT reviewed
tested locally works for me

2023-09-12 03:55 UTC, individual-it approved these changes

2023-09-12 04:15 UTC, SwikritiT approved these changes

2023-09-12 06:17 UTC, merged