[OP#49295]Change NCMultiselect to NcSelect
nextcloud/integration_openproject pull request #447
Opened 2023-07-28 08:38 UTC by SagarGi

2023-07-31 09:02 UTC, SagarGi commented on tests/jest/components/tab/SearchInput.spec.js
> +				await inputField.setValue(' ')
for the search result to set in the `dropdown` it needs to be opened. Setting the value with empty value we can get the dropdown open which gives the workpackages in the search result.

2023-07-31 09:06 UTC, SagarGi commented on tests/jest/components/tab/SearchInput.spec.js
> +				await inputField.setValue(' ')
For the search data to be visible in the dropdown. The dropdown needs to be opened. So this helps to open it. So after that we can check the content of the dropdown based on the search result.

2023-08-01 07:43 UTC, SwikritiT approved these changes
LGTM

2023-08-01 07:45 UTC, SwikritiT commented on tests/jest/components/tab/SearchInput.spec.js
> +				const multiSelectContent = wrapper.find(workpackagesListSelector)
It's not multiseletc anymore so can we change the name to something more appropriate 
```suggestion
				const ncSelectContent = wrapper.find(workpackagesListSelector)
```

2023-08-01 07:47 UTC, SwikritiT requested changes

2023-08-01 07:47 UTC, SwikritiT commented on tests/jest/components/tab/SearchInput.spec.js
> +				const multiSelectContent = wrapper.find(workpackagesListSelector)
It's not multiseletc anymore so can we change the name to something more appropriate 
```suggestion
				const ncSelectContent = wrapper.find(workpackagesListSelector)
```

2023-08-01 07:47 UTC, SwikritiT commented on tests/jest/components/tab/__snapshots__/SearchInput.spec.js.snap
> +exports[`SearchInput.vue work packages multiselect search list should not be displayed if the search results is empty 1`] = `<ul id="vs10__listbox" role="listbox" style="display: none; visibility: hi
We need to find the occurance of the word multiselect and replace/remove it. This probably need the chane in the title of the unit test
```suggestion
exports[`SearchInput.vue work packages  search list should not be displayed if the search results is empty 1`] = `<ul id="vs10__listbox" role="listbox" style="display: none; visibility: hidden;"></ul>`;
```

2023-08-01 08:43 UTC, SwikritiT approved these changes
LGTM

2023-08-01 09:34 UTC, merged