[WP#40971]Link the multiple selected files in chunks
nextcloud/integration_openproject pull request #496
Opened 2023-09-12 11:10 UTC by SagarGi

### Description
The `OpenProject` server only supports the multiple selected up to only `20` files at once to link to a workpackage. So this PR makes changes in the request to make it support to link the multiple selected files more than `20` in chunks to link to a single workpackage.

### Part of:
https://community.openproject.org/projects/nextcloud-integration/work_packages/40971/activity

2023-10-04 05:23 UTC, SagarGi commented
@wielinde @SwikritiT @individual-it I have made some UI changes for the progress of linking. Please share your opinion towards it if something needs to be changed.

## In Prgoress
![chunkProgress](https://github.com/nextcloud/integration_openproject/assets/46086950/fbeb4f81-fb29-4baf-aa2c-87d8da3b0e35)

## Link Remaining

![errorLinking](https://github.com/nextcloud/integration_openproject/assets/46086950/7ee1afd2-fb22-41fc-b81b-b95bef8f9fc5)

2023-10-12 10:22 UTC, individual-it requested changes

2023-10-12 10:22 UTC, individual-it commented on src/utils/workpackageHelper.js
> +		return totalFiles.length
will that not always be the same as `chunkedFilesInformations.length` ?

2023-10-12 10:22 UTC, individual-it commented on src/views/LinkMultipleFilesModal.vue
> +		getChunkedInformations(data) {
isn't that rather a setter?

2023-10-13 03:30 UTC, SagarGi commented on src/utils/workpackageHelper.js
> +		return totalFiles.length
`chunkedFilesInformations` contains array of array as `[[20 filesInfo], [20 filesInfo], [15 filesInfo]]`. This function get the count of those files.

2023-10-17 04:25 UTC, individual-it requested changes

2023-10-17 04:25 UTC, individual-it commented on src/components/tab/SearchInput.vue
> +					await workpackageHelper.linkMultipleFilesToWorkPackageWithChunking(chunkedFilesInformations, selectedOption, false, this)
these both functions always go together and actually depend on each other, so what about calling `chunkMultipleSelectedFilesInformation` from within `linkMultipleFilesToWorkPackageWithChunking`?

2023-10-17 04:25 UTC, individual-it commented on src/utils/workpackageHelper.js
> +		return totalFiles.length
OK, then I would suggest not to create a new array just for counting, but count inside of the loop

2023-10-17 04:25 UTC, individual-it commented on src/utils/workpackageHelper.js
> +			isChunkingError: false,
is this an error about chunking or when the transfer did not happen?
```suggestion
			error: false,
```

2023-10-17 04:25 UTC, individual-it commented on src/views/LinkMultipleFilesModal.vue
> +									{{ t('integration_openproject', `Files failed to linked: ${getTotalNoOfFilesNotLinkedInChunking}`) }}
```suggestion
									{{ t('integration_openproject', `Files failed to be linked: ${getTotalNoOfFilesNotLinkedInChunking}`) }}
```

2023-10-17 04:25 UTC, individual-it commented on src/views/LinkMultipleFilesModal.vue
> +		getChunkStateInChunking() {
```suggestion
		getError() {
```

2023-10-17 04:25 UTC, individual-it commented on src/views/LinkMultipleFilesModal.vue
> +		canCloseModal() {
```suggestion
		isError() {
```

2023-10-17 04:25 UTC, individual-it commented on tests/jest/components/tab/SearchInput.spec.js
> +						It means the file will get hchunked as [20, 20, 25]
```suggestion
						It means the file will get chunked as [20, 20, 15]
```

2023-10-17 04:25 UTC, individual-it commented on tests/jest/components/tab/SearchInput.spec.js
> +						it('should emit event "get-chunked-informations" for 3 times', async () => {
isn't that pretty much the same as the test above?

2023-10-17 04:25 UTC, individual-it commented on tests/jest/components/tab/SearchInput.spec.js
> +						it('should emit event "get-chunked-informations" with data', async () => {
could this be integrated into above test?

2023-10-17 04:25 UTC, individual-it commented on tests/jest/views/LinkMultipleFilesModal.spec.js
> +			it('should make chunkng information empty', async () => {
```suggestion
			it('should clean chunking information', async () => {
```

2023-10-17 04:25 UTC, individual-it commented on tests/jest/views/LinkMultipleFilesModal.spec.js
> +			it('should make chunkng information empty when not empty', async () => {
can be integrated into above one with `it.each`

2023-10-17 11:08 UTC, SagarGi commented on src/utils/workpackageHelper.js
> +			isChunkingError: false,
yes it is basically error key when there is some error while linking with chunk. But may be `error` is enough.

2023-10-17 11:16 UTC, SagarGi commented on tests/jest/components/tab/SearchInput.spec.js
> +						it('should emit event "get-chunked-informations" for 3 times', async () => {
yes but this checks for the emit event to the parent component

2023-10-18 03:58 UTC, SagarGi commented on tests/jest/components/tab/SearchInput.spec.js
> +						it('should emit event "get-chunked-informations" with data', async () => {
it is the case of successful link with chunk. I have adjusted the test case description instead.

2023-10-18 04:29 UTC, individual-it approved these changes

2023-10-18 08:41 UTC, SwikritiT requested changes

2023-10-18 08:41 UTC, SwikritiT commented on src/utils/workpackageHelper.js
> +		// this function chunks 20 files information in an array and returns array of it
Can we also add a little bit of context on why exactly  `20` so that we are clear in future as well?
```suggestion
		// this function chunks 20 files of information in an array and returns an array of it, `20` because Openproject api only allows linking of 20 files per request
```

2023-10-18 08:41 UTC, SwikritiT commented on src/utils/workpackageHelper.js
> +	*/
```suggestion
		// Here the chunkedFilesInformation is the array that contains the array of chunked files information in 20
```

2023-10-18 08:41 UTC, SwikritiT commented on src/views/LinkMultipleFilesModal.vue
> +								<AlertCircleOutline fill-color="#e9322d" :size="70" />
Can we use the variable of the colours provided by the nextcloud here as those colours are handeled by NC itself in different themes?
```suggestion
								<AlertCircleOutline fill-color="--var(red-color-provided-by-nextcloud)" :size="70" />
```

2023-10-18 08:49 UTC, SwikritiT commented on tests/jest/components/tab/SearchInput.spec.js
> +								// here already linked package is empty when the file selected files is more than 1
```suggestion
								// here already linked work package package is empty when the selected files is more than 1
```

2023-10-18 08:49 UTC, SwikritiT commented on tests/jest/components/tab/SearchInput.spec.js
> +						It means the file will get chunked as [20, 20, 15]
```suggestion
						For the test of linking multiple files more than 20.
						This test scenario creates a file information of 55 which is used through the whole test for the link with chunking.
						It means the file will get chunked as [20, 20, 15].
```

2023-10-18 08:55 UTC, SwikritiT commented
Note that in nextcloud master i.e NC-28 seems like the design has changed and the multi-linking option is nowhere to be seen.

![Screenshot from 2023-10-18 14-23-23](https://github.com/nextcloud/integration_openproject/assets/41103328/651c331c-07f0-4b21-ad57-6ce0d8ad8d5d)




 If we want this feature for 2.5 and if https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule this is correct nextcloud 28 is set to be released around December so we need to make it compatible with nextcloud 28 as well.

2023-11-03 06:19 UTC, merged