[WP#50135]Fix the delete files in shared link
nextcloud/integration_openproject pull request #507
Opened 2023-10-17 04:49 UTC by SagarGi

### Description
Fixes : https://community.openproject.org/projects/openproject/work_packages/50135/activity

2023-10-17 05:09 UTC, SwikritiT commented on lib/Listener/BeforeNodeInsideOpenProjectGroupfilderChangedListener.php
> +			return;
Can we also add a comment here on why this is needed?

2023-10-17 09:22 UTC, SwikritiT requested changes
Just figured out that with these changes if the OpenProject group folder is shared through public link then the nodes inside it can be deleted.

2023-10-18 03:33 UTC, SwikritiT approved these changes

2023-10-18 04:11 UTC, individual-it approved these changes

2023-10-18 04:11 UTC, merged