[WP#50326]Added trailing slash for folder for files info endpoint
nextcloud/integration_openproject pull request #509
Opened 2023-10-18 06:07 UTC by SagarGi

### Description
This PR adds the trailing slash for the folder path in the response for the file(s)info endopint.

### Relared WP
https://community.openproject.org/projects/nextcloud-integration/work_packages/50326/activity

2023-10-18 07:13 UTC, SwikritiT commented on tests/acceptance/features/api/getFileinfoByFileIDAPI.feature
> +      "path": {"type": "string", "pattern":"^files/groupFolder/$"}
```suggestion
      "path": {"type": "string", "pattern":"^files\/groupFolder\/$"}
```

2023-10-18 07:13 UTC, SwikritiT commented on tests/acceptance/features/api/getFileinfoByFileIDAPI.feature
> +      "path": {"type": "string", "pattern":"^files\/folder/$"}
```suggestion
      "path": {"type": "string", "pattern":"^files\/folder\/$"}
```

2023-10-18 07:13 UTC, SwikritiT commented on tests/acceptance/features/api/getFileinfoByFileIDAPI.feature
> +      "path": {"type": "string", "pattern":"^files\/folder/$"}
```suggestion
      "path": {"type": "string", "pattern":"^files\/folder\/$"}
```

2023-10-18 07:13 UTC, SwikritiT commented on tests/acceptance/features/api/getFileinfoByFileIDAPI.feature
> +      "path": {"type": "string", "pattern":"^files\/folder/$"}
```suggestion
      "path": {"type": "string", "pattern":"^files\/folder\/$"}
```

2023-10-18 09:04 UTC, individual-it requested changes

2023-10-18 09:04 UTC, individual-it commented on tests/lib/Controller/FilesControllerTest.php
> +				'files/test/'
the expectation here should be `files/`

2023-10-18 10:39 UTC, individual-it approved these changes

2023-10-19 10:20 UTC, SwikritiT approved these changes

2023-10-19 10:21 UTC, merged