[#50658] Connect to OpenProject Button in Smart Picker
nextcloud/integration_openproject pull request #516
Opened 2023-11-03 11:06 UTC by SwikritiT

https://community.openproject.org/work_packages/50658

2023-12-05 10:13 UTC, SwikritiT commented on src/views/WorkPackagePickerElement.vue
> +			<NcLoadingIcon v-if="isLoading" class="loading-spinner" :size="50" />
I changed the size to 100 can you check again ?

2023-12-06 06:12 UTC, SagarGi commented on src/views/WorkPackagePickerElement.vue
> +			<NcLoadingIcon v-if="isLoading" class="loading-spinner" :size="50" />
size 90 LGTM after i checked.

2023-12-06 09:31 UTC, SagarGi submitted a review, later dismissed
LGTM :+1:

2023-12-06 09:58 UTC, SagarGi requested changes
![unexpectedError](https://github.com/nextcloud/integration_openproject/assets/46086950/42b7e77a-0943-4ce6-ba86-ad707fb4d5d7)
I got this after cutting openproject after successful OAUTH connection.

2023-12-06 11:12 UTC, SwikritiT commented
> ![unexpectedError](https://private-user-images.githubusercontent.com/46086950/288366280-42b7e77a-0943-4ce6-ba86-ad707fb4d5d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NjE0NTcsIm5iZiI6MTcwMTg2MTE1NywicGF0aCI6Ii80NjA4Njk1MC8yODgzNjYyODAtNDJiN2U3N2EtMDk0My00Y2U2LWJhODYtYWQ3MDdmYjRkNWQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDExMTIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2ZDhhNjZiOGI1ZmNiNjYwMTQ5N2VjZGY5ZjYxMjM4NWYxYjIyYTU5Njk1ODM2OTJlYzMxMzJhY2UwNzVhNTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ldU8YQJmuWEclZzTovQEm2qVSRQ91N_mhfECZvPfU_c) I got this cutting openproject after successful OAUTH connection.

fixed it can you check again?

2023-12-06 11:32 UTC, SagarGi approved these changes
LGTM :+1:

2023-12-07 07:20 UTC, merged