Improve debuggability and minor fixes
nextcloud/integration_openproject pull request #519
Opened 2023-11-20 10:26 UTC by rossnet

I use this script to bootstrap the OpenProject - Nextcloud connection within a K8s deployment containing both instances. The applied changes help a lot when i comes to debugging the actual setup sequence.

2023-11-21 06:46 UTC, SwikritiT commented
@SagarGi @individual-it I think we can review and merge this if everything is working. Since this is from fork CI won't pass and the changes shouldn't affect CI either.

2023-11-21 08:08 UTC, individual-it approved these changes

2023-11-21 09:59 UTC, SagarGi approved these changes
Checked it locally working fine. LGTM :+1:

2023-11-23 11:01 UTC, SagarGi requested changes
Fails when running the script with setting up the group folders through it.

2023-12-07 10:12 UTC, closed without merging