Update readme for `release preparation` and `publish release`
nextcloud/integration_openproject pull request #549
Opened 2023-12-14 06:41 UTC by SagarGi

### Description
This PR updates `README.md` documentation for the `release preparation` and `publish release`

2023-12-14 07:01 UTC, SwikritiT commented on README.md
> +4. Also, allow transifex to write on release branch i.e. update in `.tx/backport`
```suggestion
4. Allow transifex to write on release branch i.e. update in `.tx/backport`
```

2023-12-14 10:56 UTC, SwikritiT approved these changes

2023-12-15 04:09 UTC, SwikritiT requested changes
can we also add a point to update the description of app like this https://github.com/nextcloud/integration_openproject/pull/227/files 
we forgot it this time

2023-12-20 04:00 UTC, SagarGi commented
> can we also add a point to update the description of app like this https://github.com/nextcloud/integration_openproject/pull/227/files we forgot it this time

done!

2023-12-20 04:04 UTC, SwikritiT approved these changes
LGTM

2023-12-20 04:11 UTC, individual-it requested changes

2023-12-20 04:11 UTC, individual-it commented on README.md
> +3. Protect that new branch the same way as `master`
no need to do that anymore the rule is set to `release/*` so this step can be deleted

2023-12-20 04:15 UTC, individual-it requested changes

2023-12-20 04:15 UTC, individual-it commented on README.md
> +1. Incase of any new feature added in integration app, update the feature description in `README.md` and `appinfo/info.xml`.
```suggestion
1. In case any new feature were added, update the feature description in `README.md` and `appinfo/info.xml`.
```

2023-12-20 04:15 UTC, individual-it commented on README.md
> +5. Allow transifex to write on release branch i.e. update in `.tx/backport`
the branch for nightly builds needs to be adjusted

2023-12-21 03:44 UTC, individual-it approved these changes

2023-12-21 04:09 UTC, merged