[OP#41124] Display loading icon while fetching workpackages
nextcloud/integration_openproject pull request #55
Opened 2022-02-21 11:49 UTC by SwikritiT

part of OP#41124: This PR adds a loading icon when fetching work packages

2022-02-21 11:56 UTC, SwikritiT commented on src/components/tab/SearchInput.vue
> +			</template>
@eneiluj The messages in this slot are not being displayed in the UI. The default one `No result` is displayed but if I define a custom message it's not displayed. Am I doing something wrong or that slot can't be used?

2022-02-21 12:06 UTC, kiranparajuli589 commented on src/components/tab/SearchInput.vue
> +			</template>
the `#noResult` slot is actually from `vue-multiselect` library and is already implemented inside the `Multiselect.vue` so I think, we cannot further use it as a slot here.

2022-02-22 04:10 UTC, individual-it commented on src/components/tab/SearchInput.vue
>  		async getWorkPackageColorAttributes(path, id) {
this whole function seems not to be covered well with tests, maybe this PR is a good option to add more

2022-02-23 03:38 UTC, individual-it requested changes

2022-02-23 03:38 UTC, individual-it commented on tests/jest/components/tab/SearchInput.spec.js
> +			await textInput.setValue('organ')
should not be needed if you use the `setData`

2022-02-23 03:38 UTC, individual-it commented on src/components/tab/SearchInput.vue
> +				this.loading = true
why do we need this new variable and not keep on using `this.state = 'loading'`

2022-02-23 03:54 UTC, SwikritiT commented on src/components/tab/SearchInput.vue
> +				this.loading = true
The `: loading` prop of the multi-select uses a boolean value so that I defined the new variable loading that is set true or false

2022-02-23 11:34 UTC, kiranparajuli589 commented on tests/jest/components/tab/SearchInput.spec.js
> +					},
`data` is also redundant here imo

2022-02-24 03:04 UTC, SwikritiT commented on tests/jest/components/tab/SearchInput.spec.js
> +					},
it gives me the error `  TypeError: Cannot read property 'color' of undefined `, if I don't define data

2022-02-24 06:55 UTC, individual-it commented on tests/jest/components/tab/SearchInput.spec.js
> +					},
can be done in an other PR, but I would suggest to improve `getWorkPackageColorAttributes`
it checks `if (response.status === 200) {` and the assumes that the response has a color attribute, but what if not?
Should be something like `if (response.status === 200 && response.data.color !== undefined) {`

2022-02-24 07:02 UTC, individual-it approved these changes

2022-02-24 07:03 UTC, merged