Added TOS app enabled and set TOS for OP user
nextcloud/integration_openproject pull request #552
Opened 2023-12-22 11:24 UTC by SagarGi

2024-01-08 11:53 UTC, dominic-braeunlein commented on lib/Service/OpenProjectAPIService.php
> +	public function signTOSForUserOPenProject(): void {
```suggestion
	public function signTOSForUserOpenProject(): void {
```

2024-01-10 21:57 UTC, dominic-braeunlein commented on lib/Service/OpenProjectAPIService.php
> +			}
Hi @SagarGi, Wieland and I were talking about how the code handles the signing of the TOS.

We think it would be better to only sign TOS when there are unsigned TOS instead of removing and adding them all.
This would help for another idea we have, which is signing TOS when the user opens the admin settings and showing a popup in case new TOS were signed.

I would like to give you some more info when you are back. Just ping me and we can talk more about it.

2024-01-11 05:18 UTC, SagarGi commented on lib/Service/OpenProjectAPIService.php
> +			}
@dominic-braeunlein yes sure. Thanks!

2024-01-22 10:53 UTC, SagarGi commented
A PR is created to repository `terms_of_services` https://github.com/nextcloud/terms_of_service/pull/895 in order to add an event when new `Terms of service` created so that we can listen to that event to sign newly created `Terms of service`.

2024-02-08 10:50 UTC, individual-it requested changes
- please be consistent with your naming (variable, functions, etc.)
- avoid abbreviation if they are not super common
- declare functions private, that can be made private

2024-02-08 10:50 UTC, individual-it commented on lib/Listener/TOSEventListener.php
> +			// Put Logger
fix the TODO

2024-02-08 10:50 UTC, individual-it commented on lib/Listener/TOSEventListener.php
> +use OCP\DB\Exception;
do we really want to catch the DB Exception?

2024-02-08 10:50 UTC, individual-it commented on lib/Listener/TOSEventListener.php
> +		} catch (Exception $e) {
to make sure its not the DB or any other random exception use
```suggestion
		} catch (\Exception $e) {
```

2024-02-08 10:50 UTC, individual-it commented on lib/Service/OpenProjectAPIService.php
> +
one empty line should be enough

2024-02-08 10:50 UTC, individual-it commented on lib/Service/OpenProjectAPIService.php
> +	public function getAllTermsOfServicesAvailable(): array {
```suggestion
	public function getAllTermsOfServiceAvailable(): array {
```

2024-02-08 10:50 UTC, individual-it commented on lib/Service/OpenProjectAPIService.php
> +	public function getAllTermsOfServicesSignedByUserOpenProject(): array {
```suggestion
	public function getAllTermsOfServiceSignedByUserOpenProject(): array {
```

2024-02-08 10:50 UTC, individual-it commented on lib/Service/OpenProjectAPIService.php
> +	public function getAllTermsOfServicesAvailable(): array {
can be made private

2024-02-08 10:50 UTC, individual-it commented on lib/Service/OpenProjectAPIService.php
> +	public function getAllTermsOfServicesSignedByUserOpenProject(): array {
function can be made private

2024-02-08 10:50 UTC, individual-it commented on lib/Service/OpenProjectAPIService.php
> +	public function isALlTermsOfServiceSignedForUserOpenProject(): bool {
```suggestion
	public function isAllTermsOfServiceSignedForUserOpenProject(): bool {
```

2024-02-08 10:50 UTC, individual-it commented on lib/Service/OpenProjectAPIService.php
> +	public function signTOSForUserOpenProject(): void {
```suggestion
	public function signTermsOfServiceForUserOpenProject(): void {
```

2024-02-08 10:50 UTC, individual-it commented on lib/Service/OpenProjectAPIService.php
> +			$term_id = $term->id;
```suggestion
			$termId = $term->id;
```

2024-02-08 10:50 UTC, individual-it commented on lib/Service/OpenProjectAPIService.php
> +			$term_id = $term->id;
or use `$term->id`

2024-02-08 10:50 UTC, individual-it commented on lib/Settings/Admin.php
> +			'all_terms_of_services_signed' => $anyTermsOfServiceUnsignedStatus
those both names don't match. What value does the variable hold?

2024-02-08 10:50 UTC, individual-it commented on src/components/AdminSettings.vue
> +		isALlTermsOfServiceSignedForUserOpenProject() {
```suggestion
		isAllTermsOfServiceSignedForUserOpenProject() {
```

2024-02-08 10:50 UTC, individual-it commented on src/components/admin/TermsOfServiceUnsigned.vue
> +						Sign any unsigned "Terms Of Services" for user "OpenProject".
should be translatable

2024-02-08 10:50 UTC, individual-it commented on src/components/admin/TermsOfServiceUnsigned.vue
> +						@click="signTOSForUserOpenProject">
```suggestion
						@click="signTermOfServiceForUserOpenProject">
```

2024-02-08 10:50 UTC, individual-it commented on src/components/admin/TermsOfServiceUnsigned.vue
> +		async signTOSForUserOpenProject() {
```suggestion
		async signTermOfServiceForUserOpenProject() {
```

2024-02-08 10:50 UTC, individual-it commented on appinfo/routes.php
> +		['name' => 'config#signTOSForUserOpenProject', 'url' => '/sign-tos-openproject', 'verb' => 'POST'],
```suggestion
		['name' => 'config#signTermOfServiceForUserOpenProject', 'url' => '/sign-term-of-service', 'verb' => 'POST'],
```

2024-02-08 11:02 UTC, SagarGi commented
Every steps below should sign the TOS (Terms of services) for user "OpenProject"
Manaul tests to do:
- [ ] Enable TOS app > create new terms of services > set up project folders
- [ ] Enable TOS app > set up project folders > create new terms of services
- [ ] Enable TOS app > set up project folders > reset all terms of services
- [ ] Enable TOS app > set up project folders > disable integration_app > create new terms of services > enable integration_app > sign the terms of services through modal.
- [ ] Enable TOS app > set up project folders > disable integration_app > create new terms of services > disable TOS app  > enable integration_app > enable TOS app

2024-02-08 11:17 UTC, SagarGi commented on lib/Listener/TOSEventListener.php
> +		} catch (Exception $e) {
signing terms of services only throws DB exception so only DB

2024-02-08 11:42 UTC, SagarGi commented on lib/Listener/TOSEventListener.php
> +use OCP\DB\Exception;
when signing the terms and services through `terms_of_service` app , exception can make it freeze. So i have logged error since it is from our app the sign of terms and services was unsuccessful.

2024-02-08 11:43 UTC, SagarGi commented on lib/Service/OpenProjectAPIService.php
> +	public function getAllTermsOfServicesAvailable(): array {
i have mocked it in UI tests so leaving i public.

2024-02-08 11:43 UTC, SagarGi commented on lib/Service/OpenProjectAPIService.php
> +	public function getAllTermsOfServicesSignedByUserOpenProject(): array {
i have mocked it in UI tests so leaving i public.

2024-02-08 12:08 UTC, individual-it commented on lib/Service/OpenProjectAPIService.php
> +	public function getAllTermsOfServicesSignedByUserOpenProject(): array {
That shows that you have a dependency in your function that should not be there.
I guess its `$signatoryMapper = new SignatoryMapper($this->db);`
You can create that variable in the layer above, e.g. like that:
```
	public function isALlTermsOfServiceSignedForUserOpenProject($signatoryMapper = null): bool {
		if ($this->isTermOfServiceAppEnabled() && $this->userManager->userExists(Application::OPEN_PROJECT_ENTITIES_NAME)) {
			$terms = $this->getAllTermsOfServiceAvailable();
                        if ($signatoryMapper === null) {
                           $signatoryMapper = new SignatoryMapper($this->db);
                        }
			$alreadySignedTermsIdForUserOpenProject = $this->getAllTermsOfServiceSignedByUserOpenProject($signatoryMapper);
			foreach ($terms as $term) {
				$term_id = $term->id;
				if (!in_array($term_id, $alreadySignedTermsIdForUserOpenProject)) {
					return false;
				}
			}
		}
		return true;
	}
```

And when you test `isALlTermsOfServiceSignedForUserOpenProject`, you can now mock `$signatoryMapper`, because that is the real "outside" class that you want to mock

2024-02-09 04:10 UTC, SagarGi commented on lib/Listener/TOSEventListener.php
> +use OCP\DB\Exception;
we do sign terms and services from `terms_of_service` app. incase of any db exception just to let know its through our app i though to put log.

2024-02-09 11:42 UTC, individual-it requested changes

2024-02-09 11:42 UTC, individual-it commented on lib/Listener/TermsOfServiceEventListener.php
> +use OCP\DB\Exception;
```suggestion
use OCP\DB\Exception as DBException;
```

and then catch DBException in line 76.
I feel like the name `Exception` is dangerous. I also got confused about if you wanted to catch `\Exception` or `OCP\DB\Exception`

2024-02-09 11:42 UTC, individual-it commented on tests/lib/Controller/ConfigControllerTest.php
> +	public function testsignTOSForUserOpenProject():void {
cammelCase here also

```suggestion
	public function testSignTOSForUserOpenProject():void {
```

2024-02-09 11:42 UTC, individual-it commented on tests/lib/Service/OpenProjectAPIServiceTest.php
> +	public function testIsALlTermsOfServiceSignedForUserOpenProject(array $availableTermsOfServices, array $alreadySignedTemrsOfServices, bool $expectedResult): void {
still `ALl` vs. `All`

2024-02-09 12:05 UTC, nabim777 commented
> @nabim777 @individual-it Every steps below should sign the TOS (Terms of services) for user "OpenProject" Manaul tests to do:
> 
> * [ ]  Enable TOS app > create new terms of services > set up project folders
> * [ ]  Enable TOS app > set up project folders > create new terms of services
> * [ ]  Enable TOS app > set up project folders > reset all terms of services
> * [ ]  Enable TOS app > set up project folders > disable integration_app > create new terms of services > enable integration_app > sign the terms of services through modal.
> * [ ]  Enable TOS app > set up project folders > disable integration_app > create new terms of services > disable TOS app  > enable integration_app > enable TOS app

I have manually checked it and everything seems to be working fine.

2024-02-12 07:58 UTC, individual-it approved these changes

2024-02-13 03:28 UTC, merged