add tests for file version
nextcloud/integration_openproject pull request #553
Opened 2024-01-09 09:17 UTC by nabim777

2024-01-19 04:23 UTC, SagarGi commented on tests/acceptance/features/api/setup.feature
> +  #issue of group folder https://github.com/nextcloud/groupfolders/issues/2718
```suggestion
  ## to locally run this test the "project folder" needs to be setup already
```

2024-01-19 04:23 UTC, SagarGi commented on tests/acceptance/features/api/setup.feature
> +  Scenario: upload file and no version is available inside group folder
```suggestion
  Scenario: check version of uploaded file inside a group folder
```

2024-01-19 04:23 UTC, SagarGi commented on tests/acceptance/features/api/setup.feature
> +    And the version folder of file "/OpenProject/OpenProject/project-demo/file.txt" for user "Carol" should contain "1" element
```suggestion
    Then the version folder of file "/OpenProject/OpenProject/project-demo/file.txt" for user "Carol" should contain "1" element
```

2024-01-19 04:23 UTC, SagarGi commented on tests/acceptance/features/api/setup.feature
> +    When user "Carol" deletes folder "/OpenProject/OpenProject/project-demo"
add then step after this

2024-01-19 04:23 UTC, SagarGi commented on tests/acceptance/features/api/setup.feature
> +    # issue of group folder https://github.com/nextcloud/groupfolders/issues/2718
```suggestion
   ## to locally run this test the "project folder" needs to be setup already
```

2024-01-19 04:23 UTC, SagarGi commented on tests/acceptance/features/api/setup.feature
> +  Scenario: upload a file twice with different content and version are available inside group folder
```suggestion
  Scenario: check version of uploaded file after an update inside a group folder
```

2024-01-19 04:23 UTC, SagarGi commented on tests/acceptance/features/api/setup.feature
> +    When user "Carol" deletes folder "/OpenProject/OpenProject/project-test"
add then step after it

2024-01-19 04:23 UTC, SagarGi commented on tests/acceptance/features/api/setup.feature
> +    #this step is done for deletion of folder
```suggestion
```

2024-01-19 04:23 UTC, SagarGi commented on tests/acceptance/features/api/setup.feature
> +    #this step is done for deletion of folder
```suggestion
```

2024-01-19 04:23 UTC, SagarGi commented on tests/acceptance/features/bootstrap/FilesVersionsContext.php
> +			"could not find $count version element(s) in \n" . $responseXml->asXML()
may be make message something like expected version but found version which would be easier to understand.

2024-01-19 10:49 UTC, SagarGi commented on .github/workflows/shared_workflow.yml
> +            '~@skip'
```suggestion
            matrix.nextcloudVersion == 'stable26' && '~@skipOnStable26'
```
this can be removed now since it is already in make command

2024-01-19 10:56 UTC, SagarGi commented on tests/acceptance/features/bootstrap/FilesVersionsContext.php
> +			'	</d:prop>' .
do we need to pass all this prob or simply `getetag`?

2024-01-22 09:01 UTC, phil-davis commented on tests/acceptance/features/bootstrap/FilesVersionsContext.php
> +			"Expected number of versions to be $count but get the actual number of versions to be $actualCount"
```suggestion
			"Expected the number of versions to be $count but the actual number of versions is $actualCount"
```

2024-01-22 10:49 UTC, nabim777 commented on tests/acceptance/features/api/groupFolder.feature
Oh! I forget to delete that

2024-01-24 04:13 UTC, phil-davis commented on .github/workflows/shared_workflow.yml
> +            }}
https://github.com/nextcloud/integration_openproject/actions/runs/7623821622/job/20764651429?pr=553
```
No scenarios
No steps
```
No scenarios were run with stable27.
https://github.com/nextcloud/integration_openproject/actions/runs/7623821622/job/20764652286?pr=553
No scenarios were run with stable28.
The FILTER_TAGS needs more logic so that it scenarios run for 27 and 28.

Note: 
stable25 ran 190 scenarios
stable26 ran 192 scenarios
Those look OK.

2024-01-24 04:17 UTC, SagarGi requested changes

2024-01-24 04:17 UTC, SagarGi commented on tests/acceptance/features/api/directUpload.feature
> +  @skipOnStable25
```suggestion
  # issue of group folder https://github.com/nextcloud/groupfolders/issues/2718
  @skipOnStable25
```

2024-01-24 04:17 UTC, SagarGi commented on tests/acceptance/features/api/directUpload.feature
> +  @skipOnStable25
```suggestion
  # issue of group folder https://github.com/nextcloud/groupfolders/issues/2718
  @skipOnStable25
```

2024-01-24 04:17 UTC, SagarGi commented on tests/acceptance/features/bootstrap/FilesVersionsContext.php
> +	 *
```suggestion
```

2024-01-25 04:48 UTC, SagarGi approved these changes
LGTM :+1:

2024-01-25 04:59 UTC, phil-davis approved these changes
LGTM, 190 to 194 scenarios are running for each nextcloud major version - good.

2024-01-25 05:00 UTC, merged