[OP#41128] switch to PKCE
nextcloud/integration_openproject pull request #56
Opened 2022-02-22 07:11 UTC by individual-it

use PKCE to connect  via OAuth

This change also allows it to omit the secret key

2022-02-24 10:29 UTC, individual-it commented
- [ ] ToDo: bring back the check for the secret + add tests for that see https://community.openproject.org/projects/nextcloud-integration/work_packages/41128/activity#activity-3

2022-02-25 03:28 UTC, individual-it commented
CC @Kharonus would be cool if you also could have a look on it

2022-02-25 07:00 UTC, kiranparajuli589 reviewed
lgtm :+1:

2022-02-25 10:21 UTC, Kharonus requested changes
Just one small change request, plus 2 questions. :D

2022-02-25 10:21 UTC, Kharonus commented on lib/Controller/ConfigController.php
> +			$validCodeVerifier = (\Safe\preg_match('/^[A-Za-z0-9\-._~]{128}$/', $codeVerifier) === 1);
regex should use `{43,128}`, as the verifier must be within 43 and 128 characters. I wouldn't enforce max length.

2022-02-25 10:21 UTC, Kharonus commented on lib/Controller/ConfigController.php
> +			$validCodeVerifier = (\Safe\preg_match('/^[A-Za-z0-9\-._~]{128}$/', $codeVerifier) === 1);
Where does the `$codeVerifier` comes from?

2022-02-25 10:21 UTC, Kharonus commented on src/components/OAuthConnectButton.vue
> +			return btoa(String.fromCharCode(...new Uint8Array(digest)))
Is this the php way to make a base64 url encode? ^^ I'm a bit surprised by the replacement actions.

2022-02-25 10:21 UTC, Kharonus commented on lib/Controller/ConfigController.php
> +			$validCodeVerifier = (\Safe\preg_match('/^[A-Za-z0-9\-._~]{128}$/', $codeVerifier) === 1);
nevermind, found it and that it is generated from caller context.

2022-02-25 10:21 UTC, Kharonus commented on src/components/OAuthConnectButton.vue
> +			const oauthState = this.generateRandomString(10)
what is the need of having this `oauthState` string here?

2022-02-25 11:17 UTC, individual-it commented on src/components/OAuthConnectButton.vue
> +			const oauthState = this.generateRandomString(10)
we need to save the state somewhere to be able to check it when requesting a token in https://github.com/nextcloud/integration_openproject/blob/a3b8ebf73e81d2425daefa9cd85a0146d310a933/lib/Controller/ConfigController.php#L121
So we generate it here and save it to the DB (in  https://github.com/nextcloud/integration_openproject/pull/56/files#diff-82450ababde1ab6945c0633d13fb1de0d6eacdd2a0e400890046c5d5a60ad34fR58) before redirecting to OpenProject 

generating the state in PHP would not work because the use could have multiple tabs open and then potentially the state send from the UI to OpenProject would not be the same as the remembered one

2022-02-25 12:14 UTC, Kharonus commented on src/components/OAuthConnectButton.vue
> +			const oauthState = this.generateRandomString(10)
seems legitimate! 👍🏽

2022-02-28 04:40 UTC, individual-it commented on src/components/OAuthConnectButton.vue
> +			return btoa(String.fromCharCode(...new Uint8Array(digest)))
This is JS, and the replace is seem to be needed see https://github.com/tonyxu-io/pkce-generator/blob/master/index.html#L28 or https://www.oauth.com/oauth2-servers/pkce/authorization-request/

2022-02-28 04:44 UTC, individual-it commented on lib/Controller/ConfigController.php
> +			$validCodeVerifier = (\Safe\preg_match('/^[A-Za-z0-9\-._~]{128}$/', $codeVerifier) === 1);
we have created a 128char string in https://github.com/nextcloud/integration_openproject/pull/56/files#diff-82450ababde1ab6945c0633d13fb1de0d6eacdd2a0e400890046c5d5a60ad34fR45
so why would be expect here anything else than 128 char?

2022-02-28 07:57 UTC, Kharonus commented on src/components/OAuthConnectButton.vue
> +			return btoa(String.fromCharCode(...new Uint8Array(digest)))
Thanks for the context ;) 👍🏽

2022-02-28 07:59 UTC, Kharonus commented on lib/Controller/ConfigController.php
> +			$validCodeVerifier = (\Safe\preg_match('/^[A-Za-z0-9\-._~]{128}$/', $codeVerifier) === 1);
Because code can change in time, and there are two different locations here, that will probably not everytime change together.

This line is a check, that validates a PKCE code verifier. It could be even a separate method, or provided by a service. It should not care about how the input is generated, but stick to the RFC specification IMHO.

2022-02-28 08:09 UTC, Kharonus approved these changes
LGTM! 👍🏽

2022-02-28 08:11 UTC, kiranparajuli589 approved these changes

2022-02-28 08:11 UTC, merged