add docs for api-test
nextcloud/integration_openproject pull request #565
Opened 2024-01-23 09:38 UTC by nabim777

In this PR , docs is added which is about running API test

2024-01-24 04:05 UTC, phil-davis commented on README.md
> +In order to run the specific scenrio only
```suggestion
In order to run only a specific scenario
```

2024-01-24 04:05 UTC, phil-davis commented on README.md
> +NEXTCLOUD_BASE_URL=http://localhost/server \                                                                                                                                            ─╯
```suggestion
NEXTCLOUD_BASE_URL=http://localhost/server \                                                                                                                                            
```

There seem to be some unexpected characters.

2024-01-24 04:09 UTC, SagarGi requested changes
I would suggest to make 2 command only.
1. Running all the suites
2. Running a specific suites or scenario 
Just Keep it simple.

2024-01-24 04:09 UTC, SagarGi commented on README.md
> +2. Run `NEXTCLOUD_BASE_URL=http://localhost/server make api-test`
```suggestion
3. Run `NEXTCLOUD_BASE_URL=http://localhost/server make api-test`
```

2024-01-24 04:09 UTC, SagarGi commented on README.md
> +The API tests start a full Nextcloud server and openProject_integration apps.
i cannot understand this?

2024-01-24 04:09 UTC, SagarGi commented on README.md
> +2. Goto path `server/apps/integration_openproject`
these are not needed.

2024-01-25 04:32 UTC, phil-davis commented on README.md
> +> Before API tests run, nextcloud instance needs to be ready, and also integration app needs to be enabled
```suggestion
> Before running the API tests, the nextcloud instance needs to be ready, and also the integration app needs to be enabled
```

2024-01-25 04:32 UTC, phil-davis commented on README.md
> +To run the whole acceptance test locally run the command below.
```suggestion
To run the whole of the acceptance tests locally run the command below.
```

2024-01-25 04:58 UTC, SagarGi approved these changes

2024-01-25 05:27 UTC, phil-davis approved these changes

2024-01-25 05:28 UTC, phil-davis commented
@nabim777 needs rebase to resolve the conflict for `makefile`

2024-01-25 07:10 UTC, phil-davis approved these changes

2024-01-25 07:11 UTC, merged