[WP#53002]Fix/wrong template for workpackage
nextcloud/integration_openproject pull request #580
Opened 2024-02-23 11:48 UTC by SagarGi

## Description
Some times the wrong template is in the description section which is not according to the project type selected. It is because in the code the request body is some how not cleaned up properly. This PR cleans up the request body when the request is for the project selection.

## Related Issue or Workpackage

- Fixes <issue_link>
- https://community.openproject.org/projects/nextcloud-integration/work_packages/53002/activity

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Updated `CHANGELOG.md` file

2024-03-05 11:28 UTC, individual-it commented on src/views/CreateWorkPackageModal.vue
> +						message: 'Status is not set to one of the allowed values.',
need to be translatable

2024-03-12 06:10 UTC, individual-it requested changes

2024-03-12 06:10 UTC, individual-it commented on src/views/CreateWorkPackageModal.vue
> +		// we need the all unmutated values when resetting the form
```suggestion
		// we need all unmutated values when resetting the form
```

2024-03-12 06:10 UTC, individual-it commented on src/views/CreateWorkPackageModal.vue
> +					this.type.label = (this.isTypeOrStatusAlreadyInAllowedList(previousProjectType, this.allowedTypes)) ? response.data.payload._links.type.title : ''
can we shorten the line for easier review?

2024-03-12 06:10 UTC, individual-it commented on tests/jest/views/CreateWorkpackageModal.spec.js
> +		it('should change description template is not edited or (changed)', async () => {
I don't understand that sentence

2024-03-12 06:10 UTC, individual-it commented on tests/jest/views/CreateWorkpackageModal.spec.js
> +		it('should make type empty when type for selected project is not available', async () => {
```suggestion
		it('should empty the type if that type is not available for the selected project', async () => {
```

2024-03-12 06:10 UTC, individual-it commented on tests/jest/views/CreateWorkpackageModal.spec.js
> +	it('should display error when project status is empty', async () => {
```suggestion
	it('should display an error when the project status is empty', async () => {
```

2024-03-12 06:10 UTC, individual-it commented on tests/jest/views/CreateWorkpackageModal.spec.js
> +		it('should make status empty when status for selected type is not available', async () => {
```suggestion
		it('should empty the status if this status is not available for the selected type', async () => {
```

2024-03-13 10:23 UTC, individual-it approved these changes

2024-03-14 09:48 UTC, SagarGi commented
@nabim777 can you do a QA for this PR playing around with the form before we merge once.

2024-03-18 12:01 UTC, nabim777 commented
> @nabim777 can you do a QA for this PR playing around with the form before we merge once.

It works fine for me and also this PR fixes the bug https://community.openproject.org/projects/nextcloud-integration/work_packages/53003/activity

2024-03-18 12:03 UTC, nabim777 approved these changes

2024-03-19 03:20 UTC, merged