Fix workpackage not found when searching workpackage
nextcloud/integration_openproject pull request #582
Opened 2024-03-05 12:00 UTC by SagarGi

## Description

## Related Issue or Workpackage

- Fixes <issue_link>

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Updated `CHANGELOG.md` file

2024-03-06 11:51 UTC, individual-it requested changes

2024-03-06 11:51 UTC, individual-it commented on CHANGELOG.md
> +- Fixes wrong option text while searching workpackage. [582](https://github.com/nextcloud/integration_openproject/pull/582)
```suggestion
- Fixes wrong option text while searching workpackage. [#582](https://github.com/nextcloud/integration_openproject/pull/582)
```

2024-03-06 11:51 UTC, individual-it commented on CHANGELOG.md
> -- Fix error log when fetching non-existent work package [#573](https://github.com/nextcloud/integration_openproject/pull/573)
why deleting those changelog lines?

2024-03-07 08:23 UTC, SagarGi commented on CHANGELOG.md
> -- Fix error log when fetching non-existent work package [#573](https://github.com/nextcloud/integration_openproject/pull/573)
I have made a PR related to it: https://github.com/nextcloud/integration_openproject/pull/584

2024-03-13 03:21 UTC, nabim777 commented on src/components/tab/SearchInput.vue
> +		},
The condition looks long.. so can we use switch statement

2024-03-14 05:05 UTC, nabim777 commented on src/components/tab/SearchInput.vue
> +					return t('integration_openproject', 'There were no workpackages found')
```suggestion
					return t('integration_openproject', 'No workpackages found')
```

2024-03-14 05:27 UTC, SagarGi commented on src/components/tab/SearchInput.vue
> +					return t('integration_openproject', 'There were no workpackages found')
I think no need to change the text. I was approved in the meeting we are gonna keep this text. Better to check it manually.

2024-03-14 06:00 UTC, nabim777 commented on src/components/tab/SearchInput.vue
> +					return t('integration_openproject', 'There were no workpackages found')
If so Ok then

2024-03-14 06:04 UTC, nabim777 commented on src/components/tab/SearchInput.vue
> +				return t('integration_openproject', 'Start typing to search')
```suggestion
				return t('integration_openproject', 'Start typing to search')
```

![Screenshot from 2024-03-14 10-54-49](https://github.com/nextcloud/integration_openproject/assets/61624650/e5112e62-37d9-43c4-b2c0-eda1e1dd3ac3)

Two messages that seem to be saying the same thing

2024-03-14 06:21 UTC, nabim777 commented on src/components/tab/SearchInput.vue
> +			return t('integration_openproject', '')
```suggestion
				// while workpackages are being searched we make the no text option empty
			default: return ''
			}
```

2024-03-14 06:25 UTC, nabim777 commented on src/components/tab/SearchInput.vue
> +			return t('integration_openproject', '')
```suggestion
			return  ''
```
I think no need to translate the empty string

2024-03-14 10:44 UTC, nabim777 approved these changes

2024-03-14 11:52 UTC, merged