adjust the panel content color
nextcloud/integration_openproject pull request #583
Opened 2024-03-06 03:57 UTC by nabim777

## Description

## Related Issue or Workpackage

- https://community.openproject.org/projects/nextcloud-integration/work_packages/52979/activity

## Screenshots (if appropriate):

### previously
![image](https://github.com/nextcloud/integration_openproject/assets/61624650/5a1de31d-e684-41dd-8050-ace799424a48)

![image](https://github.com/nextcloud/integration_openproject/assets/61624650/1fdf6d5c-7fbb-46cf-b19d-5aab05b2820f)

### Now
![image](https://github.com/nextcloud/integration_openproject/assets/61624650/987d8a7f-4f05-47bd-8e13-a981e1bc2009) 
![image](https://github.com/nextcloud/integration_openproject/assets/61624650/69b83b69-b9c9-4aa4-931d-1b099e5fcfda)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Updated `CHANGELOG.md` file

2024-03-06 09:44 UTC, SagarGi requested changes

2024-03-06 09:44 UTC, SagarGi commented on CHANGELOG.md
>  - Fix error log when fetching non-existent work package [#573](https://github.com/nextcloud/integration_openproject/pull/573)
```suggestion
```

2024-03-06 11:55 UTC, individual-it commented on CHANGELOG.md
>  - Fix error log when fetching non-existent work package [#573](https://github.com/nextcloud/integration_openproject/pull/573)
Please do that in a separate PR, every PR should only contain changes that relate to the description

2024-03-06 11:56 UTC, individual-it reviewed
please also test with the high-contrast themes

2024-03-07 04:03 UTC, SagarGi commented on CHANGELOG.md
>  - Fix error log when fetching non-existent work package [#573](https://github.com/nextcloud/integration_openproject/pull/573)
sure will create one!

2024-03-07 06:44 UTC, nabim777 commented
> please also test with the high-contrast themes

I think it works fine in high-contrast themes
## High contrast  mode
![image](https://github.com/nextcloud/integration_openproject/assets/61624650/e82c14eb-b9d9-4e6b-8f51-19b25d938b56)

## Dark theme with high contrast mode
![image](https://github.com/nextcloud/integration_openproject/assets/61624650/c3c0842d-8708-41b1-ada6-85632d823c32)

2024-03-07 10:55 UTC, individual-it requested changes

2024-03-07 10:55 UTC, individual-it commented on CHANGELOG.md
> +- Adjust the `Open project` panel's content color to match the `Upcoming events` panel's content. [#583](https://github.com/nextcloud/integration_openproject/pull/583)
I've just learned that we don't put in the links in the changelogs

2024-03-07 10:59 UTC, SagarGi commented
@nabim777  https://github.com/nextcloud/integration_openproject/pull/584 This PR has been merged please rebase it and push.

2024-03-12 05:58 UTC, individual-it commented on CHANGELOG.md
> +- Adjust the `Open project` panel's content color to match the `Upcoming events` panel's content. [#583](https://github.com/nextcloud/integration_openproject/pull/583)
So we need to do extra work when preparing the release. If the link is not needed I would suggest to remove it always, so when releasing we only need to change the header

2024-03-12 07:15 UTC, SagarGi commented on CHANGELOG.md
> +- Adjust the `Open project` panel's content color to match the `Upcoming events` panel's content. [#583](https://github.com/nextcloud/integration_openproject/pull/583)
Yeah that can be also done.

2024-03-12 09:38 UTC, SagarGi approved these changes
LGTM :+1:

2024-03-12 10:02 UTC, nabim777 commented
new workpackages are created to remove the `!` character from the dashboard content  [github-PR-link](https://github.com/nextcloud/integration_openproject/pull/590)

2024-03-12 10:08 UTC, individual-it approved these changes

2024-03-12 10:08 UTC, merged