[WP#52959]Added desciption for the checkbox in the usersettings
nextcloud/integration_openproject pull request #600
Opened 2024-03-15 06:58 UTC by SagarGi

## Description
This PR adds a user description for the user settings for each check box in the admin section and the personal section of the app.

## Related Issue or Workpackage

- Fixes https://community.openproject.org/projects/nextcloud-integration/work_packages/52959

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [x] Updated `CHANGELOG.md` file

2024-03-18 09:17 UTC, nabim777 commented
It's just a preference from me. 
May be little gap between them look better.

Before
![image](https://github.com/nextcloud/integration_openproject/assets/61624650/0b6be751-b168-429e-bb47-36f12deefb32)

When gap
![image](https://github.com/nextcloud/integration_openproject/assets/61624650/95c94e33-9a16-4cc6-a2c9-99100ec6f7e0)

2024-03-18 10:25 UTC, SagarGi commented
> It's just a preference from me. May be little gap between them look better.
> 
> Before ![image](https://private-user-images.githubusercontent.com/61624650/313615104-0b6be751-b168-429e-bb47-36f12deefb32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NTc3ODMsIm5iZiI6MTcxMDc1NzQ4MywicGF0aCI6Ii82MTYyNDY1MC8zMTM2MTUxMDQtMGI2YmU3NTEtYjE2OC00MjllLWJiNDctMzZmMTJkZWVmYjMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDEwMjQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkN2Q3ZTc0N2ViZjc2MWRmOTkwNDNkNWFiNTVhNmQyNWU5ZjA5NmZmMTE4OTgyY2ZhMjIwYWJlNjNlNmQ5ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I3aJl8oYv4zr1viRd4WbjVzFVpOTnSgfhQXX-u500gw)
> 
> When gap ![image](https://private-user-images.githubusercontent.com/61624650/313615253-95c94e33-9a16-4cc6-a2c9-99100ec6f7e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NTc3ODMsIm5iZiI6MTcxMDc1NzQ4MywicGF0aCI6Ii82MTYyNDY1MC8zMTM2MTUyNTMtOTVjOTRlMzMtOWExNi00Y2M2LWEyYzktOTkxMDBlYzZmN2UwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDEwMjQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhNzIwNjA5OTQyN2NkOTM0ZWYxNDFjMmY2MDQxYjFhMWMyNGE4MDI5YWU2NzM1YzFjN2NkZmFkNTkxOWUxMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qLVIs678P2bk3Wk-dEpkp-hm7qyqET6XnpVMIBOZ2T4)

Done! please check once again!

2024-03-18 11:35 UTC, individual-it requested changes

2024-03-18 11:35 UTC, individual-it commented on src/utils.js
> +}
I think, this is not translatable

2024-03-19 04:11 UTC, individual-it approved these changes

2024-03-19 06:34 UTC, merged