rearranging the readme file and create a docs
nextcloud/integration_openproject pull request #612
Opened 2024-03-27 07:25 UTC by nabim777

## Description

## Related Issue or Workpackage

- Fixes <issue_link>

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Updated `CHANGELOG.md` file

2024-03-27 10:30 UTC, SagarGi commented on README.md
>  - For documentation on how to set up the integration as an administrator, refer to [Nextcloud integration setup](https://openproject.org/docs/system-admin-guide/integrations/nextcloud/).
switch order may be. first administration set up is required and then only user guide once the admin setup is done!

2024-03-27 10:30 UTC, SagarGi commented on README.md
> +### 🧪 Running API tests
Also make this another documentation md.

2024-03-27 11:07 UTC, nabim777 commented on README.md
> +### 🧪 Running API tests
I think there are just a few lines that include the commands for running the test. It will be inconvenient to navigate to a different page in order to view the few lines of commands.

2024-04-03 08:49 UTC, SagarGi requested changes
can we also have all the `.md` file name in snake case instead of camel case?

2024-04-03 08:49 UTC, SagarGi commented on README.md
> +- [Setting up with SS](docs/settingUpWithSS.md)
```suggestion
- [Setting up Integration via Shell Script](docs/settingUpViaShellScript.md)
```

2024-04-03 08:49 UTC, SagarGi commented on README.md
> +- [Set up through docker](docs/setUpViaDocker.md)
```suggestion
- [Set up via docker](docs/setUpViaDocker.md)
```

2024-04-03 08:49 UTC, SagarGi commented on README.md
> +- [API for get file information](docs/getFileInformation.md)
```suggestion
- [APIs to get file information](docs/getFileInformation.md)
```

2024-04-03 08:49 UTC, SagarGi commented on README.md
> +- [Setting up as admin with API](docs/settingUpAsAdmin.md)
```suggestion
- [APIs for integration setup for admin](docs/settingUpAsAdmin.md)
```

2024-04-03 08:49 UTC, SagarGi commented on README.md
> +- [API for Direct Upload](docs/directUpload.md)
```suggestion
- [APIs for Direct Upload](docs/directUpload.md)
```

2024-04-04 11:19 UTC, SagarGi approved these changes
LGTM :+1:

2024-04-05 03:26 UTC, individual-it approved these changes

2024-04-05 03:31 UTC, merged