Support NC 29
nextcloud/integration_openproject pull request #621
Opened 2024-04-08 10:09 UTC by artonge

2024-04-08 10:17 UTC, SagarGi commented
Thanks @artonge for making PR for the support of NC-29 but we will be doing it iteration (phase by phase) wise. We also have a tickets for it. https://community.openproject.org/projects/nextcloud-integration/work_packages/53991

2024-04-09 04:59 UTC, SagarGi commented on .github/workflows/shared_workflow.yml
> +          if [[ "stable28" != "stable28" ]] || [[ "stable29" != "stable29" ]]
For now i am skipping `php stan` check for stable 29 as well. I came accross this ticket https://community.openproject.org/projects/nextcloud-integration/work_packages/50516/activity which needs to be followed as priority and i have also set priority as high to it as it needs to be followed. But we are running `php make stan` for stable 26 and 27. So we can merge this PR for now since we are working on droppnig `NC25` and adding support for `NC29` (very soon to be released).

2024-04-09 06:59 UTC, individual-it requested changes

2024-04-09 06:59 UTC, individual-it commented on tests/acceptance/features/api/capabilities.feature
> +                  "pattern": "^\\d+\\.\\d+\\.\\d+(?:-\\w+.\\d+)?$"
why this change?

2024-04-09 06:59 UTC, individual-it commented on .github/workflows/shared_workflow.yml
> +          if [[ "stable28" != "stable28" ]] || [[ "stable29" != "stable29" ]]
what should that line do? It will always evaluate to `false`

2024-04-09 08:26 UTC, SagarGi commented on tests/acceptance/features/api/capabilities.feature
> +                  "pattern": "^\\d+\\.\\d+\\.\\d+(?:-\\w+.\\d+)?$"
The regex did not worked for NC29 (not released) groupfolder `17.0.0-beta.1` is used. The pattern should have worked but there was some mistakes in the regex as we never faced situation where our app required version in pattern like `17.0.0-beta.1`.

2024-04-09 08:30 UTC, SagarGi commented on .github/workflows/shared_workflow.yml
> +          if [[ "stable28" != "stable28" ]] || [[ "stable29" != "stable29" ]]
My bad. I pushed the the wrong condition. I have updated.

2024-04-09 09:02 UTC, individual-it approved these changes

2024-04-10 03:38 UTC, merged