[WP#53958]Drop support for `NC25` from application code
nextcloud/integration_openproject pull request #622
Opened 2024-04-09 08:42 UTC by SagarGi

## Description
This PR drops support `NC25` from the integration application code.

## Related Issue or Workpackage

- Fixes <issue_link>

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Tests only (no source changes)

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [x] Updated `CHANGELOG.md` file

2024-04-10 11:31 UTC, individual-it requested changes

2024-04-10 11:31 UTC, individual-it commented on lib/Dashboard/OpenProjectWidget.php
> -				return $iconClass . ' nc-before-v24';
delete the class also from CSS

2024-04-11 04:29 UTC, SagarGi commented on lib/Dashboard/OpenProjectWidget.php
> -				return $iconClass . ' nc-before-v24';
Deleted. Just one use of it was present there.

2024-04-11 08:01 UTC, individual-it approved these changes

2024-04-11 08:01 UTC, merged