[WP#48598]Drop support for php7.4 and clean up code
nextcloud/integration_openproject pull request #624
Opened 2024-04-10 09:47 UTC by SagarGi

## Description
This PR clean up code related to `php7.4` support to run tests in CI.

## Related Issue or Workpackage

https://community.openproject.org/projects/nextcloud-integration/work_packages/48598/activity

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Updated `CHANGELOG.md` file

2024-04-10 11:49 UTC, individual-it requested changes

2024-04-10 11:49 UTC, individual-it commented on lib/Reference/WorkPackageReferenceProvider.php
> +		return $wpId ?? $referenceId;
why doing that?
`getWorkPackageIdFromUrl()` returns an int or null, but `getCacheKey` has to return a string or null. So this change should throw somewhere an error IMO

2024-04-10 11:49 UTC, individual-it commented on tests/lib/Reference/WorkPackageReferenceProviderTest.php
> +		MockObject            $configMock = null,
I think we should be able to do 
```suggestion
		?MockObject            $configMock = null,
```
and then we can even delete the PHPDoc section and don't have to maintain both

2024-04-11 04:16 UTC, SagarGi commented on lib/Reference/WorkPackageReferenceProvider.php
> +		return $wpId ?? $referenceId;
True. Will change according to it.

2024-04-11 04:20 UTC, SagarGi commented on tests/lib/Reference/WorkPackageReferenceProviderTest.php
> +		MockObject            $configMock = null,
Good to have PHPDoc but instead i cleared up the Type in parameters.

2024-04-11 11:29 UTC, SagarGi commented on tests/lib/Reference/WorkPackageReferenceProviderTest.php
> +		MockObject            $configMock = null,
I have created a `workpackage` related to updating the code according to php 8.0. This can be done as house keeping work.

2024-04-15 07:54 UTC, individual-it approved these changes

2024-04-15 07:54 UTC, merged