code maintenance: search input vue
nextcloud/integration_openproject pull request #63
Opened 2022-02-25 10:03 UTC by kiranparajuli589

### Description
- try-catch around Axios calls
- component state saved in constants
- improve response checks

### Related
https://community.openproject.org/projects/nextcloud-integration/work_packages/41295/activity
OP#41295

2022-02-25 10:28 UTC, individual-it requested changes
if no tests failed in such a refactoring, we don't have enough tests, so this is an opportunity to add some

2022-02-25 10:28 UTC, individual-it commented on src/components/tab/SearchInput.vue
> +				+ '=' + userName
used only once can be moved to `processWorkPackages`

2022-02-25 15:45 UTC, kiranparajuli589 commented on src/components/tab/SearchInput.vue
> -	},
no more required will be handled by the search event handler `makeSearchRequest`.

2022-02-28 07:24 UTC, individual-it requested changes

2022-02-28 07:24 UTC, individual-it commented on tests/jest/components/tab/SearchInput.spec.js
> +		])('should call method "processWorkPackages" if only the search request succeeds',
```suggestion
		])('should call method "processWorkPackages" only if the search request succeeds',
```

2022-02-28 07:24 UTC, individual-it commented on tests/jest/components/tab/SearchInput.spec.js
> +		])('should send search request only if the search text is greater than search threshold', async ({ search, expectedCallCount }) => {
can this be combined with 
`it('should be displayed if the length of words in searchbar is more than three', async () => {` ?

2022-02-28 07:24 UTC, individual-it commented on tests/jest/components/tab/SearchInput.spec.js
> +		it.each([200, 400, 401, 500])('should never left the state as loading', async (status) => {
duplication of `'sets states according to response status'` ?

2022-02-28 07:50 UTC, individual-it commented on src/components/tab/SearchInput.vue
> +			}
https://user-images.githubusercontent.com/2425577/155944570-bb71ccfd-f794-47e1-af24-8162b58bd4bf.mp4

2022-02-28 09:39 UTC, kiranparajuli589 commented on src/components/tab/SearchInput.vue
> +			}
this is due to the state update in the color attribute getter. I've removed the state update in the color attribute getter and just return an empty string if the request fails

2022-02-28 09:40 UTC, kiranparajuli589 commented on tests/jest/components/tab/SearchInput.spec.js
> -		it('should not be displayed if the length of words in searchbar decreases from more than 3 to less', async () => {
this is a feature of `makeSearchRequest` fn, so moved to the respective `describe`

2022-02-28 09:41 UTC, kiranparajuli589 commented on tests/jest/components/tab/SearchInput.spec.js
> -		it('should not be displayed if the length of words in searchbar decreases from more than 3 to less', async () => {
this snapshot should check if all work packages options are displayed correctly.

2022-02-28 09:41 UTC, kiranparajuli589 commented on tests/jest/components/tab/SearchInput.spec.js
> +				expect(searchList).toMatchSnapshot()
this snapshot should check if all work packages options are displayed correctly.

2022-02-28 09:45 UTC, kiranparajuli589 commented on tests/jest/components/tab/SearchInput.spec.js
> +		])('should send search request only if the search text is greater than search threshold', async ({ search, expectedCallCount }) => {
the test you mentioned is moved here and updated slightly.

2022-02-28 10:05 UTC, kiranparajuli589 commented on src/components/tab/SearchInput.vue
> +			}
this is due to the state update after every Axios request. introduced a separate loading state to handle the mentioned case.

2022-02-28 10:06 UTC, kiranparajuli589 commented on tests/jest/components/tab/SearchInput.spec.js
> +		it.each([200, 400, 401, 500])('should never left the state as loading', async (status) => {
the test you mention specifically checks the `checkStatusCode` function, but here we check for the state update after search request.

i've merged it with the test above `should call method "processWorkPackages" only if the search request succeeds`

2022-02-28 10:24 UTC, individual-it commented on src/components/tab/SearchInput.vue
> +			}
I don't think that is not needed. We have now 2 variables keeping the "same" information.
`checkStatusCode` does not need to set the state to OK, in case of `200` it can leave it as it is (`LOADING`) because that is the case, even the first request finished, the work is not done yet.
`if (this.isStateOk) {` can be changed to ether check for status `200` or allow to run `processWorkPackages` also if the state is `loading`

2022-02-28 10:25 UTC, individual-it commented on src/components/tab/SearchInput.vue
> +			}
the state `OK` should only be reached after all the work is done and not issue appeared

2022-03-01 06:19 UTC, kiranparajuli589 commented
@individual-it I've fixed the loading case as discussed above. Also, I've updated the test cases. Please review again.

2022-03-01 10:24 UTC, individual-it approved these changes

2022-03-01 10:24 UTC, merged