refactor-on-user-creation-carol
nextcloud/integration_openproject pull request #634
Opened 2024-04-29 06:28 UTC by nabim777

## Description

## Related Issue or Workpackage

- Fixes <issue_link>

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Updated `CHANGELOG.md` file

2024-05-08 10:39 UTC, SagarGi commented
```console
Given user "Carol" has been created with display-name "Carol Hansen"                                   # FeatureContext::userHasBeenCreatedWithDisplayName()
      │ string(24) "Retrying user creation 1"
      │ string(27) "Creating user Carolfailed!!"
      │ string(41) "Clearing up data for Carolif it exists!!!"
      │ string(24) "Retrying user creation 2"
      │ string(27) "Creating user Carolfailed!!"
      │ string(41) "Clearing up data for Carolif it exists!!!"
      │ string(24) "Retrying user creation 3"
      │ string(40) "User Carolhas been created successfully!"
      │ 
    And user "Carol" has created folder "/folder"                                                          # FeatureContext::userHasCreatedFolder()
      HTTP status code was not 201 while trying to create folder '/folder' for user 'Carol'
      Failed asserting that an array contains 429.
```
The failure of the carol creation and be again created by retry. But it fails in the next step with 429 status code

2024-05-10 04:47 UTC, SagarGi commented
Server logs for the failure of the CI:
```
{"reqId":"d2p8N86ab6owa1LuTQCD","level":3,"time":"2024-05-10T04:40:03+00:00","remoteAddr":"172.18.0.2","user":"admin","app":"ocs_api","method":"POST","url":"/ocs/v2.php/cloud/users","message":"Failed addUser attempt with invalid argument exception.","userAgent":"GuzzleHttp/7","version":"29.0.0.19","exception":{"Exception":"InvalidArgumentException","Message":"Login is invalid because files already exist for this user","Code":0,"Trace":[{"file":"/var/www/html/lib/private/User/Manager.php","line":451,"function":"validateUserId","class":"OC\\User\\Manager","type":"->","args":["*** sensitive parameters replaced ***",true]},{"file":"/var/www/html/lib/private/User/Manager.php","line":434,"function":"createUserFromBackend","class":"OC\\User\\Manager","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/apps/provisioning_api/lib/Controller/UsersController.php","line":504,"function":"createUser","class":"OC\\User\\Manager","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":232,"function":"addUser","class":"OCA\\Provisioning_API\\Controller\\UsersController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":138,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\Provisioning_API\\Controller\\UsersController"],"addUser"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\Provisioning_API\\Controller\\UsersController"],"addUser"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":338,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Provisioning_API\\Controller\\UsersController","addUser",["OC\\AppFramework\\DependencyInjection\\DIContainer"],["ocs.provisioning_api.users.adduser"]]},{"file":"/var/www/html/ocs/v1.php","line":66,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/ocsapp/cloud/users"]},{"file":"/var/www/html/ocs/v2.php","line":23,"args":["/var/www/html/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/html/lib/private/User/Manager.php","Line":758,"message":"Failed addUser attempt with invalid argument exception.","exception":{},"CustomMessage":"Failed addUser attempt with invalid argument exception."}}
```

There are similar issues on nextcloud reported: 
https://help.nextcloud.com/t/username-is-invalid-because-files-already-exist-for-this-user-during-fresh-install/79464
https://github.com/nextcloud/server/issues/21144

2024-05-13 14:00 UTC, nabim777 commented
Github Action log link: https://github.com/nextcloud/integration_openproject/actions/runs/9061677109/job/24893962745

```feature
  Scenario: Try to get token as non-existent user                                               # /__w/integration_openproject/integration_openproject/integration_openproject/tests/acceptance/features/api/directUploadPrepare.feature:144
    Given user "Carol" has been created                                                         # FeatureContext::userHasBeenCreated()
      │ string(29) "Retrying Caroluser deletion 1"
      │ string(24) "Retrying user creation 1"
      │ string(24) "----- create users -----"
      │ User Carol has been not been created previously!!{"ocs":{"meta":{"status":"failure","statuscode":101,"message":"Login is invalid because files already exist for this user"},"data":[]}}string(24) "Retrying user creation 2"
      │ string(24) "----- create users -----"
      │ User Carol has been not been created previously!!{"ocs":{"meta":{"status":"failure","statuscode":101,"message":"Login is invalid because files already exist for this user"},"data":[]}}string(24) "Retrying user creation 3"
```

Some `user files` might not have been destroyed even after `user` were deleted. 
This may be related to this issue:
https://github.com/nextcloud/server/issues/38680

2024-05-16 09:58 UTC, SagarGi commented
The main problem was the file system for carol it self. I removed it from the container when we have the 400 status code error, and after deleting the file system for the user in the container i am able to create the Carol in the second retry. I have used the docker command for now but i will do it through the volumes which is less costly.
```
| read+share                | SRG                       | RGDNVCK               |
        │ string(24) "Retrying user creation 1"
        │ string(142) "Error: {"ocs":{"meta":{"status":"failure","statuscode":101,"message":"Login is invalid because files already exist for this user"},"data":[]}}"
        │ string(28) "Creating user Carol failed!!"
        │ string(54) "Deleting Carol from file system using docker command!!"
        │ array(25) {
        │   [0]=>
        │   string(9) "total 156"
        │   [1]=>
        │   string(55) "drwxrwx---    8 www-data www-data   4096 May 16 09:50 ."
        │   [2]=>
        │   string(56) "drwxr-xr-x   28 www-data www-data   4096 May 16 09:40 .."
        │   [3]=>
        │   string(63) "-rw-r--r--    1 www-data www-data    542 May 16 09:40 .htaccess"
        │   [4]=>
        │   string(61) "-rw-r--r--    1 www-data www-data      0 May 16 09:40 .ocdata"
        │   [5]=>
        │   string(59) "drwxr-xr-x    2 www-data www-data   4096 May 16 09:50 Carol"
        │   [6]=>
        │   string(68) "drwxr-xr-x    3 www-data www-data   4096 May 16 09:40 __groupfolders"
        │   [7]=>
        │   string(64) "drwxr-xr-x 1123 www-data www-data  20480 May 16 09:50 __profiler"
        │   [8]=>
        │   string(59) "drwxr-xr-x    4 www-data www-data   4096 May 16 09:41 admin"
        │   [9]=>
        │   string(74) "drwxr-xr-x    5 www-data www-data   4096 May 16 09:40 appdata_ocobua0j2gpy"
        │   [10]=>
        │   string(68) "drwxr-xr-x    2 www-data www-data   4096 May 16 09:40 files_external"
        │   [11]=>
        │   string(64) "-rw-r--r--    1 www-data www-data      0 May 16 09:40 index.html"
        │   [12]=>
        │   string(67) "-rw-r-----    1 www-data www-data 100531 May 16 09:50 nextcloud.log"
        │   [13]=>
        │   string(9) "total 152"
        │   [14]=>
        │   string(55) "drwxrwx---    7 www-data www-data   4096 May 16 09:50 ."
        │   [15]=>
        │   string(56) "drwxr-xr-x   28 www-data www-data   4096 May 16 09:40 .."
        │   [16]=>
        │   string(63) "-rw-r--r--    1 www-data www-data    542 May 16 09:40 .htaccess"
        │   [17]=>
        │   string(61) "-rw-r--r--    1 www-data www-data      0 May 16 09:40 .ocdata"
        │   [18]=>
        │   string(68) "drwxr-xr-x    3 www-data www-data   4096 May 16 09:40 __groupfolders"
        │   [19]=>
        │   string(64) "drwxr-xr-x 1123 www-data www-data  20480 May 16 09:50 __profiler"
        │   [20]=>
        │   string(59) "drwxr-xr-x    4 www-data www-data   4096 May 16 09:41 admin"
        │   [21]=>
        │   string(74) "drwxr-xr-x    5 www-data www-data   4096 May 16 09:40 appdata_ocobua0j2gpy"
        │   [22]=>
        │   string(68) "drwxr-xr-x    2 www-data www-data   4096 May 16 09:40 files_external"
        │   [23]=>
        │   string(64) "-rw-r--r--    1 www-data www-data      0 May 16 09:40 index.html"
        │   [24]=>
        │   string(67) "-rw-r-----    1 www-data www-data 100531 May 16 09:50 nextcloud.log"
        │ }
        │ int(0)
        │ string(51) "Deleting user Carol from file system successfull!!!"
        │ int(404)
        │ string(24) "Retrying user creation 2"
        │ string(41) "User Carol has been created successfully!"
```
CC @individual-it @nabim777

2024-05-20 06:47 UTC, SagarGi commented
The log for deleting file system using docker command in CI:
```
Given user "Carol" has been created                                                  # FeatureContext::userHasBeenCreated()
      │ string(142) "Error: {"ocs":{"meta":{"status":"failure","statuscode":101,"message":"Login is invalid because files already exist for this user"},"data":[]}}"
      │ string(27) "Creating user Carol failed!"
      │ string(73) "Deleting the file system of Carol and retrying the user creation again..."
      │ string(57) "File system for user Carol has been deleted successfully!"
      │ 
```
For containers we could not map containers data to host (because mapped the host file system is created first which when mapped to container makes it empty). So we any how need the docker command in order to delete the users file system. CC @individual-it @nabim777

2024-05-20 08:35 UTC, nabim777 commented on tests/acceptance/features/bootstrap/FeatureContext.php
> +					"docker exec nextcloud  /bin/bash -c 'cd data && rm -rf $user'",
```suggestion
					"docker exec nextcloud  /bin/bash -c 'rm -rf /data/$user'",
```

can we do this?

2024-05-20 08:47 UTC, nabim777 commented on tests/acceptance/features/bootstrap/FeatureContext.php
> +		while ($retryCreate <= 5) {
```suggestion
		while ($retryCreate <= 5) {
```

Can we iterate it only for one time, when there is only 400 status code

2024-05-20 08:52 UTC, nabim777 commented on tests/acceptance/features/bootstrap/FeatureContext.php
> +		$this->createUserWithRetry($user, $userAttributes);
```suggestion
		$this->createUserWithRetry($user, $userAttributes);
		$this->theHttpStatusCodeShouldBe(200);
```

don't we need to check the status code in `given` statement

2024-05-20 09:10 UTC, nabim777 commented on tests/acceptance/features/bootstrap/FeatureContext.php
> +	 * When we run API tests in CI, the user file system frequently does not get deleted.
```suggestion
	 * When we run API tests in CI, the user file system frequently does not get deleted from the data directory.
```

2024-05-21 03:34 UTC, SagarGi commented on tests/acceptance/features/bootstrap/FeatureContext.php
> +		$this->createUserWithRetry($user, $userAttributes);
its checked in the function itself since we need to retry it its checked inside rather than with an explicit function.

2024-05-21 03:35 UTC, SagarGi commented on tests/acceptance/features/bootstrap/FeatureContext.php
> +		while ($retryCreate <= 5) {
no lets check for and retry for others as well  other than status code 200. Any how we want to create a user.

2024-05-21 06:38 UTC, nabim777 commented on tests/acceptance/features/bootstrap/FeatureContext.php
> +	 * When we run API tests in CI, the user file system frequently does not get deleted from the data directory.
```suggestion
	 * When we run API tests in CI, the user file system sometime does not get deleted from the data directory.
```

2024-05-22 05:39 UTC, individual-it requested changes

2024-05-22 05:39 UTC, individual-it commented on tests/acceptance/features/bootstrap/FeatureContext.php
> +			} else {
we should check if we really running on CI, locally this could have any side effects

2024-05-22 10:52 UTC, SagarGi commented on tests/acceptance/features/bootstrap/FeatureContext.php
> +			} else {
Done with CI env when running in github actions

2024-05-22 11:19 UTC, individual-it approved these changes

2024-05-22 11:19 UTC, merged