Update script
nextcloud/integration_openproject pull request #637
Opened 2024-05-06 11:39 UTC by SagarGi

## Description

## Related Issue or Workpackage

- Fixes <issue_link>

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Updated `CHANGELOG.md` file

2024-05-10 06:12 UTC, individual-it commented on lib/Service/OauthService.php
> +				'nextcloud_client_secret' => $this->crypto->decrypt($client->getSecret()),
why do we need this?

2024-05-10 06:15 UTC, individual-it commented on integration_setup.sh
> +	admin_config_status_with_project_folder=$(echo $admin_config_response | jq -r ".status_with_project_folder_setup_status")
maybe I don't understand the naming but it sounds to me that these values should be opposite of each other, so if `admin_config_status_with_project_folder == true` then `admin_config_status_without_project_folder == false`?

2024-05-10 06:16 UTC, individual-it commented on lib/Controller/ConfigController.php
> +			'status_with_project_folder_setup_status' => $appPasswordSetStatus
maybe we need other names, I got confused - see comment above

2024-05-10 06:21 UTC, individual-it commented on integration_setup.sh
> +    # we assume that the integration set up is done in both application
I don't see where we check the correct name and host, or is OpenProject doing that?

2024-05-10 06:23 UTC, individual-it commented on integration_setup.sh
> +    	log_info "You could try deleting the file storage '${OPENPROJECT_STORAGE_NAME}' in OpenProject and run the script again."
This will happen when the setup in Nextcloud is not complete or wrong, how will deleting the file-storage in OpenProject help?

2024-05-10 09:52 UTC, SagarGi commented on lib/Service/OauthService.php
> +				'nextcloud_client_secret' => $this->crypto->decrypt($client->getSecret()),
https://github.com/nextcloud/integration_openproject/pull/638 A separate PR has been made why this change was necessary!

2024-05-10 10:25 UTC, SagarGi commented on integration_setup.sh
> +	admin_config_status_with_project_folder=$(echo $admin_config_response | jq -r ".status_with_project_folder_setup_status")
I have renamed it. Please check if it makes sense now!

2024-05-10 10:26 UTC, SagarGi commented on integration_setup.sh
> +    	log_info "You could try deleting the file storage '${OPENPROJECT_STORAGE_NAME}' in OpenProject and run the script again."
Yes in case of any error we need a manual intervention so we need to do it from start and the openproject storage needs to be deleted.

2024-05-10 10:27 UTC, SagarGi commented on integration_setup.sh
> +    # we assume that the integration set up is done in both application
I have checked the messaged instead of the attribute from the response which is more readable.

2024-05-10 10:47 UTC, individual-it requested changes

2024-05-10 10:47 UTC, individual-it commented on integration_setup.sh
> +    if [[ "$count" -ne 2 ]]; then
What about making sure that there are only 2 error messages and make the variable names more explicit?

```suggestion
    error_count = 0
    host_already_taken = false
    name_already_taken = false
    for element in "${error_messages[@]}"; do
      if [[ "$element" == "Host has already been taken." ]]; then
          host_already_taken = true
      elif [[ "$element" == "Name has already been taken." ]]; then
          name_already_taken = true
      fi
      (( error_count +=1 ))
    done
    if [[ $host_already_taken != true || $name_already_taken != true || "$error_count" -ne 2  ]]; then
```

2024-05-10 10:47 UTC, individual-it commented on integration_setup.sh
> +    # we assume that the integration set up is done in both application
```suggestion
    # if the files storage is already created with the provided host and storage name
    # we assume that the integration set up is done in both application
    # to check that, we parse the error messages
    # if there are only two error messages and those are about the host and name being taken
    # we assume the setup is complete with the given parameters
```

2024-05-10 10:47 UTC, individual-it commented on integration_setup.sh
> +    	  log_success "Saving 'OpenProject' user application password to OpenProject was successful."
wrong indent?

2024-05-10 10:47 UTC, individual-it commented on lib/Controller/ConfigController.php
> +		// 2. without project folder setup (no app password)
isn't that the other way around that first the app if configured without project folder and then the project folder is added?
Or is it not about the order? Then "phase" is misleading. You could say: "there are two parts of the app configuration", one needs always to be setup, the other is optional

2024-05-10 11:10 UTC, SagarGi commented on lib/Controller/ConfigController.php
> +		// 2. without project folder setup (no app password)
No its not about the order. Yes i can change the comments.

2024-05-13 12:21 UTC, individual-it approved these changes

2024-05-14 05:41 UTC, merged