Some test plan for integration feature
nextcloud/integration_openproject pull request #639
Opened 2024-05-13 10:31 UTC by SagarGi

## Description

## Related Issue or Workpackage

- Fixes <issue_link>

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Updated `CHANGELOG.md` file

2024-06-12 08:49 UTC, phil-davis commented on docs/testing/smoke_testing.md
> +- [ ] Linked work package is appeared in the `OpenProject` Tab with a toast message.
```suggestion
- [ ] Linked work package appears in the `OpenProject` Tab with a toast message.
```

I don't know what a "toast message" is, but I suppose I would need to do the test steps and then I will see it.

2024-06-12 08:49 UTC, phil-davis commented on docs/testing/smoke_testing.md
> +- [ ] Link other work packages, refresh the `Nextcloud` instance and all the linked ones should appear in the `OpenProject` Tab.
"refresh the Nextcloud instance - I suppose you mean "reload the browser"?

2024-06-12 08:49 UTC, phil-davis commented on docs/testing/smoke_testing.md
> +- [ ] Unlink a work package and should be deleted from the `OpenProject` Tab with a toast message.
```suggestion
- [ ] Unlink a work package and it should be deleted from the `OpenProject` Tab with a toast message.
```

2024-06-12 08:49 UTC, phil-davis commented on docs/testing/smoke_testing.md
> +- [ ] Navigate to `Files` tab, click `link existing files`, select available files (for e.g welcome.txt) from nextcloud and link it to the work package.
```suggestion
- [ ] Navigate to `Files` tab, click `link existing files`, select available files (for e.g welcome.txt) from nextcloud and link it to the work package.
```
```suggestion
- [ ] Navigate to `Files` tab, click `link existing files`, select available files (for example, welcome.txt) from Nextcloud and link it to the work package.
```

2024-06-12 08:49 UTC, phil-davis commented on docs/testing/smoke_testing.md
> +- [ ] Navigate to `Files` tab, click `Upload files`, select available files from your local system (for e.g local.txt) and upload choosing the upload location.
```suggestion
- [ ] Navigate to `Files` tab, click `Upload files`, select available files from your local system (for e.g local.txt) and upload choosing the upload location.
```
```suggestion
- [ ] Navigate to `Files` tab, click `Upload files`, select available files from your local system (for example, local.txt) and upload choosing the upload location.
```

Either write "for example" or "e.g."

2024-06-12 08:49 UTC, phil-davis commented on docs/testing/smoke_testing.md
> +- [ ] Open the form to create work package from the nextcloud in `OpenProject` tab for a file/folder.
```suggestion
- [ ] Open the form to create work package from Nextcloud in the `OpenProject` tab for a file/folder.
```

2024-06-12 08:49 UTC, phil-davis commented on docs/testing/smoke_testing.md
> +- [ ] Now as an `OpenProject` admin, assign any of the `Demo Project` work package to created `OpenProject` user.
```suggestion
- [ ] Now as an `OpenProject` admin, assign any of the `Demo Project` work package to created `OpenProject` user.
```
```suggestion
- [ ] Now as an `OpenProject` admin, assign any of the `Demo Project` work packages to the created `OpenProject` user.
```

2024-06-12 08:49 UTC, phil-davis commented on docs/testing/smoke_testing.md
> +- [ ] Try to delete `OpenProject` or `OpenProject > Demo project(1)`, shoudl not be deleted.
```suggestion
- [ ] Try to delete `OpenProject` or `OpenProject > Demo project(1)`. They should not be deleted. 
```

2024-06-12 08:49 UTC, phil-davis commented on docs/testing/smoke_testing.md
> +- [ ] Run the `integration_setup.sh` script with to set up integration without project folder with following command:
```suggestion
- [ ] Run the `integration_setup.sh` script with to set up integration without project folder with the following command:
```

2024-06-12 08:49 UTC, phil-davis commented on docs/testing/smoke_testing.md
> +- [ ] Upon successful, try Smoke Test No 2 (Skip first check).
```suggestion
- [ ] Upon success, try Smoke Test No 2 (Skip first check).
```

2024-06-12 08:49 UTC, phil-davis commented on docs/testing/smoke_testing.md
> +- [ ] Upon successful, try Smoke Test No 4 (Skip first check).
```suggestion
- [ ] Upon success, try Smoke Test No 4 (Skip first check).
```

2024-06-13 07:04 UTC, SagarGi commented on docs/testing/smoke_testing.md
> +- [ ] Link other work packages, refresh the `Nextcloud` instance and all the linked ones should appear in the `OpenProject` Tab.
Yes exactly. Thanks!

2024-06-13 13:07 UTC, nabim777 commented on docs/testing/smoke_testing.md
> +- [ ] `Nextcloud` amdin should be connected as an `OpenProject` admin.
```suggestion
- [ ] `Nextcloud` admin should be connected as an `OpenProject` admin.
```

2024-06-13 13:07 UTC, nabim777 commented on docs/testing/smoke_testing.md
> +- [ ] Now `Project setings > File storages` option is visible
```suggestion
- [ ] Now `Project settings > File storages` option is visible
```

2024-06-13 13:15 UTC, nabim777 commented on docs/testing/smoke_testing.md
> +This file consists of some smoke testing to be done before integration application release (major and minor).
```suggestion
This file consists of some smoke testing to be done before integration_openproject application release (major and minor).
```

2024-06-17 07:48 UTC, individual-it requested changes

2024-06-17 07:48 UTC, individual-it commented on docs/testing/smoke_testing.md
> +- [ ] Navigate to `Administration > File storages` in `OpenProject`.
What about turning the sentences around, saying first where the action should be done?
```suggestion
- [ ] In `OpenProject` navigate to `Administration > File storages`.
```

2024-06-17 07:48 UTC, individual-it commented on docs/testing/smoke_testing.md
> +### 10. Check OpenProject Notification
Does this functionality rely on the integration app, or is it purely an OpenProject functionality?

2024-06-17 07:49 UTC, individual-it commented
also the release documentation should be adjusted: https://github.com/nextcloud/integration_openproject/blob/master/docs/release.md

2024-06-20 11:40 UTC, SagarGi commented on docs/testing/smoke_testing.md
> +### 10. Check OpenProject Notification
Its the notification that we get in the `openproject` widget in nextcloud for a user

2024-06-24 05:13 UTC, individual-it approved these changes

2024-06-24 05:42 UTC, phil-davis commented on docs/testing/smoke_testing.md
> +- [ ] Run the `integration_setup.sh` script with to set up integration without project folder with the following command:
```suggestion
- [ ] Run the `integration_setup.sh` script to set up integration without project folder with the following command:
```

2024-06-24 05:42 UTC, phil-davis commented on docs/testing/smoke_testing.md
> +### 9. Create a WorkPackage from the Nextcloud
```suggestion
### 9. Create a WorkPackage from Nextcloud
```

2024-06-24 05:43 UTC, phil-davis approved these changes

2024-06-25 03:34 UTC, merged