Added admin audit log for admin config integration setup
nextcloud/integration_openproject pull request #640
Opened 2024-05-21 11:39 UTC by SagarGi

## Description

## Related Issue or Workpackage

- Fixes <issue_link>

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Updated `CHANGELOG.md` file

2024-06-24 05:14 UTC, individual-it reviewed
is this something we want to have in 2.6 or only in 2.7?

2024-06-24 05:15 UTC, individual-it commented on lib/Service/OpenProjectAPIService.php
> +		if($this->isAdminAuditConfigSetCorrectly()) {
if the audit log is not setup correctly, would it make sense to log to the normal log file?

2024-06-24 10:31 UTC, SagarGi commented
> is this something we want to have in 2.6 or only in 2.7?

we will be having a patch release.

2024-06-25 08:30 UTC, individual-it requested changes

2024-06-25 08:30 UTC, individual-it commented on tests/lib/Service/OpenProjectAPIServiceTest.php
> +	public function testIsAdminAuditConfigSetCorrectly(int $logLevel, string $pathToAuditLog, array $logCondition, bool $isAdminAuditAppInstalled, bool $expectedResult): void {
too long line

2024-06-25 08:30 UTC, individual-it commented on lib/Controller/OpenProjectAPIController.php
> +		$oldOpenProjectOauthUrl = $this->config->getAppValue(
seems to be not used, why did the CI not catch it?

2024-06-25 08:30 UTC, individual-it commented on lib/Controller/ConfigController.php
> +				"OpenProject Integration admin configuration has been reset in application " . Application::APP_ID, true
there is no second parameter in `logToAuditFile`, why is CI not catching that?

2024-06-25 08:30 UTC, individual-it commented on CHANGELOG.md
> +- Audit logging in `/audit.log` for admin configuration.
```suggestion
- log admin configuration to  audit log (`/audit.log`) 
```

2024-06-25 08:30 UTC, individual-it commented on lib/Service/OpenProjectAPIService.php
> +use phpDocumentor\Reflection\Types\This;
what is that for?

2024-06-25 08:56 UTC, nabim777 commented on lib/Controller/OpenProjectAPIController.php
> +		$oldOpenProjectOauthUrl = $this->config->getAppValue(
There is a WP create that will address this CI [issue](https://community.openproject.org/projects/nextcloud-integration/work_packages/55940/activity?query_props=%7B%22c%22%3A%5B%22id%22%2C%22subject%22%2C%22type%22%2C%22status%22%2C%22assignee%22%5D%2C%22hi%22%3Atrue%2C%22g%22%3A%22%22%2C%22is%22%3Atrue%2C%22tv%22%3Afalse%2C%22hla%22%3A%5B%22status%22%2C%22priority%22%2C%22dueDate%22%5D%2C%22t%22%3A%22id%3Aasc%22%2C%22f%22%3A%5B%7B%22n%22%3A%22status%22%2C%22o%22%3A%22o%22%2C%22v%22%3A%5B%5D%7D%5D%2C%22ts%22%3A%22PT0S%22%2C%22pp%22%3A50%2C%22pa%22%3A2%7D).

2024-06-25 11:32 UTC, SagarGi commented on lib/Service/OpenProjectAPIService.php
> +use phpDocumentor\Reflection\Types\This;
Auto imported. Deleting it as it is not required.

2024-06-25 11:33 UTC, SagarGi commented on lib/Controller/ConfigController.php
> +				"OpenProject Integration admin configuration has been reset in application " . Application::APP_ID, true
will be solved by this WP [issue](https://community.openproject.org/projects/nextcloud-integration/work_packages/55940/activity?query_props=%7B%22c%22%3A%5B%22id%22%2C%22subject%22%2C%22type%22%2C%22status%22%2C%22assignee%22%5D%2C%22hi%22%3Atrue%2C%22g%22%3A%22%22%2C%22is%22%3Atrue%2C%22tv%22%3Afalse%2C%22hla%22%3A%5B%22status%22%2C%22priority%22%2C%22dueDate%22%5D%2C%22t%22%3A%22id%3Aasc%22%2C%22f%22%3A%5B%7B%22n%22%3A%22status%22%2C%22o%22%3A%22o%22%2C%22v%22%3A%5B%5D%7D%5D%2C%22ts%22%3A%22PT0S%22%2C%22pp%22%3A50%2C%22pa%22%3A2%7D).

2024-06-26 03:49 UTC, SagarGi commented
@nabim777 can you manually test it once.

2024-06-28 06:19 UTC, individual-it requested changes

2024-06-28 06:19 UTC, individual-it commented on lib/Controller/ConfigController.php
> +			"Nextcloud OAuth credential has been set on application " . Application::APP_ID
```suggestion
			"Nextcloud OAuth credential has been set in application " . Application::APP_ID
```

2024-06-28 06:19 UTC, individual-it commented on lib/Controller/ConfigController.php
> +				$this->openprojectAPIService->logToAuditFile(
what about logging what keys have been set?

2024-06-28 06:19 UTC, individual-it commented on lib/Controller/OpenProjectAPIController.php
> +					"OpenProject host url has been set to '$url' in application " . Application::APP_ID
in this function we don't set the URL, but only check if its correct, we should log the things only when they really happen

2024-06-28 06:54 UTC, SagarGi commented on lib/Controller/ConfigController.php
> +				$this->openprojectAPIService->logToAuditFile(
would be nice to have it as well.

2024-06-28 11:27 UTC, SagarGi commented on lib/Controller/OpenProjectAPIController.php
> +					"OpenProject host url has been set to '$url' in application " . Application::APP_ID
True changing it right away!

2024-07-01 05:16 UTC, individual-it approved these changes

2024-07-01 07:31 UTC, nabim777 approved these changes
Manually checked in server stable-26, 27, and 29 It works fine there

2024-07-02 08:58 UTC, merged