run psalm with all NC versions
nextcloud/integration_openproject pull request #642
Opened 2024-05-29 07:44 UTC by individual-it

## Description

## Related Issue or Workpackage

- Fixes <issue_link>

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Updated `CHANGELOG.md` file

2024-05-29 10:47 UTC, saw-jan commented on .github/workflows/shared_workflow.yml
> +      - name: PHP code analysis for phpstan
```suggestion
      - name: PHP code analysis - phpstan
```

2024-05-29 10:47 UTC, saw-jan commented on .github/workflows/shared_workflow.yml
> +      - name: PHP code analysis for psalm
```suggestion
      - name: PHP code analysis - psalm
```

2024-05-30 10:35 UTC, SagarGi commented
@nabim777 If we are able to make run psalm with all version of NC thenlets remove `phpstan` since we can achieve the same thing with psalm. I would suggest to remove `phpstan` from CI in this PR and make a workpackage to clear the things up with `phpstan`.
CC @individual-it

2024-05-30 10:39 UTC, SagarGi requested changes

2024-05-30 10:39 UTC, SagarGi commented on .github/workflows/shared_workflow.yml
>            fi
just `make psalm`

2024-05-30 10:39 UTC, SagarGi commented on tests/stub.phpstub
> +}
can you give a comment what's this actually needed for? can be useful in the future when someone come across it.

2024-05-31 04:27 UTC, nabim777 commented on tests/stub.phpstub
> + */
```suggestion
declare(strict_types=1);
/**
 * @copyright Copyright (c) 2024 Nabin Ale <nabinalemagar019@gmail.com>
 *
 * @license GNU AGPL version 3 or any later version
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
```
Other apps stub file contains this so should I need to add this or not here?
https://github.com/nextcloud/groupfolders/blob/master/tests/stub.phpstub#L5
https://github.com/nextcloud/user_retention/blob/main/tests/stub.phpstub#L4

2024-05-31 10:35 UTC, SagarGi approved these changes
LGTM :+1:

2024-05-31 10:40 UTC, SagarGi commented on tests/stub.phpstub
> + */
Can be added.

2024-06-01 08:06 UTC, individual-it commented on psalm.xml
> +				<!-- this is a class form terms_of_service app, which isn't cloned while doing static code analysis -->
It actually might be cloned, so I would rephrase the comment to something like:
```suggestion
				<!-- these classes belong to the terms_of_service app, which isn't compulsory, so might not exist while running psalm -->
```

same for other comments about missing classes

2024-06-01 08:06 UTC, individual-it commented on lib/AppInfo/Application.php
> +		/** @psalm-suppress InvalidArgument */
can we use normal single line comments?
`// @psalm-suppress InvalidArgument `
and also please add a comment about why we are suppressing this error

2024-06-01 08:06 UTC, individual-it commented on .github/workflows/shared_workflow.yml
> -            make phpstan
the PR description does not say anything about removing phpstan. Should that happen in this PR or is a separate see https://community.openproject.org/work_packages/55383/activity ?

2024-06-03 09:17 UTC, nabim777 commented on .github/workflows/shared_workflow.yml
> -            make phpstan
The reason behind removing the PHPstan from CI  is that there is a conflict on code analyzer between Psalm and PHPstan on CI and locally. https://github.com/nextcloud/integration_openproject/actions/runs/9284704953/job/25547647168 
In another PR, PHPstan will definitely removed so there will be just waste of time solving the conflict  between the two code analyzer in this PR. So, in this PR there is remove of the PHPstan from the CI and completely remove in another PR. Will be this Okay @individual-it ?

2024-06-03 10:29 UTC, nabim777 commented on lib/AppInfo/Application.php
> +		/** @psalm-suppress InvalidArgument */
using  `// @psalm-suppress InvalidArgument ` does not work. Could we use `/** @psalm-suppress InvalidArgument */` like other apps? @individual-it 
https://github.com/nextcloud/groupfolders/blob/b6fdec2266af3f40d50c0c90f42b5a53b97c7dbb/lib/Command/Scan.php#L53

https://github.com/nextcloud/all-in-one/blob/d6580b30ceccabad473fc519966e20b385d7c2dc/php/src/Docker/DockerActionManager.php#L756

2024-06-03 11:02 UTC, individual-it reviewed
LGTM

2024-06-03 11:27 UTC, merged