Update script according to extended OpenProject API
nextcloud/integration_openproject pull request #643
Opened 2024-06-03 07:20 UTC by SagarGi

## Description

## Related Issue or Workpackage

- Fixes <issue_link>

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Updated `CHANGELOG.md` file

2024-06-05 10:44 UTC, individual-it reviewed
what happens if the script is run with an older version of OP, that does not have the new API endpoint?
Do we need to be able to run the script with older versions of OP?

2024-06-05 11:34 UTC, SagarGi commented
> what happens if the script is run with an older version of OP, that does not have the new API endpoint? Do we need to be able to run the script with older versions of OP?

@individual-it  For this script we need `OpenProject` version `14.1.1` specifically.I totally forgot about that. May be we need to check the version in the script itself otherwise it will give error.

2024-06-05 11:44 UTC, individual-it commented
or we run the script on older versions without the new check

2024-06-06 03:30 UTC, SagarGi commented
> or we run the script on older versions without the new check

yes can be done. But anyways needs the `OpenProject` Version to be fetched!

2024-06-06 08:55 UTC, individual-it requested changes

2024-06-06 08:55 UTC, individual-it commented on integration_setup.sh
> +		log_success "File storage name '$OPENPROJECT_STORAGE_NAME' on OpenProject for integration has already been set up."
is it `in OpenProject` or `on OpenProject`? maybe @phil-davis can  give a hint

2024-06-06 08:55 UTC, individual-it commented on integration_setup.sh
> +    if [[ ${openproject_version} > "14.1.2" ]]; then
lets check this at the very beginning of the script and check for >= 14.2

2024-06-06 10:49 UTC, phil-davis commented on integration_setup.sh
> +		log_success "File storage name '$OPENPROJECT_STORAGE_NAME' on OpenProject for integration has already been set up."
"in OpenProject" sounds better - that is already done at line 246.
Other text, like at lines 242, 244 and 249, can be changed.

2024-06-07 06:41 UTC, SagarGi commented
hi @individual-it  I have create a WP for improving the log messages https://community.openproject.org/projects/nextcloud-integration/work_packages/55514 . That can be changed in the separate PR.

2024-06-07 08:27 UTC, SagarGi commented
@nabim777 can you check this script manually in older version and also `14.2.0`  of OpenProject?

2024-06-07 09:38 UTC, individual-it commented on integration_setup.sh
> +if [[ "$openproject_version" < "14.2.0" ]]; then
also this should not be hidden in the depths of the script, but somewhere on the top where is will be easy to find and adjust

2024-06-07 11:35 UTC, SagarGi commented on integration_setup.sh
> +if [[ "$openproject_version" < "14.2.0" ]]; then
sure i will make variable `MINIMUM_OP_VERSION` or name similar to it in ooder to make it work.

2024-06-10 05:18 UTC, phil-davis reviewed
IMO there is another PR coming after this that has various log_ messages reorganised and rewritten, so I didn't review the detail of those messages here.

2024-06-10 05:18 UTC, phil-davis commented on integration_setup.sh
> +# This script requires OpenProject Version >= 14.2.0
```suggestion
# This script requires OpenProject Version >= MINIMUM_OP_VERSION
```

If we mention 14.2.0 in a comment, then it will be easy to forget to update it in the future.

2024-06-10 05:18 UTC, phil-davis commented on integration_setup.sh
> +	log_error "This script requires OpenProject Version greater or equals to 14.2.0 but found version '$openproject_version'"
```suggestion
	log_error "This script requires OpenProject Version greater than or equal to 14.2.0 but found version '$openproject_version'"
```

2024-06-10 05:19 UTC, phil-davis commented on integration_setup.sh
> +	log_error "This script requires OpenProject Version greater or equals to 14.2.0 but found version '$openproject_version'"
And the constant `MINIMUM_OP_VERSION` needs to be substituted instead of hardcoded `14.2.0`

2024-06-10 06:38 UTC, phil-davis approved these changes

2024-06-10 09:27 UTC, individual-it approved these changes

2024-06-10 09:31 UTC, nabim777 commented
> @nabim777 can you check this script manually in older version and also `14.2.0` of OpenProject?

Checked in release openproject 14.1/14.2 :heavy_check_mark:

2024-06-10 09:33 UTC, nabim777 approved these changes
LGTM :+1:

2024-06-10 10:20 UTC, merged