Add support for integration_app in nextcloud master
nextcloud/integration_openproject pull request #649
Opened 2024-06-06 07:01 UTC by nabim777

## Description

## Related Issue or Workpackage

- Fixes <issue_link>

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Updated `CHANGELOG.md` file

2024-06-06 13:27 UTC, individual-it commented on lib/Service/OpenProjectAPIService.php
> -			'filters' => \Safe\json_encode($filters),
nextcloud seems not to use the `Safe` functions anymore and the support of thecodingmachine/safe was removed in https://github.com/nextcloud/3rdparty/pull/1799
We still should double-check if we rely somewhere on the functions throwing exceptions. With this change `json_encode` will return `false` on error and not throw an exception

2024-06-07 06:04 UTC, nabim777 commented on lib/Service/OpenProjectAPIService.php
> -			'filters' => \Safe\json_encode($filters),
we can use `'filters' => \Safe\json_encode(json_encode($filters, true, 512, JSON_THROW_ON_ERROR),` since it will throws an error.

2024-06-07 09:02 UTC, individual-it commented on lib/Service/OpenProjectAPIService.php
> -			'filters' => \Safe\json_encode($filters),
sounds good

2024-06-07 11:53 UTC, SagarGi commented on appinfo/info.xml
> +		<nextcloud min-version="26" max-version="30" />
change it to master?

2024-06-10 08:31 UTC, SagarGi commented on lib/Service/OpenProjectAPIService.php
> +	 * @throws \JsonException
```suggestion
	 * @throws OpenprojectResponseException|PreConditionNotMetException|OpenprojectErrorException|\JsonException
```

2024-06-10 09:24 UTC, individual-it requested changes
looks good to me, but CHANGELOG needs to be updated

2024-06-10 10:20 UTC, SagarGi approved these changes
LGTM :+1:

2024-06-10 10:42 UTC, individual-it approved these changes

2024-06-10 11:09 UTC, merged