add config for the psalm to check unused variables and parameter
nextcloud/integration_openproject pull request #655
Opened 2024-06-25 10:49 UTC by nabim777

## Description

## Related Issue or Workpackage

- Fixes <issue_link>

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Updated `CHANGELOG.md` file

2024-06-28 03:38 UTC, SagarGi commented
Lets put it in level 4 for now. We can make the configuration better in next PR. @nabim777 But create a WP before that.

2024-09-23 04:55 UTC, nabim777 commented on psalm.xml
> +			<directory name="../../**" />
```suggestion
			<directory name="../../**" />
```

it simply ignore error from server code error like

```error
Error: server/lib/public/BackgroundJob/TimedJob.php:92:32: MoreSpecificImplementedParamType: Argument 1 of OCP\BackgroundJob\TimedJob::execute has the more specific type 'OC\BackgroundJob\JobList', expecting 'OCP\BackgroundJob\IJobList' as defined by OCP\BackgroundJob\IJob::execute (see https://psalm.dev/140)
------------------------------
1 errors found
```

2024-09-23 05:56 UTC, individual-it requested changes

2024-09-23 05:56 UTC, individual-it commented on psalm.xml
> +<!--			<directory name="../**" />-->
is this line still needed? if not please delete it

2024-09-23 05:56 UTC, individual-it commented on tests/acceptance/features/bootstrap/FeatureContext.php
> +		return (int)(string) $fileId;
that does not look right to cast a value first to string and then to int, I have no idea why we have done that before.
Actually I think this function should return a string, because the id does not need to be an `int` it can be also a UUID

2024-09-30 08:41 UTC, individual-it requested changes
just small suggestions

2024-09-30 08:41 UTC, individual-it commented on tests/acceptance/features/bootstrap/FeatureContext.php
> +		$_responseAsJson = $responseAsJson->ocs->data;
```suggestion
		$dataOfResponse = $responseAsJson->ocs->data;
```

2024-09-30 08:41 UTC, individual-it commented on tests/acceptance/features/bootstrap/FeatureContext.php
> +			$_responseAsJson,
```suggestion
			json_decode($this->response->getBody()->getContents(),
```

2024-09-30 08:55 UTC, nabim777 commented on tests/acceptance/features/bootstrap/FeatureContext.php
> +		$_responseAsJson = $responseAsJson->ocs->data;
when we change the varaible name from `_responseAsJson` to `dataOfResponse` then we will get the following error:
```console
ERROR: UnusedVariable - tests/acceptance/features/bootstrap/FeatureContext.php:556:3 - $dataOfResponse is never referenced or the value is not used (see https://psalm.dev/077)
		$dataOfResponse = $responseAsJson->ocs->data;

```

this is due to the psalm configuration where I have added 
`findUnusedVariablesAndParams="true"`

we have to add `_` in the variable name so that psalm will not get the error

2024-09-30 08:56 UTC, nabim777 commented on tests/acceptance/features/bootstrap/FeatureContext.php
> +			$_responseAsJson,
same error cames
https://github.com/nextcloud/integration_openproject/pull/655#discussion_r1780695484

2024-09-30 11:07 UTC, individual-it approved these changes

2024-10-01 03:57 UTC, SagarGi approved these changes
LGTM :+1:

2024-10-01 03:57 UTC, merged