[WP #56254] Bug fixed related to avatar not found
nextcloud/integration_openproject pull request #665
Opened 2024-07-25 07:34 UTC by nabim777

## Description

## Related Issue or Workpackage

- [Fixes <issue_link>](https://community.openproject.org/work_packages/56254)

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Updated `CHANGELOG.md` file

2024-08-06 05:01 UTC, SagarGi requested changes

2024-08-06 05:01 UTC, SagarGi commented on lib/Service/OpenProjectAPIService.php
> +			}
```suggestion
			$imageMimeType = $response->getHeader('Content-Type');
			$imageData = $response->getBody();

            // check if response contains image
            if(empty($imageMimeType)) {
                throw new OpenprojectAvatarErrorException(
                    'The response does not contain an image content-type.'
                );
            }
			// check if response contains image
			if(!@imagecreatefromstring($imageData)) {
				throw new OpenprojectAvatarErrorException(
					'The response contains invalid image data.'
				);
			}
            // Create a temporary file
            $tempFile = tempnam(sys_get_temp_dir(), 'image');
            file_put_contents($tempFile, $imageData);
            // Get the MIME type of the temporary file
            $imageMimeTypeFromImageData = mime_content_type($tempFile);
            unlink($tempFile);
            if($imageMimeType != $imageMimeTypeFromImageData) {
                throw new OpenprojectAvatarErrorException(
                    'The content-type and mime-type of image not matched.'
                );
            }
```

2024-08-06 06:07 UTC, phil-davis commented on lib/Service/OpenProjectAPIService.php
> +					'The content-type and mime-type of image not matched.'
Or you could mention the mime-types so that the information goes into the log:
```suggestion
					"The content-type header is '$headerType' but the mime-type of the image is '$imageMimeType'."
```

2024-08-06 06:07 UTC, phil-davis commented on tests/lib/Service/OpenProjectAPIServiceTest.php
> +		imagecreatefromstring($result['avatar']);
IMO `imagecreatefromstring` returns `false` if it does not wowrk.
So you need to assert something about the return value.
https://www.php.net/manual/en/function.imagecreatefromstring.php

2024-08-06 06:07 UTC, phil-davis commented on tests/lib/Service/OpenProjectAPIServiceTest.php
> +		imagecreatefromstring($result['avatar']);
Same here, you need to assert something about the return value of `imagecreatefromstring`

2024-08-06 06:07 UTC, phil-davis commented on tests/lib/Service/OpenProjectAPIServiceTest.php
> +		imagecreatefromstring($result['avatar']);
Same here, you need to assert something about the return value of `imagecreatefromstring`

2024-08-06 07:19 UTC, phil-davis reviewed
Some comments are out-of-date.

2024-08-06 07:19 UTC, phil-davis commented on tests/lib/Service/OpenProjectAPIServiceTest.php
> +		//make sure its an image, if something else is returned it will throw an exception
```suggestion
		// make sure its an image
```

It doesn't throw an exception. You could make the comment short, like this suggestion. The name of `assertNotFalse` already gives the clue about what is being checked.

2024-08-06 07:19 UTC, phil-davis commented on tests/lib/Service/OpenProjectAPIServiceTest.php
> +		//make sure its an image, if something else is returned it will throw an exception
```suggestion
		// make sure its an image
```

2024-08-06 07:19 UTC, phil-davis commented on tests/lib/Service/OpenProjectAPIServiceTest.php
> +		//make sure its an image, if something else is returned it will throw an exception
```suggestion
		// make sure its an image
```

2024-08-06 07:19 UTC, phil-davis commented on tests/lib/Service/OpenProjectAPIServiceTest.php
>  		//make sure its an image, if something else is returned it will throw an exception
```suggestion
		// make sure its an image
```

2024-08-06 08:24 UTC, nabim777 commented on tests/lib/Service/OpenProjectAPIServiceTest.php
> +		//make sure its an image, if something else is returned it will throw an exception
Okay

2024-08-06 08:46 UTC, SagarGi commented on lib/Service/OpenProjectAPIService.php
> +			$headerType = $response->getHeader('Content-Type');
```suggestion
			$imageMimeType = $response->getHeader('Content-Type');
```
headerType does not make a bit of a sense here i guess

2024-08-06 08:46 UTC, SagarGi commented on lib/Service/OpenProjectAPIService.php
> +			$imageMimeType = mime_content_type($tempFile);
```suggestion
			$imageMimeTypeFromImageData = mime_content_type($tempImageFile);
```

2024-08-06 08:46 UTC, SagarGi commented on lib/Service/OpenProjectAPIService.php
> +			$tempFile = tempnam(sys_get_temp_dir(), 'image');
```suggestion
			$tempImageFile = tempnam(sys_get_temp_dir(), 'image');
```

2024-08-06 08:46 UTC, SagarGi commented on lib/Service/OpenProjectAPIService.php
> +			file_put_contents($tempFile, $imageData);
```suggestion
			file_put_contents($tempImageFile, $imageData);
```

2024-08-06 08:46 UTC, SagarGi commented on lib/Service/OpenProjectAPIService.php
> +			unlink($tempFile);
```suggestion
			unlink($tempImageFile);
```

2024-08-06 08:46 UTC, SagarGi commented on lib/Service/OpenProjectAPIService.php
> +			if ($headerType != $imageMimeType) {
```suggestion
			if ($imageMimeType  != $imageMimeTypeFromImageData) {
```

2024-08-06 08:46 UTC, SagarGi commented on lib/Service/OpenProjectAPIService.php
> +				'type' => $headerType,
```suggestion
				'type' => $imageMimeType ,
```

2024-08-06 08:46 UTC, SagarGi commented on lib/Service/OpenProjectAPIService.php
> +					"The content-type header is '$headerType' but the mime-type of the image is '$imageMimeType'."
```suggestion
					"The content-type header is '$imageMimeType ' but the mime-type of the image is '$imageMimeTypeFromImageData'."
```

2024-08-06 09:36 UTC, SagarGi approved these changes
LGTM :+1:  (If CI is happy)

2024-08-06 09:59 UTC, phil-davis commented
CI got a rate-limit error pulling docker containers. I guess that it needs to be run again in a few hours?

2024-08-06 11:14 UTC, SagarGi commented
> CI got a rate-limit error pulling docker containers. I guess that it needs to be run again in a few hours?

Yes we have a ticket fixing it with some caching. will do it after 2.7 release.

2024-08-07 04:57 UTC, phil-davis approved these changes

2024-08-07 05:32 UTC, merged