test real images
nextcloud/integration_openproject pull request #666
Opened 2024-07-25 13:46 UTC by individual-it

## Description

## Related Issue or Workpackage

- Fixes <issue_link>

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Updated `CHANGELOG.md` file

2024-07-29 06:43 UTC, nabim777 commented
fails in `stable-26, php 8` 
needs `php:^8.1` for the pact:`10.0.0-beta2`

I have tried locally in PHP 8.1 & 8.2 it runs successfully

2024-07-29 09:34 UTC, nabim777 commented on tests/lib/Service/OpenProjectAPIServiceTest.php
> +			);
```suggestion
			->setBody(
				new Binary(
					__DIR__ . "/../fixtures/openproject-icon.jpg",
					'image/jpeg'
				)
			);
```

there is a problem with content-type having lowercase, since from openproject side the response we get will be upper case `Content-Type` headers key

2024-07-29 09:45 UTC, individual-it commented on tests/lib/Service/OpenProjectAPIServiceTest.php
> +			);
`$response->getHeader('Content-Type')` will get the header correctly, the cases do not matter anymore 
see https://github.com/nextcloud/integration_openproject/pull/666/files#diff-acd9bb903dbec989fbe06b290cfcaed634a3f67d497845d4d6946fa1b6449c93R324
and also my comment in the original post

2024-07-30 08:18 UTC, phil-davis commented
Note: unit tests are now only run with PHP 8.1 and later. API tests are only run with PHP 8.2 and 8.3. The dev dependencies in composer PHP require at least PHP 8.1, so the API test suite has to use at least PHP 8.1.

Is there still any requirement to support PHP 8.0?
If so, do we need to find a way to run test code with PHP 8.1, but with the back-end server actually running PHP 8.0?

2024-07-30 08:21 UTC, phil-davis commented
To document the changes to PHP dependencies:
```
$ php --version
PHP 8.1.29 (cli) (built: Jun  6 2024 16:52:57) (NTS)
$ git checkout testRealImage
Switched to branch 'testRealImage'
Your branch is up to date with 'upstream/testRealImage'.
$ composer install
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Package operations: 3 installs, 37 updates, 19 removals
  - Removing monolog/monolog (2.9.3)
  - Removing league/uri-parser (1.4.1)
  - Removing league/uri-interfaces (2.3.0)
  - Removing league/uri (6.7.2)
  - Removing kelunik/certificate (v1.1.3)
  - Removing daverandom/libdns (v2.1.0)
  - Removing cash/lrucache (1.0.0)
  - Removing amphp/windows-registry (v0.3.3)
  - Removing amphp/sync (v1.4.2)
  - Removing amphp/socket (v1.2.1)
  - Removing amphp/serialization (v1.0.0)
  - Removing amphp/process (v1.1.7)
  - Removing amphp/parser (v1.1.1)
  - Removing amphp/log (v1.2.0)
  - Removing amphp/http-server (v2.1.8)
  - Removing amphp/http (v1.7.3)
  - Removing amphp/hpack (v3.2.1)
  - Removing amphp/dns (v1.2.3)
  - Removing amphp/cache (v1.4.0)
  - Upgrading symfony/polyfill-ctype (v1.29.0 => v1.30.0): Extracting archive
  - Upgrading symfony/polyfill-mbstring (v1.29.0 => v1.30.0): Extracting archive
  - Upgrading symfony/filesystem (v6.0.19 => v6.4.9): Extracting archive
  - Installing leongrdic/smplang (1.0.2): Extracting archive
  - Upgrading symfony/finder (v6.0.19 => v6.4.10): Extracting archive
  - Installing pact-foundation/composer-downloads-plugin (v2.1.1): Extracting archive
  - Upgrading symfony/deprecation-contracts (v3.0.2 => v3.5.0): Extracting archive
  - Upgrading symfony/yaml (v6.0.19 => v6.4.8): Extracting archive
  - Upgrading symfony/translation-contracts (v3.0.2 => v3.5.0): Extracting archive
  - Upgrading symfony/translation (v6.0.19 => v6.4.10): Extracting archive
  - Upgrading symfony/event-dispatcher-contracts (v3.0.2 => v3.5.0): Extracting archive
  - Upgrading symfony/event-dispatcher (v6.0.19 => v6.4.8): Extracting archive
  - Installing symfony/var-exporter (v6.4.9): Extracting archive
  - Upgrading symfony/service-contracts (v3.0.2 => v3.5.0): Extracting archive
  - Upgrading symfony/dependency-injection (v6.0.20 => v6.4.10): Extracting archive
  - Upgrading symfony/polyfill-intl-normalizer (v1.29.0 => v1.30.0): Extracting archive
  - Upgrading symfony/polyfill-intl-grapheme (v1.29.0 => v1.30.0): Extracting archive
  - Upgrading symfony/string (v6.0.19 => v6.4.10): Extracting archive
  - Upgrading symfony/console (v6.0.19 => v6.4.10): Extracting archive
  - Upgrading symfony/config (v6.0.19 => v6.4.8): Extracting archive
  - Upgrading react/stream (v1.3.0 => v1.4.0): Extracting archive
  - Upgrading composer/pcre (3.1.4 => 3.2.0): Extracting archive
  - Upgrading psr/http-message (1.1 => 2.0): Extracting archive
  - Upgrading guzzlehttp/psr7 (2.6.2 => 2.7.0): Extracting archive
  - Upgrading guzzlehttp/promises (2.0.2 => 2.0.3): Extracting archive
  - Upgrading guzzlehttp/guzzle (7.8.1 => 7.9.2): Extracting archive
  - Upgrading justinrainbow/json-schema (v5.2.13 => 5.3.0): Extracting archive
  - Upgrading symfony/stopwatch (v6.0.19 => v6.4.8): Extracting archive
  - Upgrading symfony/process (v6.0.19 => v6.4.8): Extracting archive
  - Upgrading symfony/polyfill-php81 (v1.29.0 => v1.30.0): Extracting archive
  - Upgrading symfony/polyfill-php80 (v1.29.0 => v1.30.0): Extracting archive
  - Upgrading symfony/options-resolver (v6.0.19 => v6.4.8): Extracting archive
  - Upgrading react/dns (v1.12.0 => v1.13.0): Extracting archive
  - Upgrading react/socket (v1.15.0 => v1.16.0): Extracting archive
  - Upgrading composer/semver (3.4.0 => 3.4.2): Extracting archive
  - Upgrading friendsofphp/php-cs-fixer (v3.58.1 => v3.60.0): Extracting archive
  - Upgrading pact-foundation/pact-php (7.2.0 => 10.0.0-beta2): Extracting archive
  - Upgrading myclabs/deep-copy (1.11.1 => 1.12.0): Extracting archive
  - Upgrading doctrine/instantiator (1.5.0 => 2.0.0): Extracting archive
  - Upgrading phpunit/phpunit (9.6.19 => 9.6.20): Extracting archive
  - Installing pact-foundation/pact-php:pact-ffi-headers (0.4.21)
  - Installing pact-foundation/pact-php:pact-ffi-lib (0.4.21): Extracting archive
  - Installing pact-foundation/pact-php:pact-stub-server (0.6.0): Extracting archive
Generating autoload files
70 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
```

2024-07-30 10:54 UTC, nabim777 commented
> Note: unit tests are now only run with PHP 8.1 and later. API tests are only run with PHP 8.2 and 8.3. The dev dependencies in composer PHP require at least PHP 8.1, so the API test suite has to use at least PHP 8.1.
> 
> Is there still any requirement to support PHP 8.0? If so, do we need to find a way to run API test code with PHP 8.1, but with the back-end server actually running PHP 8.0?

![image](https://github.com/user-attachments/assets/e8ea8291-d324-49f7-9f1e-6073872c845a)
As per the document of nexcloud system requirement, there is php-8.0 removed but 
still the nextcloud 26, 27, 28, and 29 support PHP 8.0 except master. So, I think there also needs to be run test in PHP 8.0.

2024-08-02 08:09 UTC, nabim777 commented
I have set up the CI to run the non-pact tests for PHP 8.0. Could you please review it @individual-it

2024-08-02 09:10 UTC, phil-davis approved these changes
LGTM if CI passes.

There is quite a lot of special checks to run as much of the tests as reasonably possible on PHP 8.0. When PHP 8.0 support is no longer required, someone will need to look back here and find all the bits of CI-related code that can be removed/reversed.

2024-08-02 09:36 UTC, individual-it commented on .github/workflows/shared_workflow.yml
> +          sed -i '/<php>/a \ <env name="PACT_MOCK_SERVER_HEALTH_CHECK_TIMEOUT" value="10"/>' phpunit.xml
I think you can leave `PACT_MOCK_SERVER_HEALTH_CHECK_TIMEOUT` permanently in the phpunit.xml file
pact 10 will not use it, but it should not do any harm
`PACT_MOCK_SERVER_PORT` should not be used or needed also for pact 7 as we are now looking for an unused port in https://github.com/nextcloud/integration_openproject/pull/666/files#diff-98e1cf54ef03e58a04b934f4854c8615c5c139b5b9c93b44c4230284d4cc51d5R531-R541

2024-08-02 09:37 UTC, individual-it commented on makefile
> +	vendor/phpunit/phpunit/phpunit --exclude-group ignoreFor8.0
maybe make the naming more explicit
```suggestion
	vendor/phpunit/phpunit/phpunit --exclude-group ignoreWithPHP8.0
```

2024-08-02 09:40 UTC, individual-it commented on .github/workflows/shared_workflow.yml
> +          sed -i '/<ignoreFiles>/a \ <file name="tests/lib/Service/OpenProjectAPIServiceTest.php"/>' psalm.xml
that seems not to work
```
Problem parsing /home/runner/work/integration_openproject/integration_openproject/psalm.xml:
  Error on line 15:
    Element '{https://getpsalm.org/schema/config}ignoreFiles': Character content other than whitespace is not allowed because the content type is 'element-only'.

2024-08-02 09:56 UTC, nabim777 commented on .github/workflows/shared_workflow.yml
> +          sed -i '/<ignoreFiles>/a \ <file name="tests/lib/Service/OpenProjectAPIServiceTest.php"/>' psalm.xml
Yeah It was wrong.
Now, I have updated it.

2024-08-02 16:50 UTC, nabim777 approved these changes
LGTM :+1:

2024-08-05 03:56 UTC, SagarGi requested changes

2024-08-05 03:56 UTC, SagarGi commented on .github/workflows/shared_workflow.yml
> +          cat composer.json
```suggestion
```

2024-08-05 03:56 UTC, SagarGi commented on .github/workflows/shared_workflow.yml
> +          composer update
```suggestion
          composer update
```

2024-08-05 03:56 UTC, SagarGi commented on .github/workflows/shared_workflow.yml
> +
cant we combine both in one?

2024-08-05 03:56 UTC, SagarGi commented on .github/workflows/shared_workflow.yml
> +
can't we combine it with upper step? seems like a lot of duplication

2024-08-05 07:12 UTC, SagarGi approved these changes
LGTM if CI is green!

2024-08-05 07:39 UTC, merged