ci: Reduce testing matrix
nextcloud/integration_openproject pull request #691
Opened 2024-08-27 16:03 UTC by nickvergessen

The CI runs of this app are unacceptable heavy.
Please reduce the matrix to something suitable. The change in `name: unit tests and linting` looks quite "decent".
The `name: API tests` change was just to prevent this PR from swallowing another 1h55m of CI time.

A recommended matrix is:
- Test each PHP version (8.1, 8.2, 8.3) with 1 database (mysql) against 1 server (stable30)
- Test each additional database (postgres) against 1 PHP (8.1 installs fastest) the latest supported server (stable30)
- Test each older server (stable26, …, stable29) with 1 PHP version (8.1 installs fastest) against 1 database (mysql) only

2024-08-27 16:05 UTC, skjnldsv approved these changes

2024-08-27 16:09 UTC, come-nc commented on .github/workflows/shared_workflow.yml
> +            phpVersion: 8.0
Your are excluding 8.0 but it’s not in phpVersion anymore?

2024-08-27 16:12 UTC, come-nc commented
icewind1991/nextcloud-version-matrix may help here, no?
Like in https://github.com/nextcloud/.github/blob/master/workflow-templates/phpunit-pgsql.yml for instance.

2024-08-27 16:49 UTC, nickvergessen commented on .github/workflows/shared_workflow.yml
>          exclude:
```suggestion
         include:
```

2024-08-28 03:39 UTC, SagarGi submitted a review, later dismissed
This app needs to support available enterprise version of `Nextcloud`. we are soon excluding `stable26`. But if this app is only the concern for having more CI times then we can make it less may be running database to only mysql. We are keeping php 8.0 because we can install `Nextcloud-26` and  `Nextcloud-27`. @nickvergessen

2024-08-28 03:39 UTC, SagarGi commented on .github/workflows/shared_workflow.yml
>          isScheduledEventNightly:
we require this when we run our pipeline from `cron` job

2024-08-28 03:41 UTC, SagarGi requested changes
@individual-it what do you think?

2024-08-28 04:59 UTC, nabim777 commented on .github/workflows/shared_workflow.yml
> +        phpVersionMinor: [ 3 ]
```suggestion
        phpVersionMinor: [ 3 ]
```
Would it be necessary to run API tests for other versions of Nextcloud and PHP as well?
Is what we have here is sufficient?@SagarGi @individual-it

2024-08-28 05:09 UTC, nabim777 commented on .github/workflows/shared_workflow.yml
>            - ${{github.event_name == 'schedule'}}
```suggestion
```

If there is supposed to be remove whole `exclude`

2024-08-28 05:19 UTC, nickvergessen commented on .github/workflows/shared_workflow.yml
>          isScheduledEventNightly:
I do not see it being consumed in the source code of this repository, but added it back

2024-08-28 05:36 UTC, nickvergessen commented on .github/workflows/shared_workflow.yml
> +        phpVersionMinor: [ 3 ]
I completed the fix and added the before and after list to the PR description

2024-08-28 06:06 UTC, nabim777 commented on .github/workflows/shared_workflow.yml
> -        nextcloudVersion: [ stable26, stable27, stable28, stable29, stable30 ]
Since this app supports Nextcloud versions 26 to 30, we need to ensure that our code is maintained accordingly. 
https://github.com/nextcloud/integration_openproject/blob/master/appinfo/info.xml#L44.

2024-08-28 06:08 UTC, nabim777 commented on .github/workflows/shared_workflow.yml
> +        nextcloudVersion: [ stable30 ]
```suggestion
        nextcloudVersion: [ stable30 ]
```
Since this app supports Nextcloud versions 26 to 30, we need to ensure that our code is maintained accordingly. 
https://github.com/nextcloud/integration_openproject/blob/master/appinfo/info.xml#L44.

2024-08-29 08:38 UTC, individual-it commented
If CI time is a concern, we can merge this reduced matrix and run the whole set of tests pre-release. That would introduce a little bit more time and risk for the release process, but that should be fine

2024-08-29 08:40 UTC, SagarGi commented
> If CI time is a concern, we can merge this reduced matrix and run the whole set of tests pre-release. That would introduce a little bit more time and risk for the release process, but that should be fine

@individual-it for PR lets keep it this way. But lets run all of the things in nightly which would be better for release process also!

2024-08-29 09:00 UTC, nickvergessen commented
> But lets run all of the things (all tests with different versions) in nightly which would be better for release process also!

The posted matrix (testing each Nextcloud version at least once, testing each Database version at least once, testing each PHP version at least once) should really be enough.
The likeliness of something failing only on a specific PHP+DB+Server combination is so low, that it does not qualify the burned energy here:
https://github.com/nextcloud/integration_openproject/actions/runs/10605760605
Every night you burn more than 8h of CI server time.
You can really be a bit more conservative here and think a little greener :leaves: 
Not even the Nextcloud server is tested in all combinations.

If you ever encountered an issue that qualifies such a huge matrix I'm happy to learn about the combination of PHP+DB+Server that failed while all other PHP versions passed on the same DB+Server, all other DBs passed on the same PHP+Server and all other Server passed on the same PHP+DB.

2024-08-29 09:04 UTC, SagarGi commented
> > But lets run all of the things (all tests with different versions) in nightly which would be better for release process also!
> 
> The posted matrix (testing each Nextcloud version at least once, testing each Database version at least once, testing each PHP version at least once) should really be enough. The likeliness of something failing only on a specific PHP+DB+Server combination is so low, that it does not qualify the burned energy here: https://github.com/nextcloud/integration_openproject/actions/runs/10605760605 Every night you burn more than 8h of CI server time. You can really be a bit more conservative here and think a little greener 🍃 Not even the Nextcloud server is tested in all combinations.
> 
> If you ever encountered an issue that qualifies such a huge matrix I'm happy to learn about the combination of PHP+DB+Server that failed while all other PHP versions passed on the same DB+Server, all other DBs passed on the same PHP+Server and all other Server passed on the same PHP+DB.

@nickvergessen sure may be lets do it your way if as it seems to be consuming more CI server time. I will once check how this PR goes for a scheduled event and then merge it. Thanks!

2024-08-29 09:13 UTC, SagarGi approved these changes
LGTM :+1: Thanks @nickvergessen for taking care of it!

2024-08-29 09:18 UTC, nabim777 approved these changes

2024-08-29 09:34 UTC, merged