Add support for nextcloud master
nextcloud/integration_openproject pull request #704
Opened 2024-09-11 11:16 UTC by nabim777

## Description

This PR added the support for the nexcloud master (31)

## Related Issue or Workpackage

- Fixes <issue_link>

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Updated `CHANGELOG.md` file

2024-09-12 06:24 UTC, individual-it approved these changes

2024-09-16 03:44 UTC, SagarGi commented on .github/workflows/shared_workflow.yml
> +            phpVersion: 8.3
I would suggest not to exclude stable30 for other PHP versions since it has not been officially released. How about running master branch for recommended php version of NC? @nabim777

2024-09-16 04:17 UTC, SagarGi commented
@nabim777  @individual-it i think all the endpoint for the group folders is now route to `ocs` endpoint in the current version (master). https://github.com/nextcloud/groupfolders/commit/749f8005d39c9bbd49ddfc919d4e3d07362d20b6

2024-09-16 04:25 UTC, nabim777 commented on .github/workflows/shared_workflow.yml
> +            phpVersion: 8.3
Ok adding pipeline for running nextcloud master with 8.3 and mysql

2024-09-17 09:22 UTC, SagarGi requested changes
is it possible to do that?

2024-09-17 09:22 UTC, SagarGi commented on tests/acceptance/features/bootstrap/GroupfoldersContext.php
> +	}
.

2024-09-18 03:37 UTC, SagarGi commented on tests/acceptance/features/bootstrap/GroupfoldersContext.php
> +		);
also check the response code here as well since it is a given step

2024-09-18 03:37 UTC, SagarGi commented on tests/acceptance/features/bootstrap/GroupfoldersContext.php
> +		$getGroupFolderVersion = $responseAsJson->ocs->data->capabilities->integration_openproject->groupfolder_version ?? null;
```suggestion
		$groupFolderVersion = $responseAsJson->ocs->data->capabilities->integration_openproject->groupfolder_version ?? null;
```

2024-09-18 09:05 UTC, SagarGi commented on tests/acceptance/features/bootstrap/GroupfoldersContext.php
> +		$GroupFolderVersion = $responseAsJson->ocs->data->capabilities->integration_openproject->groupfolder_version ?? null;
```suggestion
		$groupFolderVersion = $responseAsJson->ocs->data->capabilities->integration_openproject->groupfolder_version ?? null;
```

2024-09-18 09:05 UTC, SagarGi commented on tests/acceptance/features/bootstrap/GroupfoldersContext.php
> +			$this->groupFolderVersion = $GroupFolderVersion;
```suggestion
			$this->groupFolderVersion = $groupFolderVersion;
```

2024-09-18 09:05 UTC, SagarGi commented on tests/acceptance/features/bootstrap/GroupfoldersContext.php
> +	}
can you use `AssertNotNull` if available assertion instead of explicit exception

2024-09-18 11:22 UTC, SagarGi reviewed
LGTM :+1:

2024-09-18 11:27 UTC, SagarGi commented on tests/acceptance/features/bootstrap/GroupfoldersContext.php
> +		var_dump($this->groupFolderVersion);
```suggestion
```

2024-09-20 11:12 UTC, individual-it requested changes

2024-09-20 11:12 UTC, individual-it commented on tests/acceptance/features/bootstrap/GroupfoldersContext.php
> +	 * @Given groupfolder DAV path has been set
This is a Given step, but in the feature file used as "When".
Please ether change the feature file or run this code in a Before hook

2024-09-24 08:21 UTC, nabim777 commented on tests/acceptance/features/bootstrap/GroupfoldersContext.php
> +	 * @Given groupfolder DAV path has been set
I have put in the given statement Is that Ok

2024-09-24 08:58 UTC, individual-it requested changes

2024-09-24 08:58 UTC, individual-it commented on lib/Service/OauthService.php
> +		}
can we reduce this repetition with lib/Listener/LoadAdditionalScriptsListener.php ?

2024-09-26 04:06 UTC, individual-it commented on tests/acceptance/features/bootstrap/FeatureContext.php
> +	public function setupGroupFolderDavPath():void {
```suggestion
	public function getGroupFolderDavPath():string {
```

2024-10-03 09:20 UTC, SagarGi commented on lib/VersionUtil.php
> +		// for nextcloud above 31 OC_Util::getVersionString() method not exists
```suggestion
		// for nextcloud above 31 OC_Util::getVersionString() method does not exists
```

2024-10-03 10:08 UTC, individual-it commented on .github/workflows/shared_workflow.yml
> +        - nextcloudVersion: stable30
why changing this indent?

2024-10-03 10:08 UTC, individual-it commented on lib/VersionUtil.php
> +class VersionUtil {
what about?
```suggestion
class ServerVersionHelper {
```

2024-10-03 10:08 UTC, individual-it commented on lib/VersionUtil.php
> +	public function getNextcloudVersion(): string {
you could do this function static and then you would not need to create a new object every time you need to know the version

2024-10-03 12:30 UTC, nabim777 commented on tests/acceptance/features/bootstrap/FeatureContext.php
> +		}
IMO, 
On before scenario, I have run this function `setGroupfolderDavPath` which stores string in the class variables `groupFolderDavPath` and by doing this function will runs once in every scenario 
**But**  
if we do returns then, function will run more than 1 times.

2024-10-04 04:12 UTC, SagarGi commented on tests/acceptance/features/bootstrap/GroupfoldersContext.php
> +	private function setGroupfolderDavPath(): void {
i am not quite sure why we want to run this before every scenario. Other scenario may not need. I would prefer to create a separate step to get the `groupfolder` path and use it wherever we need it. CC @individual-it

2024-10-04 04:15 UTC, nabim777 commented on tests/acceptance/features/bootstrap/GroupfoldersContext.php
> +	private function setGroupfolderDavPath(): void {
Or I think we can simply make a function that will get the group folder DAV path rather than running function and getting the groupfolder davpath on every before scenario.

2024-10-04 04:17 UTC, individual-it commented on tests/acceptance/features/bootstrap/GroupfoldersContext.php
> +	private function setGroupfolderDavPath(): void {
so why don't we just make it a function called `getGroupfolderDavPath()` and that returns the correct folder?
Everywhere we need it, we just call the getter. Why do we even access the private variable?
wouldn't it be clearer if we change
 `"$this->groupFolderDavPath". "apps/groupfolders/folders/" . $id;`
to
 `$this->getGroupfolderDavPath() . "apps/groupfolders/folders/" . $id;`
?

2024-10-04 04:27 UTC, SagarGi commented on tests/acceptance/features/bootstrap/GroupfoldersContext.php
> +	private function setGroupfolderDavPath(): void {
> so why don't we just make it a function called `getGroupfolderDavPath()` and that returns the correct folder? Everywhere we need it, we just call the getter. Why do we even access the private variable? wouldn't it be clearer if we change `"$this->groupFolderDavPath". "apps/groupfolders/folders/" . $id;` to `$this->getGroupfolderDavPath() . "apps/groupfolders/folders/" . $id;` ?

Yes that can also work but every time we want the `groupfolder path` we make an API request. My point was just make a single request and use it for the entire scenario whenever we need the groupfolder path. But for that a separate step needs to be created. But @nabim777 you can decide which one would be better.

2024-10-04 08:28 UTC, SagarGi commented on tests/acceptance/features/bootstrap/GroupfoldersContext.php
> +		// groupfolder with version greater then 19.0.0 uses "ocs/v2.php/" endpoint
```suggestion
		// groupfolder with version greater than or equals to 19.0.0 uses "ocs/v2.php/" endpoint
```

2024-10-04 10:24 UTC, SagarGi approved these changes
LGTM :+1:

2024-10-07 07:07 UTC, SagarGi reviewed
Better than previous. Other LGTM :+1:

2024-10-07 07:07 UTC, SagarGi commented on psalm.xml
> +				<!-- this class is only in stable31 so not exist while running psalm on lower version-->
```suggestion
				<!-- this class is only in Nextcloud version 31 and does not exist while running psalm on lower version-->
```

2024-10-07 07:07 UTC, SagarGi commented on psalm.xml
> +				<!-- this class is only in stable31 so not exist while running psalm on lower version-->
```suggestion
				<!-- this class is only in Nextcloud version 31 and does not exist while running psalm on lower version-->
```

2024-10-07 07:25 UTC, individual-it approved these changes

2024-10-07 08:29 UTC, merged