Update script according to storage API response of openproject (#707)
nextcloud/integration_openproject pull request #709
Opened 2024-10-07 10:13 UTC by SagarGi

### Description
This PR forward port the PR : https://github.com/nextcloud/integration_openproject/pull/707 to `master` branch

2024-10-07 12:13 UTC, individual-it requested changes

2024-10-07 12:13 UTC, individual-it commented on integration_setup.sh
> +checkForOpenProjectOrNextcloudIntegrationConfiguration() {
```suggestion
checkForOpenProjectAndNextcloudIntegrationConfiguration() {
```

Or even better split into two functions, one for OP, one for NC. Every function just does one thing

2024-10-08 03:22 UTC, SagarGi commented on integration_setup.sh
> +checkForOpenProjectOrNextcloudIntegrationConfiguration() {
Ah sure! I will may be first do that on release/2.7 and then do it here again.

2024-10-08 10:10 UTC, nabim777 approved these changes
LGTM if CI :green_heart:

2024-10-11 11:48 UTC, individual-it approved these changes

2024-10-11 11:48 UTC, merged