[WP#57970]Add/warn for group folder encryption
nextcloud/integration_openproject pull request #713
Opened 2024-10-08 10:00 UTC by SagarGi

## Description

## Related Issue or Workpackage

- Fixes https://community.openproject.org/projects/nextcloud-integration/work_packages/57970/activity

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Updated `CHANGELOG.md` file

2024-10-18 11:50 UTC, individual-it requested changes

2024-10-18 11:50 UTC, individual-it commented on src/components/AdminSettings.vue
> +				:is-there-group-folders-encryption-warning="showEncryptionWarningForGroupFolders"
any reason the names don't match each other?

2024-10-18 11:50 UTC, individual-it commented on src/components/AdminSettings.vue
> +							<b>{{ t('integration_openproject', 'Encryption for Group Folders are not enabled.') }}</b>
```suggestion
							<b>{{ t('integration_openproject', 'Encryption for the Group Folders App is not enabled.') }}</b>
```

2024-10-18 11:50 UTC, individual-it commented on src/components/AdminSettings.vue
> +						<p class="note-card--warning-description" v-html="getGroupFolderEncryptionWarningHint" /> <!-- eslint-disable-line vue/no-v-html -->
```suggestion
						<p class="note-card--warning-description" v-html="getGroupFoldersEncryptionWarningHint" /> <!-- eslint-disable-line vue/no-v-html -->
```

be consequent with singular/plural

2024-10-18 11:50 UTC, individual-it commented on src/components/AdminSettings.vue
> +			return t('integration_openproject', 'Server-side encryption is active, but encryption for group folders is not yet enabled. To ensure secure storage of files in project folders, please follow the
here `group folders` is written in lower case, please be consequent when referring to the Group Folders App

2024-10-18 11:52 UTC, SagarGi commented on src/components/AdminSettings.vue
> +				:is-there-group-folders-encryption-warning="showEncryptionWarningForGroupFolders"
Yes it can be changed according to the function name. `is-there-group-folders-encryption-warning`

2024-10-24 05:57 UTC, individual-it approved these changes

2024-10-24 05:57 UTC, merged