Do not show the connect button if admin config is not ok
nextcloud/integration_openproject pull request #73
Opened 2022-03-14 09:33 UTC by kiranparajuli589

### Related
https://community.openproject.org/projects/nextcloud-integration/work_packages/41211

2022-03-15 02:59 UTC, individual-it commented on lib/Service/OpenProjectAPIService.php
> +			&& !!($config->getAppValue(Application::APP_ID, 'oauth_instance_url'));
should we also validate the URL here with `OpenProjectAPIService::validateOpenProjectURL`? or only when saving it?

2022-03-15 03:06 UTC, individual-it requested changes
I think we also need an extra message for the user if the setting is not complete.
e.g. "OpenProject app has not been configured correctly, please contact the NextCloud administrator"

2022-03-15 03:06 UTC, individual-it commented on src/components/tab/EmptyContent.vue
> +			<div v-if="showConnect && showConnectButton" class="connect-button">
I think this is strange naming `showConnect` and `showConnectButton`
what about doing it similar to https://github.com/nextcloud/integration_openproject/pull/73/files#diff-7f773d424a0ea444e1702d381d14bfdd2abcdbb0b199669aa28978cba4d46faeR104-R107 ?

2022-03-15 07:44 UTC, kiranparajuli589 commented on lib/Service/OpenProjectAPIService.php
> +			&& !!($config->getAppValue(Application::APP_ID, 'oauth_instance_url'));
OAuth instance URL should also be valid for a successful connection. Added a check for URL too.

2022-03-15 07:44 UTC, kiranparajuli589 commented on src/components/tab/EmptyContent.vue
> +			<div v-if="showConnect && showConnectButton" class="connect-button">
fixed

2022-03-16 04:13 UTC, individual-it requested changes
just a little suggestion to change the text

2022-03-16 04:13 UTC, individual-it commented on src/components/OAuthConnectButton.vue
> +			return t('integration_openproject', 'Failed to establish connection. Please contact your administrator.')
```suggestion
			return t('integration_openproject', 'Settings of the OpenProject integration app are not complete. Please contact your NextCloud administrator.')
```

2022-03-16 05:47 UTC, individual-it approved these changes

2022-03-16 05:49 UTC, merged