Added authentication method selection in integration setup
nextcloud/integration_openproject pull request #737
Opened 2024-11-08 07:03 UTC by SagarGi

## Description

## Related Issue or Workpackage

- Fixes <issue_link>

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Tests only (no source changes)

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Updated `CHANGELOG.md` file

2024-12-11 03:47 UTC, individual-it requested changes
there are also a lot of long lines, please fix those also

2024-12-11 03:47 UTC, individual-it commented on lib/Controller/OpenProjectAPIController.php
> +		return null;
returning `null` when everything is fine feels somehow strange to me.
I could think of just returning `true` or maybe even an object `{bool, HTTPSTATUS}` so it will be `true` or `false` and then a suggested error to send back.

2024-12-11 03:47 UTC, individual-it commented on lib/Search/OpenProjectSearchProvider.php
> +			if ($accessToken === '' || !$searchEnabled) {
`getOIDCBasedTokenForTheTargetedAudienceClient` returns null or string, in other cases you have compared `$token === null`
is there a possibility that the token will be `''`? If yes then it should be checked inside `getOIDCBasedTokenForTheTargetedAudienceClient` and then returned `null`
But here now if you compare to an empty string and `getOIDCBasedTokenForTheTargetedAudienceClient` returns `null` your code will not enter the `if` statement

2024-12-11 03:47 UTC, individual-it commented on lib/Search/OpenProjectSearchProvider.php
> +		if ($authorizationMethod === OpenProjectAPIService::AUTH_METHOD_OIDC) {
`else`? or `if else`?

2024-12-11 03:47 UTC, individual-it commented on lib/Service/OpenProjectAPIService.php
> +	public function getOIDCBasedTokenForTheTargetedAudienceClient(string $targetedAudienceClientId): ?string {
you are always getting `$targetedAudienceClientId` via `$this->config->getAppValue(Application::APP_ID, 'targeted_audience_client_id', '')`. So why not just get in here?

2024-12-11 03:47 UTC, individual-it commented on src/components/AdminSettings.vue
> +					title="OIDC Provider"
not translatable

2024-12-11 03:47 UTC, individual-it commented on src/components/AdminSettings.vue
> +						OIDC provider *
not translatable

2024-12-11 03:47 UTC, individual-it commented on src/components/AdminSettings.vue
> +							input-label="OIDC Provider"
not translatable

2024-12-11 03:47 UTC, individual-it commented on src/components/AdminSettings.vue
> +					title="OpenProject client ID"
not translatable

2024-12-11 03:47 UTC, individual-it commented on src/components/AdminSettings.vue
> +		getSelectedAuthenticatedMethod() {
if none is selected it will return oauth2, is that intended?

2024-12-11 03:47 UTC, individual-it commented on src/components/AdminSettings.vue
> +		isAuthorizationMethodAlreadySelected() {
```suggestion
		isAuthorizationMethodSelected() {
```

2024-12-11 03:47 UTC, individual-it commented on src/components/AdminSettings.vue
> +		isAuthorizationSettingsAlreadySelected() {
```suggestion
		isAuthorizationSettingsSelected() {
```

2024-12-11 04:47 UTC, SagarGi commented on lib/Search/OpenProjectSearchProvider.php
> +			if ($accessToken === '' || !$searchEnabled) {
it will return null or string (not empty). I did mistake while copying the code :smile:

2024-12-12 06:07 UTC, individual-it commented on lib/Service/OpenProjectAPIService.php
> +		if (!self::isUserOIDCAppInstalledAndEnabled()) {
shouldn't that be `$this->isUserOIDCAppInstalledAndEnabled()` :confused: ?
same in getRegisteredOidcProviders

2024-12-12 06:07 UTC, individual-it commented on src/components/OAuthConnectButton.vue
> +                + ': ' + error.message,
:question:

2025-01-06 06:39 UTC, saw-jan commented on lib/Controller/ConfigController.php
> +			$runningFullResetWithOAuth2Auth ||
```suggestion
			// when the OP client information is for reset
			$runningFullResetWithOAuth2Auth ||
```

2025-01-06 06:39 UTC, saw-jan commented on lib/Search/OpenProjectSearchProvider.php
> +			}
`!accessToken` checks for falsy conditions (including `''`, `null`, `0`). but if we want to be strict then we can have `$accessToken === '' || $accessToken === null`
```suggestion
		if ($authorizationMethod === OpenProjectAPIService::AUTH_METHOD_OAUTH) {
			$accessToken = $this->config->getUserValue($user->getUID(), Application::APP_ID, 'token');
		} elseif ($authorizationMethod === OpenProjectAPIService::AUTH_METHOD_OIDC) {
			$accessToken = $this->service->getOIDCToken();
		}

		if (!$accessToken || !$searchEnabled) {
			return SearchResult::paginated($this->getName(), [], 0);
```

2025-01-06 06:39 UTC, saw-jan commented on lib/Service/OpenProjectAPIService.php
> +			$this->logger->debug('The user_oidc app is not installed/available');
```suggestion
			$this->logger->debug('The user_oidc app is not installed or enabled');
```

2025-01-06 11:03 UTC, saw-jan reviewed
Looks good :see_no_evil:

2025-01-09 11:37 UTC, saw-jan reviewed
:sparkles:  Let's merge this.

2025-01-10 05:39 UTC, individual-it approved these changes

2025-01-10 06:25 UTC, merged