refactor `getOpenProjectOauthURL` so that it throws an exception if any needed value is not set
nextcloud/integration_openproject pull request #75
Opened 2022-03-16 08:59 UTC by kiranparajuli589

### Related
OP#41211 > 3rd todo item
https://community.openproject.org/projects/nextcloud-integration/work_packages/41211

2022-03-17 03:25 UTC, individual-it requested changes

2022-03-17 03:25 UTC, individual-it commented on src/components/PersonalSettings.vue
> -			requestUrl: loadState('integration_openproject', 'user-config').request_url,
don't we need this line for `this.requestUrl`?

2022-03-17 03:55 UTC, kiranparajuli589 commented on src/components/PersonalSettings.vue
> -			requestUrl: loadState('integration_openproject', 'user-config').request_url,
the request URL is a field in the `state`, so it is now returned from the computed section.

2022-03-18 07:49 UTC, individual-it approved these changes

2022-03-18 08:06 UTC, merged