Add ui for delete link
nextcloud/integration_openproject pull request #87
Opened 2022-03-22 10:35 UTC by SwikritiT

2022-03-24 11:23 UTC, kiranparajuli589 commented on tests/jest/views/ProjectsTab.spec.js
> +			expect(linkedWPActionMenu).toMatchSnapshot()
if `linkedWPActionMenu` is the button for triggering the menu? after clicking it, imo you've to expect the action button rather menu here.

2022-03-25 08:20 UTC, individual-it requested changes

2022-03-25 08:20 UTC, individual-it commented on src/views/ProjectsTab.vue
> +						Open in OpenProject
text should be translatable

2022-03-25 08:20 UTC, individual-it commented on src/views/ProjectsTab.vue
> +						Delete link
text should be translatable

2022-03-25 08:23 UTC, SwikritiT commented on tests/jest/views/ProjectsTab.spec.js
> +			expect(linkedWPActionMenu).toMatchSnapshot()
Yes, it is for triggering the menu. I've changed the name in the latest commit.

2022-03-25 09:54 UTC, kiranparajuli589 commented on tests/jest/views/ProjectsTab.spec.js
> +			const toggleMenu = wrapper.find(toggleMenuSelector)
```suggestion
			const toggleMenu = wrapper.find(toggleMenuSelector)
			expect(toggleMenu.exists()).toBeFalsy()
```
just to verify that the menu exists after the click.

2022-03-29 04:30 UTC, kiranparajuli589 commented on src/views/ProjectsTab.vue
> +					<ActionButton class="linked-workpackages--menu--openWorkPackage" icon="icon-openproject">
```suggestion
					<ActionButton class="linked-workpackages--menu--open" icon="icon-openproject">
```

2022-03-29 04:30 UTC, kiranparajuli589 commented on src/views/ProjectsTab.vue
> +					<ActionButton class="linked-workpackages--menu--deleteWorkPackage" icon="icon-delete">
```suggestion
					<ActionButton class="linked-workpackages--menu--delete" icon="icon-delete">
```

2022-03-29 04:30 UTC, kiranparajuli589 commented on tests/jest/views/ProjectsTab.spec.js
> +		it.only('should display the action menu in linked work packages', async () => {
```suggestion
		it.only('should display the action menu for linked work packages', async () => {
```

2022-03-29 04:30 UTC, kiranparajuli589 commented on tests/jest/views/ProjectsTab.spec.js
> +			await toggleMenu.find('button').trigger('click')
```suggestion
			expect(wrapper.find(menuPopOverSelector).isVisible()).toBeFalsy()
			await toggleMenu.find('button').trigger('click')
```
It would be more solid if you check for the action buttons existence before clicking the toggler.

2022-04-01 08:23 UTC, SwikritiT commented
https://www.figma.com/file/gtLQfPe09X7XugAH8L7dTy/Nextcloud-Integration?node-id=886%3A31892#173680750 design has been changed a little bit. So converting this to draft

2022-04-05 04:07 UTC, kiranparajuli589 commented on src/views/ProjectsTab.vue
> +					<img class="linked-workpackages--workpackage--unlink" :src="unlinkSvg">
now if we assign a click action to unlink, the implementations for the work package action will be inside ProjectsTab.
I suggest moving it inside the workPackage component itself.

2022-04-05 06:56 UTC, kiranparajuli589 commented on src/views/ProjectsTab.vue
> +			filter: contrast(0) brightness(0);
for dark theme, you need to set filter to `none`

2022-04-05 07:29 UTC, SwikritiT commented on src/views/ProjectsTab.vue
> +			filter: contrast(0) brightness(0);
It actually works for a dark theme too with the same filter, Probably due to the background color
![lightTheme](https://user-images.githubusercontent.com/41103328/161701484-caa86047-9d6d-4ed0-9968-ee5ed5910b0b.png)
![darkTheme](https://user-images.githubusercontent.com/41103328/161701492-e7ec27e4-12a6-4bfb-a7f7-bfb4d3007e41.png)
.

2022-04-05 07:32 UTC, SwikritiT commented on src/views/ProjectsTab.vue
> +			filter: contrast(0) brightness(0);
For the dark theme it looks like this, will it be too difficult to recognize?
![darkPointer](https://user-images.githubusercontent.com/41103328/161702085-aabacbbd-7403-48c4-ac9b-d60079fc447a.png)

2022-04-05 08:09 UTC, kiranparajuli589 commented on src/views/ProjectsTab.vue
> +			filter: contrast(0) brightness(0);
IMO it is visible and recognizable but odd

2022-04-05 08:36 UTC, SwikritiT commented on src/views/ProjectsTab.vue
> +			filter: contrast(0) brightness(0);
does this look better?
![darkFilter](https://user-images.githubusercontent.com/41103328/161713475-dccc4a72-dd38-4a9b-9f02-f4d94eb56bb5.png)

2022-04-05 08:39 UTC, kiranparajuli589 commented on src/views/ProjectsTab.vue
> +			filter: contrast(0) brightness(0);
looks much better :+1:

2022-04-07 11:53 UTC, kiranparajuli589 reviewed
lgtm :+1:

2022-04-12 10:25 UTC, individual-it approved these changes

2022-04-12 10:25 UTC, merged