Use debounced function to make new search request
nextcloud/integration_openproject pull request #91
Opened 2022-03-28 12:21 UTC by kiranparajuli589

2022-03-29 08:10 UTC, individual-it commented on src/components/tab/SearchInput.vue
> +			query = query.trim()
do we want to search for things like `new `?

2022-03-29 08:12 UTC, individual-it commented on tests/jest/components/tab/SearchInput.spec.js
> +				expect(workPackages.at(0).props()).toMatchSnapshot()
why checking only one and not all?

2022-03-29 08:13 UTC, individual-it commented on src/components/tab/SearchInput.vue
> +		}, 500),
put the number in some const?

2022-03-29 09:18 UTC, individual-it requested changes
small comments
but it seems not to work for me
![image](https://user-images.githubusercontent.com/2425577/160578539-0e3816e3-c335-417f-b249-04a06e64aa85.png)

2022-03-29 10:36 UTC, kiranparajuli589 commented on src/components/tab/SearchInput.vue
> +		}, 500),
done

2022-03-29 10:36 UTC, kiranparajuli589 commented on tests/jest/components/tab/SearchInput.spec.js
> +				expect(workPackages.at(0).props()).toMatchSnapshot()
fixed

2022-03-29 10:36 UTC, kiranparajuli589 commented on src/components/tab/SearchInput.vue
> +			query = query.trim()
trim removed

2022-03-29 10:43 UTC, kiranparajuli589 commented
> small comments but it seems not to work for me ![image](https://user-images.githubusercontent.com/2425577/160578539-0e3816e3-c335-417f-b249-04a06e64aa85.png)

@individual-it it works for me, can you please check again. I've checked with node v14 and v16 and it works for both. I'm using npm 8.5.0

2022-03-29 11:13 UTC, individual-it commented
something went wrong with CI, restarted

2022-04-01 06:39 UTC, individual-it approved these changes
works now.
Any way we could catch that kind of issue with tests, so that it would not happen again?

2022-04-01 07:29 UTC, kiranparajuli589 commented
> works now. Any way we could catch that kind of issue with tests, so that it would not happen again?

This was a javascript error. occ app enable/disable was working fine. I think we have to open the UI to check this. acceptance would have catched this problem.

2022-04-04 14:47 UTC, merged