Implement menu item's functions
nextcloud/integration_openproject pull request #92
Opened 2022-03-29 10:48 UTC by SwikritiT

2022-04-12 09:01 UTC, SwikritiT commented
needs base branch to be merged first https://github.com/nextcloud/integration_openproject/pull/87

2022-04-12 10:47 UTC, individual-it requested changes

2022-04-12 10:47 UTC, individual-it commented on lib/Service/OpenProjectAPIService.php
> +		$params['header'] = \Safe\json_encode($header);
I don't think we need that, the content-type is set in https://github.com/nextcloud/integration_openproject/pull/92/files#diff-acd9bb903dbec989fbe06b290cfcaed634a3f67d497845d4d6946fa1b6449c93R402

2022-04-12 10:47 UTC, individual-it commented on lib/Service/OpenProjectAPIService.php
> +		) {
```suggestion
		if (!isset($result['success'])) {
```

2022-04-12 10:47 UTC, individual-it commented on src/views/ProjectsTab.vue
> +					confirm: t('integration_openproject', 'unlink'),
```suggestion
					confirm: t('integration_openproject', 'Unlink'),
```

2022-04-12 10:47 UTC, individual-it commented on src/views/ProjectsTab.vue
> +							+ ': ' + error.response?.data?.message
will that potentially show some weird technical error message? If yes we should not show it at all. It should appear in the logs and that should be enough

2022-04-12 10:47 UTC, individual-it commented on src/views/ProjectsTab.vue
> +			response = await axios.delete(url)
if the first request does not work correctly this will send the `DELETE` request to a wrong URL, in that case we should nor send the DELETE at all

2022-04-12 10:47 UTC, individual-it commented on src/views/ProjectsTab.vue
> +					linkId = element.id
should we get out of the loop here as soon as the linkId is found, or do we want to look for the last one?

2022-04-12 10:47 UTC, individual-it commented on tests/jest/views/ProjectsTab.spec.js
> +// import * as dialogs from '@nextcloud/dialogs'
delete unneeded lines

2022-04-12 10:47 UTC, individual-it commented on tests/jest/views/ProjectsTab.spec.js
> +			await wrapper.find('.linked-workpackages--workpackage--unlink').trigger('click')
```suggestion
			await wrapper.find(workPackageUnlinkSelector).trigger('click')
```

2022-04-12 10:47 UTC, individual-it commented on tests/jest/views/ProjectsTab.spec.js
> +	describe('unlinkWorkPackage', () => {
I think we should also add tests for the case where one or both requests fail

2022-04-12 10:55 UTC, kiranparajuli589 commented on lib/Service/OpenProjectAPIService.php
> +				if ($response->getStatusCode() === 204) {
use Http::STATUS_NO_CONTENT
```suggestion
				if ($response->getStatusCode() === Http::STATUS_NO_CONTENT) {
```

2022-04-12 10:55 UTC, kiranparajuli589 commented on src/views/ProjectsTab.vue
> +		async getWorkPackageUrl(workpackageId, projectId) {
```suggestion
		async routeToTheWorkPackage(workpackageId, projectId) {
```

2022-04-12 10:55 UTC, kiranparajuli589 commented on src/views/ProjectsTab.vue
> +					confirm: t('integration_openproject', 'unlink'),
```suggestion
					confirm: t('integration_openproject', 'Unlink'),
```

2022-04-12 10:55 UTC, kiranparajuli589 commented on src/views/ProjectsTab.vue
> +					linkId = element.id
break here after match found? :thinking:

2022-04-12 10:55 UTC, kiranparajuli589 commented on tests/jest/views/ProjectsTab.spec.js
> +		it('opens it in open project', async () => {
opens what :)

2022-04-12 10:55 UTC, kiranparajuli589 commented on tests/jest/views/ProjectsTab.spec.js
> +	describe('onclick unlink', () => {
```suggestion
	describe('when workpackage unlink button is clicked', () => {
```

2022-04-12 10:55 UTC, kiranparajuli589 commented on tests/jest/views/ProjectsTab.spec.js
> +		it('a dailog box should be displayed', async () => {
```suggestion
		it('should display a confirmation dialog box', async () => {
```

2022-04-12 10:55 UTC, kiranparajuli589 commented on tests/jest/views/ProjectsTab.spec.js
> +	describe('on clicking the work package', () => {
```suggestion
	describe('when the workpackage is clicked', () => {
```

2022-04-26 03:56 UTC, SwikritiT commented on lib/Service/OpenProjectAPIService.php
> +		$params['header'] = \Safe\json_encode($header);
Not really it'll go inside the main if block only if the `param >0` https://github.com/nextcloud/integration_openproject/blob/a3a3b69f4515ffbb45874b206af09a95e6285e2a/lib/Service/OpenProjectAPIService.php#L384-L402

2022-04-26 09:11 UTC, kiranparajuli589 reviewed
lgtm :+1:

2022-04-26 11:51 UTC, individual-it approved these changes

2022-04-26 11:51 UTC, merged